### ISSUE TITLE
Severity 1: Swift Cookbook Install Error's

### ISSUE THREAD

**Issue by dcurran90** [rcbops/chef-cookbooks#259]
I've been following "rackspace-private-cloud-swift-install.pdf" guide (Until page 14). I set up everything up so far without error and created my rings. I tried to re-run the chef-client to distribute the ring but there were errors on proxy and storage nodes starting particular services

The proxy node encountered the following fatal error:
Error executing action `start` on resource 'service[swift-proxy]'

/var/log/upstart/swift-proxy.log:

Starting proxy-server...(/etc/swift/proxy-server.conf)
Traceback (most recent call last):
  File "/usr/bin/swift-proxy-server", line 22, in <module>
    run_wsgi(conf_file, 'proxy-server', default_port=8080, *_options)
  File "/usr/lib/python2.7/dist-packages/swift/common/wsgi.py", line 138, in run_wsgi
    loadapp('config:%s' % conf_file, global_conf={'log_name': log_name})
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, *_kw)
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 207, in invoke
    app = filter(app)
  File "/usr/lib/python2.7/dist-packages/keystone/middleware/auth_token.py", line 815, in auth_filter
    return AuthProtocol(app, conf)
  File "/usr/lib/python2.7/dist-packages/keystone/middleware/auth_token.py", line 210, in **init**
    self.signing_dirname = '%s/keystone-signing' % os.environ['HOME']
  File "/usr/lib/python2.7/UserDict.py", line 23, in **getitem**
    raise KeyError(key)
KeyError: 'HOME'

The storage nodes encountered the following fatal error:
Error executing action `start` on resource 'service[swift-account-reaper]'

/var/log/upstart/swift-account-reaper.log:
Starting account-reaper...(/etc/swift/account-server.conf)
Traceback (most recent call last):
  File "/usr/bin/swift-account-reaper", line 17, in <module>
    from swift.account.reaper import AccountReaper
  File "/usr/lib/python2.7/dist-packages/swift/account/reaper.py", line 27, in <module>
    from swift.common.direct_client import ClientException, \
  File "/usr/lib/python2.7/dist-packages/swift/common/direct_client.py", line 29, in <module>
    from swiftclient import ClientException, json_loads
ImportError: No module named swiftclient

**Comment by galstrom21** [comment]
moving to https://github.com/rcbops-cookbooks/swift/issues/61
