### ISSUE TITLE
Block Migration Failed

### ISSUE THREAD

**Issue by panpengjun** [rcbops/chef-cookbooks#262]
I found a bug, which probably is an openstack bug.
1. 364026-aio node
2. 364217-compute node
3. nova boot --flavor 1 --image cirros-image Test
4. nova live-migration --block_migrate 871e24ab-fc79-4dc9-8071-7b5dc1b50cd0 364217-compute (assume the id is 871e24ab-fc79-4dc9-8071-7b5dc1b50cd0 and the instance landed on 364026-aio)
5. nova show Test | grep -e 'vm_state' -e 'ATTR:host' -e 'status'
6. nova live-migration --block_migrate 871e24ab-fc79-4dc9-8071-7b5dc1b50cd0 364026-aio
7. nova show Test | grep -e 'vm_state' -e 'ATTR:host' -e 'status'
8. Repeat step 4 - 7.

vm status changed from MIGRATING to ACTIVE, but sill in the node where it should be migrated from. 

grep 'ERROR' nova-compute.log:

2012-11-02 10:24:13 ERROR nova.virt.libvirt.driver [-] [instance: 871e24ab-fc79-4dc9-8071-7b5dc1b50cd0] During wait destroy, instance disappeared.
2012-11-02 10:24:13 ERROR nova.openstack.common.rpc.amqp [-] Exception during message handling
2012-11-02 10:24:13 ERROR nova.openstack.common.rpc.common [-] Returning exception The supplied disk path (/var/lib/nova/instances/instance-00000003) already exists, it is expected not to exist. to caller
2012-11-02 10:24:13 ERROR nova.openstack.common.rpc.common [-] ['Traceback (most recent call last):\n', '  File "/usr/lib/python2.7/dist-packages/nova/openstack/common/rpc/amqp.py", line 275, in _process_data\n    rval = self.proxy.dispatch(ctxt, version, method, *_args)\n', '  File "/usr/lib/python2.7/dist-packages/nova/openstack/common/rpc/dispatcher.py", line 145, in dispatch\n    return getattr(proxyobj, method)(ctxt, *_kwargs)\n', '  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 2142, in pre_live_migration\n    self.driver.pre_block_migration(context, instance, disk)\n', '  File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 2556, in pre_block_migration\n    raise exception.DestinationDiskExists(path=instance_dir)\n', 'DestinationDiskExists: The supplied disk path (/var/lib/nova/instances/instance-00000003) already exists, it is expected not to exist.\n']
2012-11-02 10:24:20 ERROR nova.virt.libvirt.driver [-] [instance: 871e24ab-fc79-4dc9-8071-7b5dc1b50cd0] During wait destroy, instance disappeared.

**Comment by breu** [comment]
This caused an error because there is an untracked instance file on one of the nodes named /var/lib/nova/instances/instance-00000003.  This may have been caused by your earlier issues.  Delete the nodes, clean out /var/lib/nova/instances on all of the nodes, and try again.

**Comment by panpengjun** [comment]
Thanks Joe. This might be the reason. Since I could not produce #262, this never happened again. I am about to close it. Thanks again.
