### ISSUE TITLE
Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by amaltson** [rcbops/chef-cookbooks#322]
I'm getting further installing but I've now run an issue with the recipe not being able to log into the database. I've set up the example environment, is there anything else I should do? The chef run is below. Thank you!

```
2013-03-15T17:13:59-04:00] INFO: Processing ruby_block[cleanup insecure default mysql users] action create (mysql-openstack::server line 177)

================================================================================
Error executing action `create` on resource 'ruby_block[cleanup insecure default mysql users]'
================================================================================

Mysql::Error
------------
Access denied for user 'root'@'localhost' (using password: YES)

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb:187:in `new'
/var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb:187:in `block (2 levels) in from_file'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb

177: ruby_block "cleanup insecure default mysql users" do
178:   block do
179:     mysql_conn = Mysql.new(bind_ip, "root", node["mysql"]["server_root_password"])
180:     Chef::Log.info("Removing insecure default mysql users")
181:     mysql_conn.query("DELETE FROM mysql.user WHERE User=''")
182:     mysql_conn.query("DELETE FROM mysql.user WHERE Password=''")
183:     mysql_conn.query("DROP DATABASE IF EXISTS test")
184:     mysql_conn.query("FLUSH privileges")
185:   end
186:   only_if do
187:     mysql_conn = Mysql.new(bind_ip, "root", node["mysql"]["server_root_password"])
188:     exists = mysql_conn.query("SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'test'")
189:     exists.num_rows > 0
190:   end
191: end
192:

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb:177:in `from_file'

ruby_block("cleanup insecure default mysql users") do
  action "create"
  retries 0
  retry_delay 2
  block_name "cleanup insecure default mysql users"
  cookbook_name "mysql-openstack"
  recipe_name "server"
  block #<Proc:0x000000033e8ea8@/var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb:178>
  only_if { #code block }
end

[2013-03-15T17:13:59-04:00] ERROR: Running exception handlers
[2013-03-15T17:13:59-04:00] FATAL: Saving node information to /var/chef/cache/failed-run-data.json
[2013-03-15T17:13:59-04:00] ERROR: Exception handlers complete
[2013-03-15T17:13:59-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2013-03-15T17:13:59-04:00] FATAL: Mysql::Error: ruby_block[cleanup insecure default mysql users] (mysql-openstack::server line 177) had an error: Mysql::Error: Access denied for user 'root'@'localhost' (using password: YES)
```

**Comment by claco** [comment]
Is this by chance an attempt at a reinstall of the chef client after a previous failure? Wondering if there's an existing mysql grants file lying around with a previous password.

**Comment by amaltson** [comment]
@claco I've tried removing MySQL server and client and any grant files I could find with locate. Should there be a password in a databag? Thanks!

**Comment by breu** [comment]
@amaltson Remove the files that you removed above as well as delete the database directory /var/lib/mysql.

**Comment by amaltson** [comment]
@rackerjoe thank you, did that as well. Now I'm getting: `FATAL: Mysql::Error: ruby_block[cleanup insecure default mysql users] (mysql-openstack::server line 177) had an error: Mysql::Error: Can't connect to MySQL server on '0.0.0.0' (111)`

Do you think it might be worth while just reinstalling the OS? Thank you.

Full trace:

```
[2013-03-18T15:57:46-04:00] INFO: Processing ruby_block[cleanup insecure default mysql users] action create (mysql-openstack::server line 177)

================================================================================
Error executing action `create` on resource 'ruby_block[cleanup insecure default mysql users]'
================================================================================

Mysql::Error
------------
Can't connect to MySQL server on '0.0.0.0' (111)

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb:187:in `new'
/var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb:187:in `block (2 levels) in from_file'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb

177: ruby_block "cleanup insecure default mysql users" do
178:   block do
179:     mysql_conn = Mysql.new(bind_ip, "root", node["mysql"]["server_root_password"])
180:     Chef::Log.info("Removing insecure default mysql users")
181:     mysql_conn.query("DELETE FROM mysql.user WHERE User=''")
182:     mysql_conn.query("DELETE FROM mysql.user WHERE Password=''")
183:     mysql_conn.query("DROP DATABASE IF EXISTS test")
184:     mysql_conn.query("FLUSH privileges")
185:   end
186:   only_if do
187:     mysql_conn = Mysql.new(bind_ip, "root", node["mysql"]["server_root_password"])
188:     exists = mysql_conn.query("SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'test'")
189:     exists.num_rows > 0
190:   end
191: end
192:

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb:177:in `from_file'

ruby_block("cleanup insecure default mysql users") do
  action "create"
  retries 0
  retry_delay 2
  block_name "cleanup insecure default mysql users"
  cookbook_name "mysql-openstack"
  recipe_name "server"
  block #<Proc:0x0000000221e4e8@/var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb:178>
  only_if { #code block }
end

[2013-03-18T15:57:46-04:00] ERROR: Running exception handlers
[2013-03-18T15:57:46-04:00] FATAL: Saving node information to /var/chef/cache/failed-run-data.json
[2013-03-18T15:57:46-04:00] ERROR: Exception handlers complete
[2013-03-18T15:57:46-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2013-03-18T15:57:46-04:00] FATAL: Mysql::Error: ruby_block[cleanup insecure default mysql users] (mysql-openstack::server line 177) had an error: Mysql::Error: Can't connect to MySQL server on '0.0.0.0' (111
```

**Comment by mancdaz** [comment]
@amaltson seems like mysql is no longer running.  Your chef attributes for the node, and the state of packages on the system, have probably got themselves into a bit of a mess.  You could try purging mysql server from the system, deleting and re-adding the client/node from the chef server, and then running again.  Failing that, I'd go with a clean install.

**Comment by amaltson** [comment]
Did a clean install and everything works! Thanks!

**Comment by vskubriev** [comment]
I have similiar problem but some other.
Did an:
aptitude purge mysql-client mysql-common mysql-server mysql-server-5.5
   78  rm -R /var/lib/mysql/
   79  rm -R /etc/mysql/
   80  mkdir /etc/mysql
   81  chef-client
Is helping me.
But I don't understand why recipe don't create first /etc/mysql dir, before doing this fragment of recipe mysql::server code

template "#{node['mysql']['conf_dir']}/debian.cnf" do

I think that it is wrong. And Author should fix it.

Thank you.

**Comment by mancdaz** [comment]
@vskubriev you appear to be talking about issues with the mysql cookbook, which is maintained by opscode.  If you feel you have a genuine bug, please file it here:

http://tickets.opscode.com/secure/Dashboard.jspa

Thanks!
@mancdaz

**Comment by vskubriev** [comment]
Excusme I push this bug wrong )))

I create this already
http://tickets.opscode.com/browse/COOK-3390#comment-38187
