### ISSUE TITLE
[DE53]: keystone bind_host gets set twice causing keystone to restart twice during a single chef run

### ISSUE THREAD

**Issue by breu** [rcbops/chef-cookbooks#342]
on the second run of a chef client (and maybe the first run as well) the bind_host of keystone gets changed first to the VIP address, and then later on to the local machine IP causing keystone to restart twice in a single chef run

sample chef-client run

Recipe: <Dynamically Defined Resource>
- monit_procmon[keystone] action add[2013-03-25T14:23:25+00:00] INFO: Processing monit_procmon[keystone] action add (/var/chef/cache/cookbooks/monitoring/providers/procmon_monit.rb line 28)
  (up to date)
- template[/etc/monit/conf.d/keystone.conf] action create[2013-03-25T14:23:25+00:00] INFO: Processing template[/etc/monit/conf.d/keystone.conf] action create (/var/chef/cache/cookbooks/monit/providers/procmon.rb line 50)
  (up to date)
  Recipe: keystone::server
- monitoring_metric[keystone-proc] action measure[2013-03-25T14:23:25+00:00] INFO: Processing monitoring_metric[keystone-proc] action measure (keystone::server line 92)
  (up to date)
- directory[/etc/keystone] action create[2013-03-25T14:23:25+00:00] INFO: Processing directory[/etc/keystone] action create (keystone::server line 99)
  (up to date)
- execute[keystone-manage db_sync] action nothing[2013-03-25T14:23:25+00:00] INFO: Processing execute[keystone-manage db_sync] action nothing (keystone::server line 106)
  (up to date)
- template[/etc/keystone/keystone.conf] action create[2013-03-25T14:23:25+00:00] INFO: Processing template[/etc/keystone/keystone.conf] action create (keystone::server line 122)
  [2013-03-25T14:23:25+00:00] INFO: template[/etc/keystone/keystone.conf] backed up to /var/chef/backup/etc/keystone/keystone.conf.chef-20130325142325
  [2013-03-25T14:23:25+00:00] INFO: template[/etc/keystone/keystone.conf] removed backup at /var/chef/backup/./etc/keystone/keystone.conf.chef-20130325132230
  [2013-03-25T14:23:25+00:00] INFO: template[/etc/keystone/keystone.conf] updated content
  [2013-03-25T14:23:25+00:00] INFO: template[/etc/keystone/keystone.conf] owner changed to 109
  [2013-03-25T14:23:25+00:00] INFO: template[/etc/keystone/keystone.conf] group changed to 116
  [2013-03-25T14:23:25+00:00] INFO: template[/etc/keystone/keystone.conf] mode changed to 600
  - update template[/etc/keystone/keystone.conf] from 7df7d3 to dd5f77
    --- /etc/keystone/keystone.conf 2013-03-25 14:01:16.000000000 +0000
    +++ /tmp/chef-rendered-template20130325-11350-n6ad88    2013-03-25 14:23:25.000000000 +0000
    @@ -4,7 +4,7 @@
     public_port = 5000
     admin_port = 35357
     admin_token = aUrfqs23SSD7GnSvxbUI
    -bind_host = 192.168.0.21
    +bind_host = 192.168.0.251
     compute_port = 8774
     verbose = True
     debug = False

[2013-03-25T14:23:25+00:00] INFO: template[/etc/keystone/keystone.conf] sending run action to execute[keystone-manage db_sync](immediate)
- execute[keystone-manage db_sync] action run[2013-03-25T14:23:25+00:00] INFO: Processing execute[keystone-manage db_sync] action run (keystone::server line 106)
  [2013-03-25T14:23:27+00:00] INFO: execute[keystone-manage db_sync] ran successfully
  - execute keystone-manage db_sync

[2013-03-25T14:23:27+00:00] INFO: template[/etc/keystone/keystone.conf] sending restart action to service[keystone](immediate)
- service[keystone] action restart[2013-03-25T14:23:27+00:00] INFO: Processing service[keystone] action restart (keystone::server line 78)
  [2013-03-25T14:23:27+00:00] INFO: service[keystone] restarted
  - restart service service[keystone]

[2013-03-25T14:23:27+00:00] INFO: service[keystone] sending run action to execute[Keystone: sleep](immediate)
- execute[Keystone: sleep] action run[2013-03-25T14:23:27+00:00] INFO: Processing execute[Keystone: sleep] action run (keystone::server line 73)
  [2013-03-25T14:23:37+00:00] INFO: execute[Keystone: sleep] ran successfully
  - execute sleep 10s

[2013-03-25T14:23:37+00:00] INFO: template[/etc/keystone/keystone.conf] sending restart action to service[keystone](immediate)
Recipe: keystone::keystone-api
- service[keystone] action restart[2013-03-25T14:23:37+00:00] INFO: Processing service[keystone] action restart (keystone::keystone-api line 47)
  [2013-03-25T14:23:37+00:00] INFO: service[keystone] restarted
  - restart service service[keystone]

[2013-03-25T14:23:37+00:00] INFO: service[keystone] sending run action to execute[Keystone: sleep](immediate)
Recipe: keystone::server
- execute[Keystone: sleep] action run[2013-03-25T14:23:37+00:00] INFO: Processing execute[Keystone: sleep] action run (keystone::server line 73)
  [2013-03-25T14:23:48+00:00] INFO: execute[Keystone: sleep] ran successfully
  - execute sleep 10s
- file[/var/lib/keystone/keystone.db] action delete[2013-03-25T14:23:48+00:00] INFO: Processing file[/var/lib/keystone/keystone.db] action delete (keystone::server line 149)
  (up to date)
- template[/etc/keystone/logging.conf] action create[2013-03-25T14:23:48+00:00] INFO: Processing template[/etc/keystone/logging.conf] action create (keystone::server line 153)
  (up to date)
- keystone_tenant[Create 'admin' Tenant] action create[2013-03-25T14:23:48+00:00] INFO: Processing keystone_tenant[Create 'admin' Tenant] action create (keystone::server line 170)
  [2013-03-25T14:23:48+00:00] INFO: Tenant 'admin' already exists.. Not creating.
  [2013-03-25T14:23:48+00:00] INFO: Tenant UUID: 04ad59211c8249f5be2a3edb38b0729e
  (up to date)
- keystone_tenant[Create 'service' Tenant] action create[2013-03-25T14:23:48+00:00] INFO: Processing keystone_tenant[Create 'service' Tenant] action create (keystone::server line 170)
  [2013-03-25T14:23:48+00:00] INFO: Tenant 'service' already exists.. Not creating.
  [2013-03-25T14:23:48+00:00] INFO: Tenant UUID: bafc597f36ac48cd974b5c54cb7841f7
  (up to date)
- keystone_role[Create 'admin' Role] action create[2013-03-25T14:23:48+00:00] INFO: Processing keystone_role[Create 'admin' Role] action create (keystone::server line 185)
  [2013-03-25T14:23:48+00:00] INFO: Role 'admin' already exists.. Not creating.
  [2013-03-25T14:23:48+00:00] INFO: Role UUID: eb22515a50344cba8e2802bc434489d6
  (up to date)
- keystone_role[Create 'Member' Role] action create[2013-03-25T14:23:48+00:00] INFO: Processing keystone_role[Create 'Member' Role] action create (keystone::server line 185)
  [2013-03-25T14:23:48+00:00] INFO: Role 'Member' already exists.. Not creating.
  [2013-03-25T14:23:48+00:00] INFO: Role UUID: 55cdac912c1c4ca4a380f11f5f293d00
  (up to date)
- keystone_role[Create 'KeystoneAdmin' Role] action create[2013-03-25T14:23:48+00:00] INFO: Processing keystone_role[Create 'KeystoneAdmin' Role] action create (keystone::server line 185)
  [2013-03-25T14:23:48+00:00] INFO: Role 'KeystoneAdmin' already exists.. Not creating.
  [2013-03-25T14:23:48+00:00] INFO: Role UUID: 322c489a977f4772a522c2d04f68fd72
  (up to date)
- keystone_role[Create 'KeystoneServiceAdmin' Role] action create[2013-03-25T14:23:48+00:00] INFO: Processing keystone_role[Create 'KeystoneServiceAdmin' Role] action create (keystone::server line 185)
  [2013-03-25T14:23:48+00:00] INFO: Role 'KeystoneServiceAdmin' already exists.. Not creating.
  [2013-03-25T14:23:48+00:00] INFO: Role UUID: e1f239c88c5d4458b9e6f33764d15dc8
  (up to date)
- keystone_user[Create 'admin' User] action create[2013-03-25T14:23:48+00:00] INFO: Processing keystone_user[Create 'admin' User] action create (keystone::server line 197)
  [2013-03-25T14:23:48+00:00] INFO: User 'admin' already exists for Tenant 'admin'.. Not creating.
  [2013-03-25T14:23:48+00:00] INFO: User UUID: 23c7755cd2b04cdbad199a1429a9a7e9
  (up to date)
- keystone_role[Grant 'admin' Role to 'admin' User in 'admin' Tenant] action grant[2013-03-25T14:23:48+00:00] INFO: Processing keystone_role[Grant 'admin' Role to 'admin' User in 'admin' Tenant] action grant (keystone::server line 212)
  [2013-03-25T14:23:48+00:00] INFO: Role 'admin' already exists.. Not granting.
  (up to date)
- keystone_role[Grant 'KeystoneAdmin' Role to 'admin' User in 'admin' Tenant] action grant[2013-03-25T14:23:48+00:00] INFO: Processing keystone_role[Grant 'KeystoneAdmin' Role to 'admin' User in 'admin' Tenant] action grant (keystone::server line 212)
  [2013-03-25T14:23:48+00:00] INFO: Role 'KeystoneAdmin' already exists.. Not granting.
  (up to date)
- keystone_role[Grant 'KeystoneServiceAdmin' Role to 'admin' User in 'admin' Tenant] action grant[2013-03-25T14:23:48+00:00] INFO: Processing keystone_role[Grant 'KeystoneServiceAdmin' Role to 'admin' User in 'admin' Tenant] action grant (keystone::server line 212)
  [2013-03-25T14:23:48+00:00] INFO: Role 'KeystoneServiceAdmin' already exists.. Not granting.
  (up to date)
- keystone_user[Create 'monitoring' User] action create[2013-03-25T14:23:48+00:00] INFO: Processing keystone_user[Create 'monitoring' User] action create (keystone::server line 197)
  [2013-03-25T14:23:49+00:00] INFO: User 'monitoring' already exists for Tenant 'service'.. Not creating.
  [2013-03-25T14:23:49+00:00] INFO: User UUID: 990ff8c50e6840698949a229481f8e4c
  (up to date)
- keystone_role[Grant 'Member' Role to 'monitoring' User in 'admin' Tenant] action grant[2013-03-25T14:23:49+00:00] INFO: Processing keystone_role[Grant 'Member' Role to 'monitoring' User in 'admin' Tenant] action grant (keystone::server line 212)
  [2013-03-25T14:23:49+00:00] INFO: Role 'Member' already exists.. Not granting.
  (up to date)
- keystone_service[Create Identity Service] action create[2013-03-25T14:23:49+00:00] INFO: Processing keystone_service[Create Identity Service] action create (keystone::server line 230)
  [2013-03-25T14:23:49+00:00] INFO: Service Type 'identity' already exists.. Not creating.
  [2013-03-25T14:23:49+00:00] INFO: Service UUID: 727e54258a49457592890df918333658
  (up to date)
- keystone_endpoint[Create Identity Endpoint] action create[2013-03-25T14:23:49+00:00] INFO: Processing keystone_endpoint[Create Identity Endpoint] action create (keystone::server line 252)
  [2013-03-25T14:23:49+00:00] INFO: Endpoint already exists for Service Type 'identity' already exists.. Not creating.
  [2013-03-25T14:23:49+00:00] INFO: Endpoint UUID: 743a30f61f7247f7a08e0dd428a80fa4
  (up to date)
- keystone_credentials[Create EC2 credentials for 'admin' user] action create_ec2[2013-03-25T14:23:49+00:00] INFO: Processing keystone_credentials[Create EC2 credentials for 'admin' user] action create_ec2 (keystone::server line 268)
  [2013-03-25T14:23:49+00:00] INFO: Credentials already exist for User 'admin' in Tenant 'admin'.. Not creating.
  (up to date)
- keystone_credentials[Create EC2 credentials for 'monitoring' user] action create_ec2[2013-03-25T14:23:49+00:00] INFO: Processing keystone_credentials[Create EC2 credentials for 'monitoring' user] action create_ec2 (keystone::server line 268)
  [2013-03-25T14:23:49+00:00] INFO: Credentials already exist for User 'monitoring' in Tenant 'service'.. Not creating.
  (up to date)
- monitoring_metric[keystone] action measure[2013-03-25T14:23:49+00:00] INFO: Processing monitoring_metric[keystone] action measure (keystone::server line 280)
  (up to date)
  Recipe: keystone::keystoneclient-patch
- template[/usr/share/pyshared/keystoneclient/v2_0/client.py] action create[2013-03-25T14:23:49+00:00] INFO: Processing template[/usr/share/pyshared/keystoneclient/v2_0/client.py] action create (keystone::keystoneclient-patch line 25)
  (skipped due to only_if)
  Recipe: keystone::keystone-api
- package[keystone] action install[2013-03-25T14:23:49+00:00] INFO: Processing package[keystone] action install (keystone::keystone-api line 34)
  (up to date)
- package[python-keystone] action install[2013-03-25T14:23:50+00:00] INFO: Processing package[python-keystone] action install (keystone::keystone-api line 34)
  (up to date)
- package[python-keystoneclient] action install[2013-03-25T14:23:50+00:00] INFO: Processing package[python-keystoneclient] action install (keystone::keystone-api line 34)
  (up to date)
- package[python-ldap] action install[2013-03-25T14:23:50+00:00] INFO: Processing package[python-ldap] action install (keystone::keystone-api line 41)
  (up to date)
- service[keystone] action enable[2013-03-25T14:23:50+00:00] INFO: Processing service[keystone] action enable (keystone::keystone-api line 47)
  (up to date)
- monitoring_procmon[keystone] action monitor[2013-03-25T14:23:50+00:00] INFO: Processing monitoring_procmon[keystone] action monitor (keystone::keystone-api line 53)
  [2013-03-25T14:23:50+00:00] WARN: Cloning resource attributes for monit_procmon[keystone] from prior resource (CHEF-3694)
  [2013-03-25T14:23:50+00:00] WARN: Previous monit_procmon[keystone]: /var/chef/cache/cookbooks/monitoring/providers/procmon_monit.rb:28:in `block in class_from_file'
  [2013-03-25T14:23:50+00:00] WARN: Current  monit_procmon[keystone]: /var/chef/cache/cookbooks/monitoring/providers/procmon_monit.rb:28:in`block in class_from_file'

Recipe: <Dynamically Defined Resource>
- monit_procmon[keystone] action add[2013-03-25T14:23:50+00:00] INFO: Processing monit_procmon[keystone] action add (/var/chef/cache/cookbooks/monitoring/providers/procmon_monit.rb line 28)
  [2013-03-25T14:23:50+00:00] WARN: Cloning resource attributes for template[/etc/monit/conf.d/keystone.conf] from prior resource (CHEF-3694)
  [2013-03-25T14:23:50+00:00] WARN: Previous template[/etc/monit/conf.d/keystone.conf]: /var/chef/cache/cookbooks/monit/providers/procmon.rb:50:in `block in class_from_file'
  [2013-03-25T14:23:50+00:00] WARN: Current  template[/etc/monit/conf.d/keystone.conf]: /var/chef/cache/cookbooks/monit/providers/procmon.rb:50:in`block in class_from_file'
  (up to date)
- template[/etc/monit/conf.d/keystone.conf] action create[2013-03-25T14:23:50+00:00] INFO: Processing template[/etc/monit/conf.d/keystone.conf] action create (/var/chef/cache/cookbooks/monit/providers/procmon.rb line 50)
  (up to date)
  Recipe: keystone::keystone-api
- monitoring_metric[keystone-proc] action measure[2013-03-25T14:23:50+00:00] INFO: Processing monitoring_metric[keystone-proc] action measure (keystone::keystone-api line 60)
  (up to date)
- directory[/etc/keystone] action create[2013-03-25T14:23:50+00:00] INFO: Processing directory[/etc/keystone] action create (keystone::keystone-api line 67)
  (up to date)
- template[/etc/keystone/keystone.conf] action create[2013-03-25T14:23:50+00:00] INFO: Processing template[/etc/keystone/keystone.conf] action create (keystone::keystone-api line 80)
  [2013-03-25T14:23:51+00:00] INFO: template[/etc/keystone/keystone.conf] backed up to /var/chef/backup/etc/keystone/keystone.conf.chef-20130325142351
  [2013-03-25T14:23:51+00:00] INFO: template[/etc/keystone/keystone.conf] removed backup at /var/chef/backup/./etc/keystone/keystone.conf.chef-20130325135313
  [2013-03-25T14:23:51+00:00] INFO: template[/etc/keystone/keystone.conf] updated content
  [2013-03-25T14:23:51+00:00] INFO: template[/etc/keystone/keystone.conf] owner changed to 109
  [2013-03-25T14:23:51+00:00] INFO: template[/etc/keystone/keystone.conf] group changed to 116
  [2013-03-25T14:23:51+00:00] INFO: template[/etc/keystone/keystone.conf] mode changed to 600
  - update template[/etc/keystone/keystone.conf] from dd5f77 to 7df7d3
    --- /etc/keystone/keystone.conf 2013-03-25 14:23:25.000000000 +0000
    +++ /tmp/chef-rendered-template20130325-11350-jx1ntl    2013-03-25 14:23:50.000000000 +0000
    @@ -4,7 +4,7 @@
     public_port = 5000
     admin_port = 35357
     admin_token = aUrfqs23SSD7GnSvxbUI
    -bind_host = 192.168.0.251
    +bind_host = 192.168.0.21
     compute_port = 8774
     verbose = True
     debug = False

[2013-03-25T14:23:51+00:00] INFO: template[/etc/keystone/keystone.conf] sending run action to execute[keystone-manage db_sync](immediate)
Recipe: keystone::server
- execute[keystone-manage db_sync] action run[2013-03-25T14:23:51+00:00] INFO: Processing execute[keystone-manage db_sync] action run (keystone::server line 106)
  [2013-03-25T14:23:53+00:00] INFO: execute[keystone-manage db_sync] ran successfully
  - execute keystone-manage db_sync

[2013-03-25T14:23:53+00:00] INFO: template[/etc/keystone/keystone.conf] sending restart action to service[keystone](immediate)
- service[keystone] action restart[2013-03-25T14:23:53+00:00] INFO: Processing service[keystone] action restart (keystone::server line 78)
  [2013-03-25T14:23:53+00:00] INFO: service[keystone] restarted
  - restart service service[keystone]

[2013-03-25T14:23:53+00:00] INFO: service[keystone] sending run action to execute[Keystone: sleep](immediate)
- execute[Keystone: sleep] action run[2013-03-25T14:23:53+00:00] INFO: Processing execute[Keystone: sleep] action run (keystone::server line 73)
  [2013-03-25T14:24:03+00:00] INFO: execute[Keystone: sleep] ran successfully
  - execute sleep 10s

[2013-03-25T14:24:03+00:00] INFO: template[/etc/keystone/keystone.conf] sending restart action to service[keystone](immediate)
Recipe: keystone::keystone-api
- service[keystone] action restart[2013-03-25T14:24:03+00:00] INFO: Processing service[keystone] action restart (keystone::keystone-api line 47)
  [2013-03-25T14:24:03+00:00] INFO: service[keystone] restarted
  - restart service service[keystone]

[2013-03-25T14:24:03+00:00] INFO: service[keystone] sending run action to execute[Keystone: sleep](immediate)
Recipe: keystone::server
- execute[Keystone: sleep] action run[2013-03-25T14:24:03+00:00] INFO: Processing execute[Keystone: sleep] action run (keystone::server line 73)
  [2013-03-25T14:24:14+00:00] INFO: execute[Keystone: sleep] ran successfully
  - execute sleep 10s

**Comment by mancdaz** [comment]
closing as issue is resolved
