### ISSUE TITLE
[DE141]: Instance spawning fails because of missing ephemerals files

### ISSUE THREAD

**Issue by StephenKing** [rcbops/chef-cookbooks#407]
I've set up the allinone version but cannot spin up new instances (using Ubuntu 12.10 and Folsom).

It fails with

```
ERROR Instance failed to spawn
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 756, in _spawn
    block_device_info)
  File "/usr/lib/python2.7/dist-packages/nova/exception.py", line 117, in wrapped
    temp_level, payload)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/lib/python2.7/dist-packages/nova/exception.py", line 92, in wrapped
    return f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 1091, in spawn
    admin_pass=admin_password)
  File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 1373, in _create_image
    ephemeral_size=ephemeral_gb)
  File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/imagebackend.py", line 131, in cache
    *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/imagebackend.py", line 181, in create_image
    if size and size < disk.get_disk_size(base):
  File "/usr/lib/python2.7/dist-packages/nova/virt/disk/api.py", line 115, in get_disk_size
    size = images.qemu_img_info(path)['virtual size']
  File "/usr/lib/python2.7/dist-packages/nova/virt/images.py", line 50, in qemu_img_info
    'qemu-img', 'info', path)
  File "/usr/lib/python2.7/dist-packages/nova/utils.py", line 210, in execute
    cmd=' '.join(cmd))
ProcessExecutionError: Unexpected error while running command.
Command: env LC_ALL=C LANG=C qemu-img info /var/lib/nova/instances/_base/ephemeral_0_10_None
Exit code: 1
Stdout: ''
Stderr: "qemu-img: Could not open '/var/lib/nova/instances/_base/ephemeral_0_10_None': No such file or directory\n"
```

See here in the debug log:
https://gist.github.com/StephenKing/1f7bf135f2af7f260877#file-nova-log-L965

A way to "fix" this bug is copying the file with a hash as filename (size 1.4GB) to that name and then I'm able to spin up new instances (with the disk size of XX in ephemeral_0_XX_None).

It seems to happen around here:

``` python
def _create_image()
  ..
  if ephemeral_gb and not self._volume_in_mapping(
      self.default_second_device, block_device_info):
    ..
    image('disk.local').cache(fetch_func=fn,
        filename=fname,
        size=size,
        ephemeral_size=ephemeral_gb)
```

in `nova/virt/libvirt/driver.py`.

Any idea, how to fix this?

**Comment by mattt416** [comment]
Hi @StephenKing,

It almost sounds like you're running into issue https://bugs.launchpad.net/openstack/nova/+bug/1182624.

Can you please let us know what version of the OpenStack nova packages you have installed on your node?

As an aside, please note that our cookbooks are only tested on CentOS 6.3 and Ubuntu 12.04 at this point in time.

Kind Regards,
Matt

**Comment by StephenKing** [comment]
Yeah, that's it.. didn't find that during my search before!
