### ISSUE TITLE
[nova-network]: we need a quantum-common recipe to manage all config file creation

### ISSUE THREAD

**Issue by mancdaz** [rcbops/chef-cookbooks#435]
The quantum-[dhcp|l3]-agents recipe does not drop in the quantum.conf file, only it's own *-agent.ini
It assumes that the quantum-server recipe has dropped in quantum.conf, and therefore can not run standalone on it's own box.  You would see something like this:

<pre>Traceback (most recent call last):
  File "/usr/bin/quantum-dhcp-agent", line 20, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/quantum/agent/dhcp_agent.py", line 730, in main
    cfg.CONF(project='quantum')
  File "/usr/lib/python2.7/dist-packages/oslo/config/cfg.py", line 1180, in __call__
    self._parse_config_files()
  File "/usr/lib/python2.7/dist-packages/oslo/config/cfg.py", line 1655, in _parse_config_files
    raise ConfigFilesNotFoundError(not_read_ok)
oslo.config.cfg.ConfigFilesNotFoundError: Failed to read some config files: /etc/quantum/quantum.conf</pre>

**Comment by mancdaz** [comment]
fixed in https://github.com/rcbops-cookbooks/nova-network/pull/29
