### ISSUE TITLE
Keystone-manage db_sync failing due to TypeError, string indices must be integers, not str

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#452]
http://build.monkeypuppetlabs.com:8080/view/QE%20Jobs/job/autotest-centos-folsom-ha/16/console

[2013-06-17T09:23:28-06:00] INFO: Processing file[/var/lib/keystone/keystone.db] action delete (keystone::keystone-common line 114)
[2013-06-17T09:23:28-06:00] INFO: Processing execute[keystone-manage db_sync] action run (keystone::setup line 61)
[0m
================================================================================[0m
[31mError executing action `run` on resource 'execute[keystone-manage db_sync]'[0m
================================================================================[0m

[0m
Mixlib::ShellOut::ShellCommandFailed[0m
------------------------------------[0m
Expected process to exit with [0], but received '1'
---- Begin output of keystone-manage db_sync ----
STDOUT: 
STDERR: Traceback (most recent call last):
  File "/usr/bin/keystone-manage", line 28, in <module>
    cli.main(argv=sys.argv, config_files=config_files)
  File "/usr/lib/python2.6/site-packages/keystone/cli.py", line 175, in main
    CONF.command.cmd_class.main()
  File "/usr/lib/python2.6/site-packages/keystone/cli.py", line 54, in main
    driver.db_sync()
  File "/usr/lib/python2.6/site-packages/keystone/identity/backends/sql.py", line 156, in db_sync
    migration.db_sync()
  File "/usr/lib/python2.6/site-packages/keystone/common/sql/migration.py", line 52, in db_sync
    return versioning_api.upgrade(CONF.sql.connection, repo_path, version)
  File "/usr/lib/python2.6/site-packages/migrate/versioning/api.py", line 185, in upgrade
    return _migrate(url, repository, version, upgrade=True, err=err, **opts)
  File "<string>", line 2, in _migrate
  File "/usr/lib/python2.6/site-packages/migrate/versioning/util/__init__.py", line 160, in with_engine
    return f(_a, *_kw)
  File "/usr/lib/python2.6/site-packages/migrate/versioning/api.py", line 364, in _migrate
    schema.runchange(ver, change, changeset.step)
  File "/usr/lib/python2.6/site-packages/migrate/versioning/schema.py", line 90, in runchange
    change.run(self.engine, step)
  File "/usr/lib/python2.6/site-packages/migrate/versioning/script/py.py", line 145, in run
    script_func(engine)
  File "/usr/lib/python2.6/site-packages/keystone/common/sql/migrate_repo/versions/020_migrate_metadata_table_roles.py", line 41, in upgrade
    old_roles = data['roles']
TypeError: string indices must be integers, not str
---- End output of keystone-manage db_sync ----
Ran keystone-manage db_sync returned 1[0m

[0m
Resource Declaration:[0m
---------------------[0m
In /var/chef/cache/cookbooks/keystone/recipes/setup.rb

 61: execute "keystone-manage db_sync" do
 62:   user "keystone"
 63:   group "keystone"
 64:   command "keystone-manage db_sync"
 65:   action :run
 66: end
 67: 
[0m

[0m
Compiled Resource:[0m
------------------[0m
Declared in /var/chef/cache/cookbooks/keystone/recipes/setup.rb:61:in `from_file'

execute("keystone-manage db_sync") do
  action [:run]
  retries 0
  retry_delay 2
  command "keystone-manage db_sync"
  backup 5
  group "keystone"
  returns 0
  user "keystone"
  cookbook_name "keystone"
  recipe_name "setup"
end
[0m

[0m
[2013-06-17T09:23:29-06:00] INFO: Running queued delayed notifications before re-raising exception
[2013-06-17T09:23:29-06:00] INFO: template[/etc/rsyslog.conf] sending restart action to service[rsyslog](delayed)

**Comment by breu** [comment]
@jacobwagner  Do you have copies of the keystone.conf and paste conf files?
