### ISSUE TITLE
[DE222] centos/folsom fails due to version of python-keystoneclient

### ISSUE THREAD

**Issue by mancdaz** [rcbops/chef-cookbooks#487]
folsom on centos is failing when uploading images to glance.  This is because the glanceclient from folsom relies on a version of python-keystoneclient that is < 0.2.  Unfortunately, since the client packages are not tied to openstack releases, the latest python-keystoneclient (0.2.0-2el6) is being pulled in.  Hence failure...

  not_if "glance -I admin -K secrete -T admin -N http://192.168.3.2:35357/v2.0 -f index | grep cirros-image"
end
-- INSERT --                                                                                                                                                                                   59,4          Bot
    Recipe: <Dynamically Defined Resource>
      \* bash[Uploading QCOW2 image cirros] action run[2013-07-23T12:01:05+00:00] INFO: Processing bash[Uploading QCOW2 image cirros] action run (/var/chef/cache/cookbooks/glance/providers/image.rb line 64)

```
================================================================================
Error executing action `run` on resource 'bash[Uploading QCOW2 image cirros]'
================================================================================


Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of "bash"  "/tmp/chef-script20130723-10651-299j4v" ----
STDOUT:
STDERR: Traceback (most recent call last):
  File "/usr/bin/glance", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2659, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: python-keystoneclient>=0.1.2,<0.2
---- End output of "bash"  "/tmp/chef-script20130723-10651-299j4v" ----
Ran "bash"  "/tmp/chef-script20130723-10651-299j4v" returned 1


Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/glance/providers/image.rb

 64:   bash "Uploading QCOW2 image #{name}" do
 65:     cwd "/tmp"
 66:     user "root"
 67:     code <<-EOH
 68:         #{glance_cmd} add name="#{new_name}" is_public=true #{c_fmt} #{d_fmt} location="#{url}"
 69:     EOH
 70:     not_if "#{glance_cmd} -f index | grep #{new_name.to_s}"
 71:   end
 72: end



Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/glance/providers/image.rb:64:in `_upload_qcow'

bash("Uploading QCOW2 image cirros") do
  action "run"
  retries 0
  retry_delay 2
  command "\"bash\"  \"/tmp/chef-script20130723-10651-299j4v\""
  backup 5
  cwd "/tmp"
  returns 0
  user "root"
  code "        glance -I admin -K secrete -T admin -N http://192.168.3.2:35357/v2.0 add name=\"cirros-image\" is_public=true container_format=bare disk_format=qcow2 location=\"https://launchpadlibrarian.net/83305348/cirros-0.3.0-x86_64-disk.img\"\n"
  interpreter "bash"
  cookbook_name "glance"
  not_if "glance -I admin -K secrete -T admin -N http://192.168.3.2:35357/v2.0 -f index | grep cirros-image"
end
```

**Comment by mancdaz** [comment]
Actually it seems this may be an issue with the python-glanceclient dependencies.  It has a hard requirement for python-keystoneclient>=0.1.2,<0.2. 

```
/usr/lib/python2.6/site-packages/python_glanceclient-0.5.1-py2.6.egg-info/requires.txt

prettytable>=0.6,<0.7
python-keystoneclient>=0.1.2, <0.2
warlock<2
```

As per [this bug comment](https://bugs.launchpad.net/openstack-manuals/+bug/1064449/comments/5), this needs to be changed to

```
python-keystoneclient>=0.1.2
```

Manually changing this and running the image upload does indeed fix the issue.

**Comment by mancdaz** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=987475

**Comment by mancdaz** [comment]
fixed in https://github.com/rcbops-cookbooks/glance/pull/161
