### ISSUE TITLE
[osops-utils] Specs and Chef::Recipe::IPManagement.get_ips_for_role broken

### ISSUE THREAD

**Issue by claco** [rcbops/chef-cookbooks#506]
This commit:  https://github.com/rcbops-cookbooks/osops-utils/commit/c420a1be1a521f0770c30d1f72624be104aa4a71

Broke get_ips_for_role (the class method) and a metric tonne of specs.

Also, run the specs and coverage I so loving crafted please, lest I have to rpedde-level rage.
## 

Failures:

  1) RCB#get_bind_endpoint returns the host and uri for the endpoint
     Failure/Error: }
       expected: {"host"=>"172.16.10.1", "network"=>"management", "path"=>"/endpoint", "port"=>80, "scheme"=>"http", "uri"=>"http://172.16.10.1:80/endpoint"}
            got: {"network"=>"management", "path"=>"/endpoint", "scheme"=>"http", "port"=>80, "host"=>"localhost", "uri"=>"http://localhost:80/endpoint"} (using ==)
       Diff:

```
   @@ -1,7 +1,7 @@
   -"host" => "172.16.10.1",
   +"host" => "localhost",
    "network" => "management",
    "path" => "/endpoint",
    "port" => 80,
    "scheme" => "http",
   -"uri" => "http://172.16.10.1:80/endpoint"
   +"uri" => "http://localhost:80/endpoint"
 # ./spec/ip_location_spec.rb:297:in `block (3 levels) in <top (required)>'
```

  2) RCB#get_lb_endpoint with vips and service information uses the node if the name matches the search result for vips
     Failure/Error: library.get_lb_endpoint("myrole", "myserver", "myservice").should == {
     NoMethodError:
       undefined method `include?' for nil:NilClass
     # ./libraries/ip_location.rb:304:in`block in osops_search'
     # ./libraries/ip_location.rb:303:in `each'
     # ./libraries/ip_location.rb:303:in`osops_search'
     # ./libraries/ip_location.rb:212:in `get_realserver_endpoints'
     # ./libraries/ip_location.rb:359:in`get_lb_endpoint'
     # ./spec/ip_location_spec.rb:341:in `block (4 levels) in <top (required)>'

  3) RCB#get_lb_endpoint with vips and service information uses node if the name matches the search result for external vips
     Failure/Error: library.get_lb_endpoint("myrole", "myserver", "myservice").should == {
     NoMethodError:
       undefined method `include?' for nil:NilClass
     # ./libraries/ip_location.rb:304:in`block in osops_search'
     # ./libraries/ip_location.rb:303:in `each'
     # ./libraries/ip_location.rb:303:in`osops_search'
     # ./libraries/ip_location.rb:212:in `get_realserver_endpoints'
     # ./libraries/ip_location.rb:359:in`get_lb_endpoint'
     # ./spec/ip_location_spec.rb:354:in `block (4 levels) in <top (required)>'

  4) RCB#get_access_endpoint returns nil for no matching role, service, service
     Failure/Error: library.get_access_endpoint("unknown", "unknown", "unknown").should be_nil
     NoMethodError:
       undefined method `include?' for nil:NilClass
     # ./libraries/ip_location.rb:304:in`block in osops_search'
     # ./libraries/ip_location.rb:303:in `each'
     # ./libraries/ip_location.rb:303:in`osops_search'
     # ./libraries/ip_location.rb:186:in `get_access_endpoint'
     # ./spec/ip_location_spec.rb:393:in`block (3 levels) in <top (required)>'

  5) RCB#get_access_endpoint with service information uses the node if the name matches the search result
     Failure/Error: library.get_access_endpoint("myrole", "myserver", "myservice").
     NoMethodError:
       undefined method `include?' for nil:NilClass
     # ./libraries/ip_location.rb:304:in`block in osops_search'
     # ./libraries/ip_location.rb:303:in `each'
     # ./libraries/ip_location.rb:303:in`osops_search'
     # ./libraries/ip_location.rb:186:in `get_access_endpoint'
     # ./spec/ip_location_spec.rb:418:in`block (4 levels) in <top (required)>'

  6) RCB#get_access_endpoint with service information uses the node if the role contains the search result
     Failure/Error: library.get_access_endpoint("myrole", "myserver", "myservice").
     NoMethodError:
       undefined method `include?' for nil:NilClass
     # ./libraries/ip_location.rb:304:in`block in osops_search'
     # ./libraries/ip_location.rb:303:in `each'
     # ./libraries/ip_location.rb:303:in`osops_search'
     # ./libraries/ip_location.rb:186:in `get_access_endpoint'
     # ./spec/ip_location_spec.rb:432:in`block (4 levels) in <top (required)>'

  7) RCB#get_access_endpoint with service information find the lb vips for more thanone result
     Failure/Error: library.get_access_endpoint("myrole", "myserver", "myservice").
     NoMethodError:
       undefined method `include?' for nil:NilClass
     # ./libraries/ip_location.rb:304:in`block in osops_search'
     # ./libraries/ip_location.rb:303:in `each'
     # ./libraries/ip_location.rb:303:in`osops_search'
     # ./libraries/ip_location.rb:186:in `get_access_endpoint'
     # ./spec/ip_location_spec.rb:447:in`block (4 levels) in <top (required)>'

  8) RCB#get_realserver_endpoints returns empty array for no matching role, service, service
     Failure/Error: library.get_realserver_endpoints("unknown", "unknown", "unknown").
     NoMethodError:
       undefined method `include?' for nil:NilClass
     # ./libraries/ip_location.rb:304:in`block in osops_search'
     # ./libraries/ip_location.rb:303:in `each'
     # ./libraries/ip_location.rb:303:in`osops_search'
     # ./libraries/ip_location.rb:212:in `get_realserver_endpoints'
     # ./spec/ip_location_spec.rb:474:in`block (3 levels) in <top (required)>'

  9) RCB#get_realserver_endpoints with service information uses the node if the name matches the search result
     Failure/Error: library.get_realserver_endpoints("myrole", "myserver", "myservice").
     NoMethodError:
       undefined method `include?' for nil:NilClass
     # ./libraries/ip_location.rb:304:in`block in osops_search'
     # ./libraries/ip_location.rb:303:in `each'
     # ./libraries/ip_location.rb:303:in`osops_search'
     # ./libraries/ip_location.rb:212:in `get_realserver_endpoints'
     # ./spec/ip_location_spec.rb:500:in`block (4 levels) in <top (required)>'

  10) RCB#get_realserver_endpoints with service information uses the node if the role contains the search result
     Failure/Error: library.get_realserver_endpoints("myrole", "myserver", "myservice").
     NoMethodError:
       undefined method `include?' for nil:NilClass
     # ./libraries/ip_location.rb:304:in`block in osops_search'
     # ./libraries/ip_location.rb:303:in `each'
     # ./libraries/ip_location.rb:303:in`osops_search'
     # ./libraries/ip_location.rb:212:in `get_realserver_endpoints'
     # ./spec/ip_location_spec.rb:514:in`block (4 levels) in <top (required)>'

  11) Chef::Recipe::IPManagement.get_ip_for_net logs and raises an error for no networks
     Failure/Error: Chef::Log.should_receive("error").with(/can't find network/i)
       (<Chef::Log (class)>).error(/can't find network/i)
           expected: 1 time
           received: 0 times
     # ./spec/ip_location_spec.rb:655:in `block (3 levels) in <top (required)>'

  12) Chef::Recipe::IPManagement.get_ip_for_net logs and raises an error for a missing network
     Failure/Error: Chef::Log.should_receive("error").with(/can't find network/i)
       (<Chef::Log (class)>).error(/can't find network/i)
           expected: 1 time
           received: 0 times
     # ./spec/ip_location_spec.rb:662:in `block (3 levels) in <top (required)>'

  13) Chef::Recipe::IPManagement.get_ips_for_role returns 0.0.0.0 for all
     Failure/Error: library.get_ips_for_role("myrole", "all", node).should eq ["0.0.0.0"]
     NoMethodError:
       undefined method `osops_search' for Chef::Recipe::IPManagement:Class
     # ./libraries/ip_location.rb:457:in`get_ips_for_role'
     # ./spec/ip_location_spec.rb:726:in `block (3 levels) in <top (required)>'

  14) Chef::Recipe::IPManagement.get_ips_for_role returns 127.0.0.1 for localhost
     Failure/Error: library.get_ips_for_role("myrole", "localhost", node).
     NoMethodError:
       undefined method `osops_search' for Chef::Recipe::IPManagement:Class
     # ./libraries/ip_location.rb:457:in`get_ips_for_role'
     # ./spec/ip_location_spec.rb:730:in `block (3 levels) in <top (required)>'

  15) Chef::Recipe::IPManagement.get_ips_for_role logs and raises an error for no networks
     Failure/Error: expect { library.get_ips_for_role("myrole", "nonet", node) }.
       expected Exception with message matching /can't find network/i, got #<NoMethodError: undefined method `osops_search' for Chef::Recipe::IPManagement:Class> with backtrace:
         # ./libraries/ip_location.rb:457:in `get_ips_for_role'
         # ./spec/ip_location_spec.rb:739:in`block (4 levels) in <top (required)>'
         # ./spec/ip_location_spec.rb:739:in `block (3 levels) in <top (required)>'
     # ./spec/ip_location_spec.rb:739:in`block (3 levels) in <top (required)>'

  16) Chef::Recipe::IPManagement.get_ips_for_role logs and raises an error for a missing network
     Failure/Error: expect { library.get_ips_for_role("myrole", "nonet", node) }.
       expected Exception with message matching /can't find network/i, got #<NoMethodError: undefined method `osops_search' for Chef::Recipe::IPManagement:Class> with backtrace:
         # ./libraries/ip_location.rb:457:in `get_ips_for_role'
         # ./spec/ip_location_spec.rb:746:in`block (4 levels) in <top (required)>'
         # ./spec/ip_location_spec.rb:746:in `block (3 levels) in <top (required)>'
     # ./spec/ip_location_spec.rb:746:in`block (3 levels) in <top (required)>'

  17) Chef::Recipe::IPManagement.get_ips_for_role returns an interface and ip for matching inet4 network
     Failure/Error: library.get_ips_for_role("myrole", "network", node).
     NoMethodError:
       undefined method `osops_search' for Chef::Recipe::IPManagement:Class
     # ./libraries/ip_location.rb:457:in`get_ips_for_role'
     # ./spec/ip_location_spec.rb:753:in `block (3 levels) in <top (required)>'

  18) Chef::Recipe::IPManagement.get_ips_for_role returns an interface and ip for matching inet6 network
     Failure/Error: library.get_ips_for_role("myrole", "network", node).
     NoMethodError:
       undefined method `osops_search' for Chef::Recipe::IPManagement:Class
     # ./libraries/ip_location.rb:457:in`get_ips_for_role'
     # ./spec/ip_location_spec.rb:761:in `block (3 levels) in <top (required)>'

  19) Chef::Recipe::IPManagement.get_ips_for_role uses osops network mappings if available
     Failure/Error: library.get_ips_for_role("myrole", "mynetwork", node).
     NoMethodError:
       undefined method `osops_search' for Chef::Recipe::IPManagement:Class
     # ./libraries/ip_location.rb:457:in`get_ips_for_role'
     # ./spec/ip_location_spec.rb:769:in `block (3 levels) in <top (required)>'

  20) Chef::Recipe::IPManagement.get_ips_for_role raises an exception if no matching network is found
     Failure/Error: expect { library.get_ips_for_role("myrole", "network", node) }.
       expected Exception with message matching /can't find address on network/i, got #<NoMethodError: undefined method `osops_search' for Chef::Recipe::IPManagement:Class> with backtrace:
         # ./libraries/ip_location.rb:457:in `get_ips_for_role'
         # ./spec/ip_location_spec.rb:778:in`block (4 levels) in <top (required)>'
         # ./spec/ip_location_spec.rb:778:in `block (3 levels) in <top (required)>'
     # ./spec/ip_location_spec.rb:778:in`block (3 levels) in <top (required)>'

  21) Chef::Recipe::IPManagement.get_ips_for_role raises an exception if no addresses on interface
     Failure/Error: expect { library.get_ips_for_role("myrole", "network", node) }.
       expected Exception with message matching /can't find address on network/i, got #<NoMethodError: undefined method `osops_search' for Chef::Recipe::IPManagement:Class> with backtrace:
         # ./libraries/ip_location.rb:457:in `get_ips_for_role'
         # ./spec/ip_location_spec.rb:788:in`block (4 levels) in <top (required)>'
         # ./spec/ip_location_spec.rb:788:in `block (3 levels) in <top (required)>'
     # ./spec/ip_location_spec.rb:788:in`block (3 levels) in <top (required)>'

  22) Chef::Recipe::IPManagement.get_ips_for_role raises an exception if no roles match
     Failure/Error: expect { library.get_ips_for_role("unknown", "network", node) }.
       expected Exception with message matching /can't find any candidates for role/i, got #<NoMethodError: undefined method `osops_search' for Chef::Recipe::IPManagement:Class> with backtrace:
         # ./libraries/ip_location.rb:457:in `get_ips_for_role'
         # ./spec/ip_location_spec.rb:796:in`block (4 levels) in <top (required)>'
         # ./spec/ip_location_spec.rb:796:in `block (3 levels) in <top (required)>'
     # ./spec/ip_location_spec.rb:796:in`block (3 levels) in <top (required)>'

  23) Chef::Recipe::IPManagement.get_access_ip_for_role returns 0.0.0.0 for all
     Failure/Error: library.get_access_ip_for_role("myrole", "all", node).
     NoMethodError:
       undefined method `osops_search' for Chef::Recipe::IPManagement:Class
     # ./libraries/ip_location.rb:472:in`get_access_ip_for_role'
     # ./spec/ip_location_spec.rb:826:in `block (3 levels) in <top (required)>'

  24) Chef::Recipe::IPManagement.get_access_ip_for_role returns 127.0.0.1 for localhost
     Failure/Error: library.get_access_ip_for_role("myrole", "localhost", node).
     NoMethodError:
       undefined method `osops_search' for Chef::Recipe::IPManagement:Class
     # ./libraries/ip_location.rb:472:in`get_access_ip_for_role'
     # ./spec/ip_location_spec.rb:831:in `block (3 levels) in <top (required)>'

  25) Chef::Recipe::IPManagement.get_access_ip_for_role logs and raises an error for no networks
     Failure/Error: expect { library.get_access_ip_for_role("myrole", "nonet", node) }.
       expected Exception with message matching /can't find network/i, got #<NoMethodError: undefined method `osops_search' for Chef::Recipe::IPManagement:Class> with backtrace:
         # ./libraries/ip_location.rb:472:in `get_access_ip_for_role'
         # ./spec/ip_location_spec.rb:840:in`block (4 levels) in <top (required)>'
         # ./spec/ip_location_spec.rb:840:in `block (3 levels) in <top (required)>'
     # ./spec/ip_location_spec.rb:840:in`block (3 levels) in <top (required)>'

  26) Chef::Recipe::IPManagement.get_access_ip_for_role logs and raises an error for a missing network
     Failure/Error: expect { library.get_access_ip_for_role("myrole", "nonet", node) }.
       expected Exception with message matching /can't find network/i, got #<NoMethodError: undefined method `osops_search' for Chef::Recipe::IPManagement:Class> with backtrace:
         # ./libraries/ip_location.rb:472:in `get_access_ip_for_role'
         # ./spec/ip_location_spec.rb:847:in`block (4 levels) in <top (required)>'
         # ./spec/ip_location_spec.rb:847:in `block (3 levels) in <top (required)>'
     # ./spec/ip_location_spec.rb:847:in`block (3 levels) in <top (required)>'

  27) Chef::Recipe::IPManagement.get_access_ip_for_role returns an interface and ip for matching inet4 network
     Failure/Error: library.get_access_ip_for_role("myrole", "network", node).
     NoMethodError:
       undefined method `osops_search' for Chef::Recipe::IPManagement:Class
     # ./libraries/ip_location.rb:472:in`get_access_ip_for_role'
     # ./spec/ip_location_spec.rb:854:in `block (3 levels) in <top (required)>'

  28) Chef::Recipe::IPManagement.get_access_ip_for_role returns an interface and ip for matching inet6 network
     Failure/Error: library.get_access_ip_for_role("myrole", "network", node).
     NoMethodError:
       undefined method `osops_search' for Chef::Recipe::IPManagement:Class
     # ./libraries/ip_location.rb:472:in`get_access_ip_for_role'
     # ./spec/ip_location_spec.rb:862:in `block (3 levels) in <top (required)>'

  29) Chef::Recipe::IPManagement.get_access_ip_for_role uses osops network mappings if available
     Failure/Error: library.get_access_ip_for_role("myrole", "mynetwork", node).
     NoMethodError:
       undefined method `osops_search' for Chef::Recipe::IPManagement:Class
     # ./libraries/ip_location.rb:472:in`get_access_ip_for_role'
     # ./spec/ip_location_spec.rb:870:in `block (3 levels) in <top (required)>'

  30) Chef::Recipe::IPManagement.get_access_ip_for_role raises an exception if no matching network is found
     Failure/Error: expect { library.get_access_ip_for_role("myrole", "network", node) }.
       expected Exception with message matching /can't find address on network/i, got #<NoMethodError: undefined method `osops_search' for Chef::Recipe::IPManagement:Class> with backtrace:
         # ./libraries/ip_location.rb:472:in `get_access_ip_for_role'
         # ./spec/ip_location_spec.rb:879:in`block (4 levels) in <top (required)>'
         # ./spec/ip_location_spec.rb:879:in `block (3 levels) in <top (required)>'
     # ./spec/ip_location_spec.rb:879:in`block (3 levels) in <top (required)>'

  31) Chef::Recipe::IPManagement.get_access_ip_for_role raises an exception if no addresses on interface
     Failure/Error: expect { library.get_access_ip_for_role("myrole", "network", node) }.
       expected Exception with message matching /can't find address on network/i, got #<NoMethodError: undefined method `osops_search' for Chef::Recipe::IPManagement:Class> with backtrace:
         # ./libraries/ip_location.rb:472:in `get_access_ip_for_role'
         # ./spec/ip_location_spec.rb:889:in`block (4 levels) in <top (required)>'
         # ./spec/ip_location_spec.rb:889:in `block (3 levels) in <top (required)>'
     # ./spec/ip_location_spec.rb:889:in`block (3 levels) in <top (required)>'

  32) Chef::Recipe::IPManagement.get_access_ip_for_role raises an exception if no roles match
     Failure/Error: expect { library.get_access_ip_for_role("unknown", "network", node) }.
       expected Exception with message matching /can't find any candidates for role/i, got #<NoMethodError: undefined method `osops_search' for Chef::Recipe::IPManagement:Class> with backtrace:
         # ./libraries/ip_location.rb:472:in `get_access_ip_for_role'
         # ./spec/ip_location_spec.rb:897:in`block (4 levels) in <top (required)>'
         # ./spec/ip_location_spec.rb:897:in `block (3 levels) in <top (required)>'
     # ./spec/ip_location_spec.rb:897:in`block (3 levels) in <top (required)>'

  33) Chef::Recipe::IPManagement.get_access_ip_for_role returns an vips ip from osops networks roles if multiple results
     Failure/Error: library.get_access_ip_for_role("myrole", "network", node).
     NoMethodError:
       undefined method `osops_search' for Chef::Recipe::IPManagement:Class
     # ./libraries/ip_location.rb:472:in`get_access_ip_for_role'
     # ./spec/ip_location_spec.rb:913:in `block (3 levels) in <top (required)>'

  34) Chef::Recipe::IPManagement.get_access_ip_for_role raises exception on multiple results with no vips role in osops
     Failure/Error: expect { library.get_access_ip_for_role("unknown", "network", node) }.
       expected Exception with message matching /can't find lb vip/i, got #<NoMethodError: undefined method `osops_search' for Chef::Recipe::IPManagement:Class> with backtrace:
         # ./libraries/ip_location.rb:472:in `get_access_ip_for_role'
         # ./spec/ip_location_spec.rb:923:in`block (4 levels) in <top (required)>'
         # ./spec/ip_location_spec.rb:923:in `block (3 levels) in <top (required)>'
     # ./spec/ip_location_spec.rb:923:in`block (3 levels) in <top (required)>'

Finished in 0.12157 seconds
102 examples, 34 failures

**Comment by claco** [comment]
Fixed in another PR. Also, this issue never made it through Rally triggers. Prolly killed the process.
