### ISSUE TITLE
[DE260]: SolidFire OpenStack drivers not up to date

### ISSUE THREAD

**Issue by alextricity25** [rcbops/chef-cookbooks#532]
The SolidFire drivers deployed with RPC are not up to date to support their new Element 5 OS. Snapshot creation fails and yields the following error in cinder-volume.log: 

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cinder/openstack/common/rpc/amqp.py", line 430, in _process_data
    rval = self.proxy.dispatch(ctxt, version, method, *_args)
  File "/usr/lib/python2.7/dist-packages/cinder/openstack/common/rpc/dispatcher.py", line 133, in dispatch
    return getattr(proxyobj, method)(ctxt, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/cinder/volume/manager.py", line 474, in create_snapshot
    {'status': 'error'})
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/lib/python2.7/dist-packages/cinder/volume/manager.py", line 465, in create_snapshot
    model_update = self.driver.create_snapshot(snapshot_ref)
  File "/usr/lib/python2.7/dist-packages/cinder/volume/drivers/solidfire.py", line 539, in create_snapshot
    snapshot)
  File "/usr/lib/python2.7/dist-packages/cinder/volume/drivers/solidfire.py", line 324, in _do_clone_volume
    type_id = v_ref['volume_type_id']
  File "/usr/lib/python2.7/dist-packages/cinder/db/sqlalchemy/models.py", line 74, in __getitem__
    return getattr(self, key)
AttributeError: 'Snapshot' object has no attribute 'volume_type_id'

Suggested Solution: Pull the latest solidfire.py file from 
https://github.com/openstack/cinder/blob/c4b6f7b99a5ae3f3250106620509ce8e10ad1f1a/cinder/volume/drivers/solidfire.py

**Comment by git-harry** [comment]
@elextro 

We deploy using the latest packages for the distros we support for a defined and stable feature set. As a general rule we do not patch the deployment to add new features from the master branch of an OpenStack project and so I will close this issue.

Thank you for the feedback,
git-harry
