### ISSUE TITLE
[nova-network/sysctl] Compilation Error when enabling Quantum

### ISSUE THREAD

**Issue by themistymay** [rcbops/chef-cookbooks#556]
Single compute installation fails:

``` shell
Starting Chef Client, version 11.6.0
resolving cookbooks for run list: ["osops-utils::packages", "openssh", "ntp", "sosreport", "rsyslog::default", "hardware", "osops-utils::default", "rsyslog::client", "nova-network::nova-compute", "openstack-monitoring::nova-network", "nova::compute", "openstack-monitoring::nova-compute", "openstack-logging::default"]
Synchronizing Cookbooks:
  - rsyslog
  - openstack-logging
  - osops-utils
  - monitoring
  - keystone
  - openstack-monitoring
  - dsh
  - apache2
  - openssl
  - mysql
  - database
  - xfs
  - aws
  - build-essential
  - apt
  - postgresql
  - yum
  - cinder
  - sysctl
  - nova-network
  - nova
  - collectd
  - collectd-plugins
  - monit
  - hardware
  - sosreport
  - ntp
  - iptables
  - openssh
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/nova-network/recipes/nova-compute.rb
================================================================================


NoMethodError
-------------
undefined method `new' for Sysctl:Module


Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/nova-network/recipes/nova-compute.rb:24:in `from_file'


Relevant File Content:
----------------------
/var/chef/cache/cookbooks/nova-network/recipes/nova-compute.rb:

 17:  # limitations under the License.
 18:  #
 19:  
 20:  if node["nova"]["network"]["provider"] == "quantum"
 21:    include_recipe "nova-network::quantum-plugin"
 22:    include_recipe "sysctl::default"
 23:  
 24>>   sysctl 'net.ipv4.ip_forward' do
 25:      value '1'
 26:    end
 27:  else
 28:    include_recipe "nova::api-metadata"
 29:    include_recipe "nova-network::nova-network"
 30:  end
 31:  


[2013-09-03T08:05:42-04:00] ERROR: Running exception handlers
[2013-09-03T08:05:42-04:00] ERROR: Exception handlers complete
[2013-09-03T08:05:42-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated
[2013-09-03T08:05:42-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Trace:

``` shell
Generated at 2013-09-03 08:05:42 -0400
NoMethodError: undefined method `new' for Sysctl:Module
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/dsl/recipe.rb:62:in `method_missing'
/var/chef/cache/cookbooks/nova-network/recipes/nova-compute.rb:24:in `from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/cookbook_version.rb:237:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/run_context.rb:151:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/run_context/cookbook_compiler.rb:139:in `block in compile_recipes'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/run_context/cookbook_compiler.rb:137:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/run_context/cookbook_compiler.rb:137:in `compile_recipes'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/run_context/cookbook_compiler.rb:74:in `compile'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/run_context.rb:86:in `load'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:249:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:492:in `do_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:199:in `block in run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:193:in `fork'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:193:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application.rb:183:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application/client.rb:302:in `block in run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application/client.rb:294:in `loop'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application/client.rb:294:in `run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:23:in `load'
/usr/bin/chef-client:23:in `<main>'

```

I hope I am either looking too hard or missing something small.

**Comment by themistymay** [comment]
I had two version of sysctl... the cookbook was trying to use the wrong one.
