### ISSUE TITLE
[mysql-openstack] Cannot find a resource for keepalived_chkscript

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#568]
Using the master copy of all submodules I end up with the following:

```
[2013-09-16T13:14:20+02:00] INFO: I am currently the only mysql master
[2013-09-16T13:14:20+02:00] DEBUG: Loading Recipe mysql::server via include_recipe
[2013-09-16T13:14:20+02:00] DEBUG: I am not loading mysql::server, because I have already seen it.
[2013-09-16T13:14:20+02:00] DEBUG: rcb_safe_deref(): searching for vips.mysql-db in node[sqlrmq1.lab] with delimiter .
[2013-09-16T13:14:20+02:00] DEBUG: Loading Recipe keepalived via include_recipe
[2013-09-16T13:14:20+02:00] DEBUG: Found recipe default in cookbook keepalived
[2013-09-16T13:14:20+02:00] DEBUG: rcb_safe_deref(): searching for vips_config_192.168.4.113_network in node[sqlrmq1.lab] with delimiter _
[2013-09-16T13:14:20+02:00] DEBUG: rcb_safe_deref(): searching for vips_config_192.168.4.113_vrid in node[sqlrmq1.lab] with delimiter _
[2013-09-16T13:14:20+02:00] DEBUG: using 3 for vips.config.192.168.4.113.vrid
[2013-09-16T13:14:20+02:00] DEBUG: filtered backtrace of compile error: /var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb:254:in `from_file'
[2013-09-16T13:14:20+02:00] DEBUG: filtered backtrace of compile error: /var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb:254:in `from_file'
[2013-09-16T13:14:20+02:00] DEBUG: backtrace entry for compile error: '/var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb:254:in `from_file''
[2013-09-16T13:14:20+02:00] DEBUG: Line number of compile error: '254'

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb
================================================================================


NameError
---------
Cannot find a resource for keepalived_chkscript on ubuntu version 12.04


Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb:254:in `from_file'


Relevant File Content:
----------------------
/var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb:

247:      Chef::Log.debug "using #{router_id} for vips.config.#{vip}.vrid"
248:    elsif router_id = rcb_safe_deref(node, "mysql.ha.vrid")
249:      Chef::Application.fatal! "node[\"mysql\"][\"ha\"][\"vrid\"] is deprecated.  Please set node[\"vips\"][\"config\"][\"#{vip}\"][\"vrid\"] instead"
250:    else
251:      Chef::Application.fatal! "You have not configured a VRID for the VIP.  Please set node[\"vips\"][\"config\"][\"#{vip}\"][\"vrid\"]"
252:    end
253:
254>>   keepalived_chkscript "mysql" do
255:      script "killall -0 mysqld"
256:      interval 5
257:      action :create
258:    end
```

It's rather odd, as I see the keepalived recipe inclusion is working:

```
[2013-09-16T13:14:20+02:00] DEBUG: Loading Recipe keepalived via include_recipe
```

I can't seem to figure out why the inclusion of the recipe isn't resulting in the provider being available.

Any thoughts?

**Comment by odyssey4me** [comment]
Aha, I figured it out - I had uploaded the opscode cookbook into the Chef server for testing... so even though my folder had the resource, the cookbook coming down to the client wan't receiving the right version of cookbook. The opscode cookbook is a later version but doesn't have the LWRP's.
