### ISSUE TITLE
[nova-network]: specifying VlanManager with vlan_id causes chef error

### ISSUE THREAD

**Issue by clauded** [rcbops/chef-cookbooks#625]
Test was done with Grizzly on Ubuntu 12.04 with Chef 11.2.0 (ruby 1.9.1). Here's my overide file:

```
  "override_attributes": {
    "nova": {
      "network": {
        "network_manager": "nova.network.manager.VlanManager",
        "fixed_range" : "172.16.1.0/24"
      },
      "networks": {
        "label": "public",
        "bridge_dev": "eth0",
        "ipv4_cidr": "172.16.0.0/24",
        "bridge": "br100",
        "dns1": "8.8.4.4",
        "dns2": "8.8.8.8",
        "vlan_id" : "2003"
      }
```

And the error generated:

```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/nova-network/recipes/nova-controller.rb
================================================================================


NoMethodError
-------------
undefined method `has_key?' for "public":String


Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/nova-network/recipes/nova-setup.rb:33:in `block (2 levels) in from_file'
  /var/chef/cache/cookbooks/nova-network/recipes/nova-setup.rb:25:in `block in from_file'
  /var/chef/cache/cookbooks/nova-network/recipes/nova-setup.rb:24:in `each'
  /var/chef/cache/cookbooks/nova-network/recipes/nova-setup.rb:24:in `from_file'
  /var/chef/cache/cookbooks/nova-network/recipes/nova-controller.rb:24:in `from_file'


Relevant File Content:
----------------------
/var/chef/cache/cookbooks/nova-network/recipes/nova-setup.rb:

 26:      label v['label']
 27:      multi_host true
 28:      fixed_range v['ipv4_cidr']
 29:      bridge v['bridge']
 30:      bridge_int v['bridge_dev']
 31:      dns1 v['dns1']
 32:      dns2 v['dns2']
 33>>     if v.has_key?('vlan_id')
 34:        Chef::Log.debug "Vlan ID set #{v['vlan_id']}"
 35:        vlan_id v['vlan_id']
 36:      end
 37:      action :create_fixed
 38:    end
 39:  end
 40:  
```

**Comment by clauded** [comment]
OK, I found the problem : a syntax error in the overide file:

```
  "override_attributes": {
    "nova": {
      "network": {
        "network_manager": "nova.network.manager.VlanManager",
        "fixed_range" : "172.16.1.0/24"
      },
      "networks": {
        "public": {
          "label": "public",
          "bridge_dev": "eth0",
          "ipv4_cidr": "172.16.0.0/24",
          "bridge": "br100",
          "dns1": "8.8.4.4",
          "dns2": "8.8.8.8",
          "vlan_id": 2003
        }
      }
    },
```
