### ISSUE TITLE
V4.2.1: Iptables for ha-proxy vip is getting DNATd on preroute to localhosts ip instead of loopback ip

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#684]
```
root@qa-precise-pool794:~# ip netns exec vips iptables-save -C
iptables-save: invalid option -- 'C'
# Generated by iptables-save v1.4.12 on Wed Nov 27 13:06:27 2013
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A PREROUTING -d 198.101.133.156/32 -j DNAT --to-destination 198.101.133.227
-A PREROUTING -d 198.101.133.155/32 -j DNAT --to-destination 198.101.133.227
-A PREROUTING -d 198.101.133.154/32 -j DNAT --to-destination 198.101.133.227
-A POSTROUTING -m conntrack --ctstate DNAT --ctorigdst 198.101.133.156 -j SNAT --to-source 198.101.133.156
-A POSTROUTING -m conntrack --ctstate DNAT --ctorigdst 198.101.133.155 -j SNAT --to-source 198.101.133.155
-A POSTROUTING -m conntrack --ctstate DNAT --ctorigdst 198.101.133.154 -j SNAT --to-source 198.101.133.154
```

This is causing a no route to host error on controller 2 runs for all haproxy vip services

```
2013-11-27 12:37:17,011 rcbops.qa INFO: [2013-11-27T12:37:17-06:00] INFO: Processing file[/etc/keystone/ssl/certs/ca.pem] action create (keystone::keystone-api line 62)
2013-11-27 12:37:17,013 rcbops.qa INFO: [2013-11-27T12:37:17-06:00] INFO: Processing keystone_service[Create Identity Service] action create (keystone::keystone-api line 76)
2013-11-27 12:37:20,084 rcbops.qa INFO: 
2013-11-27 12:37:20,084 rcbops.qa INFO: ================================================================================
2013-11-27 12:37:20,085 rcbops.qa INFO: Error executing action `create` on resource 'keystone_service[Create Identity Service]'
2013-11-27 12:37:20,085 rcbops.qa INFO: ================================================================================
2013-11-27 12:37:20,085 rcbops.qa INFO: 
2013-11-27 12:37:20,085 rcbops.qa INFO: 
2013-11-27 12:37:20,085 rcbops.qa INFO: Errno::EHOSTUNREACH
2013-11-27 12:37:20,085 rcbops.qa INFO: -------------------
2013-11-27 12:37:20,086 rcbops.qa INFO: No route to host - connect(2)
2013-11-27 12:37:20,086 rcbops.qa INFO: 
2013-11-27 12:37:20,086 rcbops.qa INFO: 
2013-11-27 12:37:20,086 rcbops.qa INFO: Cookbook Trace:
2013-11-27 12:37:20,086 rcbops.qa INFO: ---------------
2013-11-27 12:37:20,086 rcbops.qa INFO: /var/chef/cache/cookbooks/keystone/libraries/helpers.rb:12:in `find_value'
2013-11-27 12:37:20,087 rcbops.qa INFO: /var/chef/cache/cookbooks/keystone/providers/service.rb:49:in `block in class_from_file'
2013-11-27 12:37:20,087 rcbops.qa INFO: 
2013-11-27 12:37:20,087 rcbops.qa INFO: 
2013-11-27 12:37:20,087 rcbops.qa INFO: Resource Declaration:
2013-11-27 12:37:20,088 rcbops.qa INFO: ---------------------
2013-11-27 12:37:20,088 rcbops.qa INFO: # In /var/chef/cache/cookbooks/keystone/recipes/keystone-api.rb
2013-11-27 12:37:20,088 rcbops.qa INFO: 
2013-11-27 12:37:20,088 rcbops.qa INFO: 76: keystone_service "Create Identity Service" do
2013-11-27 12:37:20,088 rcbops.qa INFO: 77:   auth_host ks_admin_endpoint["host"]
2013-11-27 12:37:20,088 rcbops.qa INFO: 78:   auth_port ks_admin_endpoint["port"]
2013-11-27 12:37:20,089 rcbops.qa INFO: 79:   auth_protocol ks_admin_endpoint["scheme"]
2013-11-27 12:37:20,089 rcbops.qa INFO: 80:   api_ver ks_admin_endpoint["path"]
2013-11-27 12:37:20,089 rcbops.qa INFO: 81:   auth_token keystone["admin_token"]
2013-11-27 12:37:20,089 rcbops.qa INFO: 82:   service_name "keystone"
2013-11-27 12:37:20,089 rcbops.qa INFO: 83:   service_type "identity"
2013-11-27 12:37:20,089 rcbops.qa INFO: 84:   service_description "Keystone Identity Service"
2013-11-27 12:37:20,089 rcbops.qa INFO: 85:   action :create
2013-11-27 12:37:20,089 rcbops.qa INFO: 86: end
2013-11-27 12:37:20,089 rcbops.qa INFO: 87:
2013-11-27 12:37:20,089 rcbops.qa INFO: 
2013-11-27 12:37:20,089 rcbops.qa INFO: 
2013-11-27 12:37:20,089 rcbops.qa INFO: 
2013-11-27 12:37:20,089 rcbops.qa INFO: Compiled Resource:
2013-11-27 12:37:20,089 rcbops.qa INFO: ------------------
2013-11-27 12:37:20,089 rcbops.qa INFO: # Declared in /var/chef/cache/cookbooks/keystone/recipes/keystone-api.rb:76:in `from_file'
2013-11-27 12:37:20,089 rcbops.qa INFO: 
2013-11-27 12:37:20,090 rcbops.qa INFO: keystone_service("Create Identity Service") do
2013-11-27 12:37:20,090 rcbops.qa INFO: action [:create]
2013-11-27 12:37:20,090 rcbops.qa INFO: retries 0
2013-11-27 12:37:20,090 rcbops.qa INFO: retry_delay 2
2013-11-27 12:37:20,090 rcbops.qa INFO: cookbook_name "keystone"
2013-11-27 12:37:20,090 rcbops.qa INFO: recipe_name "keystone-api"
2013-11-27 12:37:20,090 rcbops.qa INFO: auth_host "198.101.133.156"
2013-11-27 12:37:20,090 rcbops.qa INFO: auth_port "35357"
2013-11-27 12:37:20,090 rcbops.qa INFO: auth_protocol "http"
2013-11-27 12:37:20,090 rcbops.qa INFO: api_ver "/v2.0"
2013-11-27 12:37:20,090 rcbops.qa INFO: auth_token "5oH_5aIU0ZeIvgyb_twM"
2013-11-27 12:37:20,090 rcbops.qa INFO: service_name "keystone"
2013-11-27 12:37:20,090 rcbops.qa INFO: service_type "identity"
2013-11-27 12:37:20,090 rcbops.qa INFO: service_description "Keystone Identity Service"
2013-11-27 12:37:20,090 rcbops.qa INFO: end
2013-11-27 12:37:20,090 rcbops.qa INFO: 
2013-11-27 12:37:20,090 rcbops.qa INFO: 
2013-11-27 12:37:20,091 rcbops.qa INFO: 
2013-11-27 12:37:20,091 rcbops.qa INFO: [2013-11-27T12:37:20-06:00] INFO: Running queued delayed notifications before re-raising exception
2013-11-27 12:37:20,091 rcbops.qa INFO: [2013-11-27T12:37:20-06:00] INFO: template[/etc/collectd/plugins/syslog.conf] sending restart action to service[collectd] (delayed)
2013-11-27 12:37:20,091 rcbops.qa INFO: [2013-11-27T12:37:20-06:00] INFO: Processing service[collectd] action restart (collectd::default line 33)
2013-11-27 12:37:22,184 rcbops.qa INFO: [2013-11-27T12:37:22-06:00] INFO: service[collectd] restarted
2013-11-27 12:37:22,185 rcbops.qa INFO: [2013-11-27T12:37:22-06:00] ERROR: Running exception handlers
2013-11-27 12:37:22,185 rcbops.qa INFO: [2013-11-27T12:37:22-06:00] ERROR: Exception handlers complete
2013-11-27 12:37:22,186 rcbops.qa INFO: [2013-11-27T12:37:22-06:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
2013-11-27 12:37:22,220 rcbops.qa INFO: [2013-11-27T12:37:22-06:00] ERROR: keystone_service[Create Identity Service] (keystone::keystone-api line 76) had an error: Errno::EHOSTUNREACH: No route to host - connect(2)
2013-11-27 12:37:22,260 rcbops.qa INFO: [2013-11-27T12:37:22-06:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

I also obviously cannot ping the vip either

```
root@qa-precise-pool794:~# ping -c 5 198.101.133.156
PING 198.101.133.156 (198.101.133.156) 56(84) bytes of data.
From 198.101.133.227 icmp_seq=1 Destination Host Unreachable
From 198.101.133.227 icmp_seq=2 Destination Host Unreachable
From 198.101.133.227 icmp_seq=3 Destination Host Unreachable
From 198.101.133.227 icmp_seq=4 Destination Host Unreachable
From 198.101.133.227 icmp_seq=5 Destination Host Unreachable

--- 198.101.133.156 ping statistics ---
5 packets transmitted, 0 received, +5 errors, 100% packet loss, time 4022ms
```

**Comment by jacobwagner** [comment]
verified fixed by QE

:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A PREROUTING -d 198.101.133.154/32 -j DNAT --to-destination 198.101.133.226
-A PREROUTING -d 198.101.133.156/32 -j DNAT --to-destination 169.254.123.1
-A PREROUTING -d 198.101.133.155/32 -j DNAT --to-destination 198.101.133.226
-A POSTROUTING -m conntrack --ctstate DNAT --ctorigdst 198.101.133.156 -j SNAT --to-source 198.101.133.156
-A POSTROUTING -m conntrack --ctstate DNAT --ctorigdst 198.101.133.154 -j SNAT --to-source 198.101.133.154
-A POSTROUTING -m conntrack --ctstate DNAT --ctorigdst 198.101.133.155 -j SNAT --to-source 198.101.133.155
