### ISSUE TITLE
4.1.2 to 4.1.3 Upgrade

### ISSUE THREAD

**Issue by cjoelrun** [rcbops/chef-cookbooks#686]
Due to race conditions in restarting keepalived, chef-client failures are expected in the upgrade from 4.1.2 to 4.1.3.

The process needed differs by distribution

On Centos
run chef-client and you'll see the first error below.
run chef-cleint again and you'll see the second error below
run service keepalived restart and run chef-client again to fix

On Ubuntu
run chef-client and you'll see the second error below
run chef-client again to fix

On first chef run:

```
2013-11-27 12:15:03,147 rcbops.qa INFO: [2013-11-27T11:15:10-07:00] INFO: Processing mysql_database[create keystone database] action create (keystone::setup line 34)
2013-11-27 12:15:06,297 rcbops.qa INFO:
2013-11-27 12:15:06,298 rcbops.qa INFO: ================================================================================
2013-11-27 12:15:06,298 rcbops.qa INFO: Error executing action `create` on resource 'mysql_database[create keystone database]'
2013-11-27 12:15:06,299 rcbops.qa INFO: ================================================================================
2013-11-27 12:15:06,299 rcbops.qa INFO:
2013-11-27 12:15:06,299 rcbops.qa INFO:
2013-11-27 12:15:06,299 rcbops.qa INFO: Mysql::Error
2013-11-27 12:15:06,299 rcbops.qa INFO: ------------
2013-11-27 12:15:06,299 rcbops.qa INFO: Can't connect to MySQL server on '198.101.133.157' (113)
2013-11-27 12:15:06,299 rcbops.qa INFO:
2013-11-27 12:15:06,299 rcbops.qa INFO:
2013-11-27 12:15:06,299 rcbops.qa INFO: Cookbook Trace:
2013-11-27 12:15:06,300 rcbops.qa INFO: ---------------
2013-11-27 12:15:06,300 rcbops.qa INFO: /var/chef/cache/cookbooks/database/libraries/provider_database_mysql.rb:83:in `new'
2013-11-27 12:15:06,300 rcbops.qa INFO: /var/chef/cache/cookbooks/database/libraries/provider_database_mysql.rb:83:in `db'
2013-11-27 12:15:06,300 rcbops.qa INFO: /var/chef/cache/cookbooks/database/libraries/provider_database_mysql.rb:78:in `exists?'
2013-11-27 12:15:06,300 rcbops.qa INFO: /var/chef/cache/cookbooks/database/libraries/provider_database_mysql.rb:36:in `action_create'
2013-11-27 12:15:06,300 rcbops.qa INFO:
2013-11-27 12:15:06,300 rcbops.qa INFO:
2013-11-27 12:15:06,300 rcbops.qa INFO: Resource Declaration:
2013-11-27 12:15:06,300 rcbops.qa INFO: ---------------------
2013-11-27 12:15:06,301 rcbops.qa INFO: # In /var/chef/cache/cookbooks/osops-utils/libraries/database.rb
2013-11-27 12:15:06,301 rcbops.qa INFO:
2013-11-27 12:15:06,301 rcbops.qa INFO: 34:       mysql_database "create #{db_name} database" do
2013-11-27 12:15:06,301 rcbops.qa INFO: 35:         connection connection_info
2013-11-27 12:15:06,301 rcbops.qa INFO: 36:         database_name db_name
2013-11-27 12:15:06,301 rcbops.qa INFO: 37:         action :create
2013-11-27 12:15:06,301 rcbops.qa INFO: 38:       end
2013-11-27 12:15:06,301 rcbops.qa INFO: 39:
2013-11-27 12:15:06,301 rcbops.qa INFO:
2013-11-27 12:15:06,302 rcbops.qa INFO:
2013-11-27 12:15:06,302 rcbops.qa INFO:
2013-11-27 12:15:06,302 rcbops.qa INFO: Compiled Resource:
2013-11-27 12:15:06,302 rcbops.qa INFO: ------------------
2013-11-27 12:15:06,348 rcbops.qa INFO: # Declared in /var/chef/cache/cookbooks/osops-utils/libraries/database.rb:34:in `create_db_and_user'
2013-11-27 12:15:06,348 rcbops.qa INFO:
2013-11-27 12:15:06,348 rcbops.qa INFO: mysql_database("create keystone database") do
2013-11-27 12:15:06,348 rcbops.qa INFO: provider Chef::Provider::Database::Mysql
2013-11-27 12:15:06,348 rcbops.qa INFO: action [:create]
2013-11-27 12:15:06,349 rcbops.qa INFO: retries 0
2013-11-27 12:15:06,349 rcbops.qa INFO: retry_delay 2
2013-11-27 12:15:06,349 rcbops.qa INFO: database_name "keystone"
2013-11-27 12:15:06,349 rcbops.qa INFO: cookbook_name "keystone"
2013-11-27 12:15:06,349 rcbops.qa INFO: recipe_name "setup"
2013-11-27 12:15:06,349 rcbops.qa INFO: connection {:host=>"198.101.133.157", :username=>"root", :password=>"EXg9hfFHhW2WVDGRj3rn"}
2013-11-27 12:15:06,349 rcbops.qa INFO: end
```

On 2nd run:

```
2013-11-27 12:17:35,895 rcbops.qa INFO: [2013-11-27T11:17:43-07:00] INFO: Processing keystone_register[Recreate keystone Endpoint] action recreate_endpoint (openstack-ha::default line 184)
2013-11-27 12:17:38,903 rcbops.qa INFO: [2013-11-27T11:17:46-07:00] INFO: Retrying execution of keystone_register[Recreate keystone Endpoint], 9 attempt(s) left
2013-11-27 12:17:46,121 rcbops.qa INFO: [2013-11-27T11:17:53-07:00] INFO: Retrying execution of keystone_register[Recreate keystone Endpoint], 8 attempt(s) left
2013-11-27 12:17:54,123 rcbops.qa INFO: [2013-11-27T11:18:01-07:00] INFO: Retrying execution of keystone_register[Recreate keystone Endpoint], 7 attempt(s) left
2013-11-27 12:18:02,126 rcbops.qa INFO: [2013-11-27T11:18:09-07:00] INFO: Retrying execution of keystone_register[Recreate keystone Endpoint], 6 attempt(s) left
2013-11-27 12:18:10,128 rcbops.qa INFO: [2013-11-27T11:18:17-07:00] INFO: Retrying execution of keystone_register[Recreate keystone Endpoint], 5 attempt(s) left
2013-11-27 12:18:18,130 rcbops.qa INFO: [2013-11-27T11:18:25-07:00] INFO: Retrying execution of keystone_register[Recreate keystone Endpoint], 4 attempt(s) left
2013-11-27 12:18:26,133 rcbops.qa INFO: [2013-11-27T11:18:33-07:00] INFO: Retrying execution of keystone_register[Recreate keystone Endpoint], 3 attempt(s) left
2013-11-27 12:18:34,136 rcbops.qa INFO: [2013-11-27T11:18:41-07:00] INFO: Retrying execution of keystone_register[Recreate keystone Endpoint], 2 attempt(s) left
2013-11-27 12:18:42,139 rcbops.qa INFO: [2013-11-27T11:18:49-07:00] INFO: Retrying execution of keystone_register[Recreate keystone Endpoint], 1 attempt(s) left
2013-11-27 12:18:50,142 rcbops.qa INFO: [2013-11-27T11:18:57-07:00] INFO: Retrying execution of keystone_register[Recreate keystone Endpoint], 0 attempt(s) left
2013-11-27 12:18:58,207 rcbops.qa INFO:
2013-11-27 12:18:58,208 rcbops.qa INFO: ================================================================================
2013-11-27 12:18:58,208 rcbops.qa INFO: Error executing action `recreate_endpoint` on resource 'keystone_register[Recreate keystone Endpoint]'
2013-11-27 12:18:58,208 rcbops.qa INFO: ================================================================================
2013-11-27 12:18:58,208 rcbops.qa INFO:
2013-11-27 12:18:58,208 rcbops.qa INFO:
2013-11-27 12:18:58,209 rcbops.qa INFO: Errno::EHOSTUNREACH
2013-11-27 12:18:58,209 rcbops.qa INFO: -------------------
2013-11-27 12:18:58,209 rcbops.qa INFO: No route to host - connect(2)
2013-11-27 12:18:58,209 rcbops.qa INFO:
2013-11-27 12:18:58,209 rcbops.qa INFO:
2013-11-27 12:18:58,210 rcbops.qa INFO: Cookbook Trace:
2013-11-27 12:18:58,210 rcbops.qa INFO: ---------------
2013-11-27 12:18:58,210 rcbops.qa INFO: /var/chef/cache/cookbooks/keystone/libraries/helpers.rb:12:in `find_value'
2013-11-27 12:18:58,210 rcbops.qa INFO: /var/chef/cache/cookbooks/keystone/providers/register.rb:285:in `block in class_from_file'
2013-11-27 12:18:58,210 rcbops.qa INFO:
2013-11-27 12:18:58,210 rcbops.qa INFO:
2013-11-27 12:18:58,211 rcbops.qa INFO: Resource Declaration:
2013-11-27 12:18:58,211 rcbops.qa INFO: ---------------------
2013-11-27 12:18:58,211 rcbops.qa INFO: # In /var/chef/cache/cookbooks/openstack-ha/recipes/default.rb
2013-11-27 12:18:58,211 rcbops.qa INFO:
2013-11-27 12:18:58,211 rcbops.qa INFO: 184:       keystone_register "Recreate #{ns} Endpoint" do
2013-11-27 12:18:58,212 rcbops.qa INFO: 185:         auth_host ks_admin_endpoint["host"]
2013-11-27 12:18:58,212 rcbops.qa INFO: 186:         auth_port ks_admin_endpoint["port"]
2013-11-27 12:18:58,212 rcbops.qa INFO: 187:         auth_protocol ks_admin_endpoint["scheme"]
2013-11-27 12:18:58,212 rcbops.qa INFO: 188:         api_ver ks_admin_endpoint["path"]
2013-11-27 12:18:58,212 rcbops.qa INFO: 189:         auth_token keystone["admin_token"]
2013-11-27 12:18:58,212 rcbops.qa INFO: 190:         service_type svc_type
2013-11-27 12:18:58,212 rcbops.qa INFO: 191:         endpoint_region node["nova"]["compute"]["region"]
2013-11-27 12:18:58,213 rcbops.qa INFO: 192:         endpoint_publicurl public_endpoint["uri"]
2013-11-27 12:18:58,213 rcbops.qa INFO: 193:         endpoint_internalurl internal_endpoint["uri"]
2013-11-27 12:18:58,213 rcbops.qa INFO: 194:         endpoint_adminurl admin_endpoint["uri"]
2013-11-27 12:18:58,213 rcbops.qa INFO: 195:         retries 10
2013-11-27 12:18:58,213 rcbops.qa INFO: 196:         retry_delay 5
2013-11-27 12:18:58,213 rcbops.qa INFO: 197:         action :recreate_endpoint
2013-11-27 12:18:58,213 rcbops.qa INFO: 198:       end
2013-11-27 12:18:58,214 rcbops.qa INFO: 199:     end
2013-11-27 12:18:58,214 rcbops.qa INFO:
2013-11-27 12:18:58,214 rcbops.qa INFO:
2013-11-27 12:18:58,214 rcbops.qa INFO:
2013-11-27 12:18:58,255 rcbops.qa INFO: Compiled Resource:
2013-11-27 12:18:58,255 rcbops.qa INFO: ------------------
2013-11-27 12:18:58,256 rcbops.qa INFO: # Declared in /var/chef/cache/cookbooks/openstack-ha/recipes/default.rb:184:in `block in from_file'
2013-11-27 12:18:58,256 rcbops.qa INFO:
2013-11-27 12:18:58,256 rcbops.qa INFO: keystone_register("Recreate keystone Endpoint") do
2013-11-27 12:18:58,256 rcbops.qa INFO: action [:recreate_endpoint]
2013-11-27 12:18:58,256 rcbops.qa INFO: retries 0
2013-11-27 12:18:58,257 rcbops.qa INFO: retry_delay 5
2013-11-27 12:18:58,257 rcbops.qa INFO: cookbook_name "openstack-ha"
2013-11-27 12:18:58,257 rcbops.qa INFO: recipe_name "default"
2013-11-27 12:18:58,257 rcbops.qa INFO: auth_host "198.101.133.159"
2013-11-27 12:18:58,257 rcbops.qa INFO: auth_port "35357"
2013-11-27 12:18:58,257 rcbops.qa INFO: auth_protocol "http"
2013-11-27 12:18:58,257 rcbops.qa INFO: api_ver "/v2.0"
2013-11-27 12:18:58,257 rcbops.qa INFO: auth_token "N99dGyszADcGAi_SFttj"
2013-11-27 12:18:58,258 rcbops.qa INFO: service_type "identity"
2013-11-27 12:18:58,258 rcbops.qa INFO: endpoint_region "RegionOne"
2013-11-27 12:18:58,258 rcbops.qa INFO: endpoint_adminurl "http://198.101.133.159:35357/v2.0"
2013-11-27 12:18:58,258 rcbops.qa INFO: endpoint_internalurl "http://198.101.133.159:5000/v2.0"
2013-11-27 12:18:58,258 rcbops.qa INFO: endpoint_publicurl "http://198.101.133.159:5000/v2.0"
```

**Comment by jacobwagner** [comment]
Verified fixed by QE
