### ISSUE TITLE
RPCdaemon is not starting

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#713]
2013-12-10 10:51:04  rpcdaemon  INFO     Initializing...
2013-12-10 10:51:04  rpcdaemon  INFO     Loading plugins...
Traceback (most recent call last):
  File "/usr/bin/rpcdaemon", line 9, in <module>
    load_entry_point('RPCDaemon==1.0.0', 'console_scripts', 'rpcdaemon')()
  File "/usr/lib/pymodules/python2.7/rpcdaemon/**init**.py", line 164, in main
    with Monitor(sys.argv[1:]) as monitor:
  File "/usr/lib/python2.7/dist-packages/daemon/daemon.py", line 352, in **enter**
    self.open()
  File "/usr/lib/pymodules/python2.7/rpcdaemon/**init**.py", line 129, in open
    for module in self.config['plugins'].split()
ImportError: No module named l3agent,dhcpagent

**Comment by jacobwagner** [comment]
root@qa-precise-pool880:~# dpkg -l rpcdaemon
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                    Version                 Description
+++-=======================-=======================-==============================================================
ii  rpcdaemon               1.0.0.20131204-1        OpenStack AMQP listener daemon

**Comment by jacobwagner** [comment]
seeing this on both Ubuntu and Centos fresh installs and upgrades

**Comment by jacobwagner** [comment]
verified fixed on Centos

```
2013-12-16 09:13:17  rpcdaemon  INFO     Initializing...
2013-12-16 09:13:17  rpcdaemon  INFO     Loading plugins...
2013-12-16 09:13:17  l3agent    INFO     Populating agents...
2013-12-16 09:13:17  dhcpagent  INFO     Populating agents...
2013-12-16 09:13:18  rpcdaemon  INFO     Starting worker...
2013-12-16 09:13:18  rpcdaemon  INFO     Started.
```

**Comment by jacobwagner** [comment]
Verified fixed on Precise

```
root@qa-precise-pool935:~# cat /var/log/rpcdaemon.log 
2013-12-16 12:15:35  rpcdaemon  INFO     Initializing...
2013-12-16 12:15:35  rpcdaemon  INFO     Loading plugins...
2013-12-16 12:15:35  l3agent    INFO     Populating agents...
2013-12-16 12:15:35  dhcpagent  INFO     Populating agents...
2013-12-16 12:15:35  rpcdaemon  INFO     Starting worker...
2013-12-16 12:15:36  rpcdaemon  INFO     Started.
```
