### ISSUE TITLE
python-swiftclient in ubuntu upgrade

### ISSUE THREAD

**Issue by cjoelrun** [rcbops/chef-cookbooks#715]
When upgrading from 4.1.3 to 4.2.1rc chef-client fails on compute
because of a python-swiftclient version conflict.

```
apt-get -q -y -o Dpkg::Options:='--force-confold' -o Dpkg::Options:='--force-confdef' install ceilometer-agent-compute=2013.2-0ubuntu1~cloud0
```

After `apt-get update`

```
root@qa-precise-pool887:~# apt-cache policy python-swiftclient
python-swiftclient:
  Installed: 1:1.3.0-0ubuntu1~cloud0
  Candidate: 1:1.6.0-0ubuntu1~cloud0
  Version table:
     1:1.6.0-0ubuntu1~cloud0 0
        500 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/havana/main amd64 Packages
 *** 1:1.3.0-0ubuntu1~cloud0 0
        500 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/grizzly/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by cjoelrun** [comment]
Still seeing this happen on compute node after upgrade

A subsequent run of chef-client fixes works.

Doc bug?

```
Recipe: ceilometer::ceilometer-compute
  * package[ceilometer-agent-compute] action upgrade
================================================================================
Error executing action `upgrade` on resource 'package[ceilometer-agent-compute]'
================================================================================


Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '100'
---- Begin output of apt-get -q -y -o Dpkg::Options:='--force-confold' -o Dpkg::Options:='--force-confdef' install ceilometer-agent-compute=2013.2-0ubuntu1~cloud0 ----
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  python-keyring python-daemon python-pycurl python-nose python-gflags
  python-quantum python-carrot python-glance python-utidylib python-configobj
  python-stompy python-oslo-config python-lockfile python-feedparser
  python-dateutil libtidy-0.99-0 python-libxml2 python-xattr python-dingus
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  ceilometer-common msgpack-python python-beautifulsoup python-bson
  python-bson-ext python-ceilometer python-ceilometerclient python-flask
  python-glanceclient python-gridfs python-happybase python-itsdangerous
  python-pecan python-pymongo python-pymongo-ext python-simplegeneric
  python-thrift python-webtest python-werkzeug python-wsme
Suggested packages:
  python-flask-doc ipython python-genshi python-memcache
The following NEW packages will be installed:
  ceilometer-agent-compute ceilometer-common msgpack-python
  python-beautifulsoup python-bson python-bson-ext python-ceilometer
  python-ceilometerclient python-flask python-gridfs python-happybase
  python-itsdangerous python-pecan python-pymongo python-pymongo-ext
  python-simplegeneric python-thrift python-webtest python-werkzeug
  python-wsme
The following packages will be upgraded:
  python-glanceclient
1 upgraded, 20 newly installed, 0 to remove and 23 not upgraded.
Need to get 2,943 kB of archives.
After this operation, 12.8 MB of additional disk space will be used.
Get:1 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/havana/main python-thrift amd64 0.9.0-1~cloud1 [35.4 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ precise/main python-werkzeug all 0.8.1+dfsg-1 [1,321 kB]
Get:3 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/havana/main python-happybase all 0.6-1ubuntu1~cloud0 [33.6 kB]
Get:4 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/grizzly/main python-simplegeneric all 0.8.1-1~cloud0 [11.8 kB]
Get:5 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/havana/main python-webtest all 1.3.4-1~cloud0 [74.7 kB]
Get:6 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/havana/main python-pecan all 0.3.0-1ubuntu1~cloud0 [121 kB]
Get:7 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/havana/main python-wsme all 0.5b5-1ubuntu2~cloud0 [66.6 kB]
Get:8 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/havana/main msgpack-python amd64 0.3.0-0ubuntu1~cloud1 [57.5 kB]
Get:9 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/havana/main python-ceilometerclient all 1.0.5-0ubuntu1~cloud0 [31.3 kB]
Get:10 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/havana/main python-itsdangerous all 0.22+dfsg1-1~cloud0 [12.5 kB]
Get:11 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/havana/main python-flask all 0.10.1-2~cloud1 [63.7 kB]
Get:12 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/havana/main python-glanceclient all 1:0.11.0-0ubuntu1~cloud0 [81.0 kB]
Get:13 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/havana/main python-bson amd64 2.6-1~cloud1 [34.3 kB]
Get:14 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/havana/main python-pymongo amd64 2.6-1~cloud1 [116 kB]
Get:15 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/havana/main python-ceilometer all 2013.2-0ubuntu1~cloud0 [750 kB]
Get:16 http://archive.ubuntu.com/ubuntu/ precise/main python-beautifulsoup all 3.2.0-2build1 [34.5 kB]
Get:17 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/havana/main ceilometer-common all 2013.2-0ubuntu1~cloud0 [10.3 kB]
Get:18 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/havana/main ceilometer-agent-compute all 2013.2-0ubuntu1~cloud0 [2,776 B]
Get:19 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/havana/main python-bson-ext amd64 2.6-1~cloud1 [34.6 kB]
Get:20 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/havana/main python-gridfs all 2.6-1~cloud1 [25.7 kB]
Get:21 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/havana/main python-pymongo-ext amd64 2.6-1~cloud1 [25.1 kB]
Fetched 2,943 kB in 1s (1,835 kB/s)
Selecting previously unselected package python-thrift.
(Reading database ... 91602 files and directories currently installed.)
Unpacking python-thrift (from .../python-thrift_0.9.0-1~cloud1_amd64.deb) ...
Selecting previously unselected package python-happybase.
Unpacking python-happybase (from .../python-happybase_0.6-1ubuntu1~cloud0_all.deb) ...
Selecting previously unselected package python-simplegeneric.
Unpacking python-simplegeneric (from .../python-simplegeneric_0.8.1-1~cloud0_all.deb) ...
Selecting previously unselected package python-webtest.
Unpacking python-webtest (from .../python-webtest_1.3.4-1~cloud0_all.deb) ...
Selecting previously unselected package python-pecan.
Unpacking python-pecan (from .../python-pecan_0.3.0-1ubuntu1~cloud0_all.deb) ...
Selecting previously unselected package python-wsme.
Unpacking python-wsme (from .../python-wsme_0.5b5-1ubuntu2~cloud0_all.deb) ...
Selecting previously unselected package msgpack-python.
Unpacking msgpack-python (from .../msgpack-python_0.3.0-0ubuntu1~cloud1_amd64.deb) ...
Selecting previously unselected package python-ceilometerclient.
Unpacking python-ceilometerclient (from .../python-ceilometerclient_1.0.5-0ubuntu1~cloud0_all.deb) ...
Selecting previously unselected package python-werkzeug.
Unpacking python-werkzeug (from .../python-werkzeug_0.8.1+dfsg-1_all.deb) ...
Selecting previously unselected package python-itsdangerous.
Unpacking python-itsdangerous (from .../python-itsdangerous_0.22+dfsg1-1~cloud0_all.deb) ...
Selecting previously unselected package python-flask.
Unpacking python-flask (from .../python-flask_0.10.1-2~cloud1_all.deb) ...
Preparing to replace python-glanceclient 1:0.9.0-0ubuntu1.2~cloud0 (using .../python-glanceclient_1%3a0.11.0-0ubuntu1~cloud0_all.deb) ...
Unpacking replacement python-glanceclient ...
Selecting previously unselected package python-bson.
Unpacking python-bson (from .../python-bson_2.6-1~cloud1_amd64.deb) ...
Selecting previously unselected package python-pymongo.
Unpacking python-pymongo (from .../python-pymongo_2.6-1~cloud1_amd64.deb) ...
Selecting previously unselected package python-ceilometer.
Unpacking python-ceilometer (from .../python-ceilometer_2013.2-0ubuntu1~cloud0_all.deb) ...
Selecting previously unselected package ceilometer-common.
Unpacking ceilometer-common (from .../ceilometer-common_2013.2-0ubuntu1~cloud0_all.deb) ...
Selecting previously unselected package ceilometer-agent-compute.
Unpacking ceilometer-agent-compute (from .../ceilometer-agent-compute_2013.2-0ubuntu1~cloud0_all.deb) ...
Selecting previously unselected package python-beautifulsoup.
Unpacking python-beautifulsoup (from .../python-beautifulsoup_3.2.0-2build1_all.deb) ...
Selecting previously unselected package python-bson-ext.
Unpacking python-bson-ext (from .../python-bson-ext_2.6-1~cloud1_amd64.deb) ...
Selecting previously unselected package python-gridfs.
Unpacking python-gridfs (from .../python-gridfs_2.6-1~cloud1_all.deb) ...
Selecting previously unselected package python-pymongo-ext.
Unpacking python-pymongo-ext (from .../python-pymongo-ext_2.6-1~cloud1_amd64.deb) ...
Processing triggers for ureadahead ...
Setting up python-thrift (0.9.0-1~cloud1) ...
Setting up python-happybase (0.6-1ubuntu1~cloud0) ...
Setting up python-simplegeneric (0.8.1-1~cloud0) ...
Setting up python-webtest (1.3.4-1~cloud0) ...
Setting up python-pecan (0.3.0-1ubuntu1~cloud0) ...
Setting up python-wsme (0.5b5-1ubuntu2~cloud0) ...
Setting up msgpack-python (0.3.0-0ubuntu1~cloud1) ...
Setting up python-ceilometerclient (1.0.5-0ubuntu1~cloud0) ...
Setting up python-werkzeug (0.8.1+dfsg-1) ...
Setting up python-itsdangerous (0.22+dfsg1-1~cloud0) ...
Setting up python-flask (0.10.1-2~cloud1) ...
Setting up python-glanceclient (1:0.11.0-0ubuntu1~cloud0) ...
Setting up python-bson (2.6-1~cloud1) ...
Setting up python-pymongo (2.6-1~cloud1) ...
Setting up python-ceilometer (2013.2-0ubuntu1~cloud0) ...
Setting up ceilometer-common (2013.2-0ubuntu1~cloud0) ...
Adding system user `ceilometer' (UID 110) ...
Adding new user `ceilometer' (UID 110) with group `ceilometer' ...
Not creating home directory `/var/lib/ceilometer'.
Setting up python-beautifulsoup (3.2.0-2build1) ...
Setting up python-bson-ext (2.6-1~cloud1) ...
Setting up python-gridfs (2.6-1~cloud1) ...
Setting up python-pymongo-ext (2.6-1~cloud1) ...
STDERR: 2013-12-13 18:01:24.284 20623 ERROR stevedore.extension [-] Could not load 'sqlite': (python-swiftclient 1.3.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('python-swiftclient>=1.5'))
2013-12-13 18:01:24.284 20623 ERROR stevedore.extension [-] (python-swiftclient 1.3.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('python-swiftclient>=1.5'))
2013-12-13 18:01:24.284 20623 TRACE stevedore.extension Traceback (most recent call last):
2013-12-13 18:01:24.284 20623 TRACE stevedore.extension   File "/usr/lib/python2.7/dist-packages/stevedore/extension.py", line 89, in _load_plugins
2013-12-13 18:01:24.284 20623 TRACE stevedore.extension     invoke_kwds,
2013-12-13 18:01:24.284 20623 TRACE stevedore.extension   File "/usr/lib/python2.7/dist-packages/stevedore/named.py", line 57, in _load_one_plugin
2013-12-13 18:01:24.284 20623 TRACE stevedore.extension     ep, invoke_on_load, invoke_args, invoke_kwds,
2013-12-13 18:01:24.284 20623 TRACE stevedore.extension   File "/usr/lib/python2.7/dist-packages/stevedore/extension.py", line 101, in _load_one_plugin
2013-12-13 18:01:24.284 20623 TRACE stevedore.extension     plugin = ep.load()
2013-12-13 18:01:24.284 20623 TRACE stevedore.extension   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1988, in load
2013-12-13 18:01:24.284 20623 TRACE stevedore.extension     if require: self.require(env, installer)
2013-12-13 18:01:24.284 20623 TRACE stevedore.extension   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2001, in require
2013-12-13 18:01:24.284 20623 TRACE stevedore.extension     working_set.resolve(self.dist.requires(self.extras),env,installer))
2013-12-13 18:01:24.284 20623 TRACE stevedore.extension   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 588, in resolve
2013-12-13 18:01:24.284 20623 TRACE stevedore.extension     raise VersionConflict(dist,req) # XXX put more info here
2013-12-13 18:01:24.284 20623 TRACE stevedore.extension VersionConflict: (python-swiftclient 1.3.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('python-swiftclient>=1.5'))
2013-12-13 18:01:24.284 20623 TRACE stevedore.extension
2013-12-13 18:01:24.285 20623 CRITICAL ceilometer [-] No 'ceilometer.storage' driver found, looking for 'sqlite'
dpkg: error processing ceilometer-common (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of ceilometer-agent-compute:
 ceilometer-agent-compute depends on ceilometer-common (= 2013.2-0ubuntu1~cloud0); however:
  Package ceilometer-common is not configured yet.
dpkg: error processing ceilometer-agent-compute (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
Errors were encountered while processing:
 ceilometer-common
 ceilometer-agent-compute
E: Sub-process /usr/bin/dpkg returned an error code (1)
---- End output of apt-get -q -y -o Dpkg::Options:='--force-confold' -o Dpkg::Options:='--force-confdef' install ceilometer-agent-compute=2013.2-0ubuntu1~cloud0 ----
Ran apt-get -q -y -o Dpkg::Options:='--force-confold' -o Dpkg::Options:='--force-confdef' install ceilometer-agent-compute=2013.2-0ubuntu1~cloud0 returned 100


Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/ceilometer/recipes/ceilometer-compute.rb

 25:   package pkg do
 26:     action node["osops"]["do_package_upgrades"] == true ? :upgrade : :install
 27:     options platform_options["package_options"]
 28:   end
 29: end



Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/ceilometer/recipes/ceilometer-compute.rb:25:in `block in from_file'

package("ceilometer-agent-compute") do
  action [:upgrade]
  retries 0
  retry_delay 2
  options "-o Dpkg::Options:='--force-confold' -o Dpkg::Options:='--force-confdef'"
  package_name "ceilometer-agent-compute"
  version "2013.2-0ubuntu1~cloud0"
  cookbook_name "ceilometer"
  recipe_name "ceilometer-compute"
end
```

**Comment by kaushikb** [comment]
At this stage, given that it is reproducible only in the QE env and since we have a workaround, let's doc this issue.

**Comment by klevenstein** [comment]
So we'll add this to the known issues? Please confirm workaround steps: if failure occurs, run apt-get update, then re-run chef client?

**Comment by cjoelrun** [comment]
chef-client a second time on compute if it fails

**Comment by klevenstein** [comment]
Proposed text: "When upgrading from v4.1.3 to v4.2.1, chef-client may fail on the Compute nodes due to a conflict in python-swiftclient versions. If this failure occurs, run chef-client a second time."

**Comment by cjoelrun** [comment]
Looks good
