### ISSUE TITLE
RPCdaemon not rescheduling router on server failover

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#729]
On Centos

When shutting down the controller with the routers and vips, rpcdaemon attempts to remove the router from neutron to reschedule but cannot connect, which then fails to move the router to the new controller

```
[root@qa-centos-pool876 ~]# tail -n 100 /var/log/neutron/server.log 
2013-12-16 11:16:50.418 1898 TRACE neutron.api.v2.resource   File "/usr/lib64/python2.6/site-packages/SQLAlchemy-0.7.8-py2.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2193, in one
2013-12-16 11:16:50.418 1898 TRACE neutron.api.v2.resource     "Multiple rows were found for one()")
2013-12-16 11:16:50.418 1898 TRACE neutron.api.v2.resource MultipleResultsFound: Multiple rows were found for one()
2013-12-16 11:16:50.418 1898 TRACE neutron.api.v2.resource 
2013-12-16 11:16:53.439 1898 ERROR neutron.api.v2.resource [-] delete failed
2013-12-16 11:16:53.439 1898 TRACE neutron.api.v2.resource Traceback (most recent call last):
2013-12-16 11:16:53.439 1898 TRACE neutron.api.v2.resource   File "/usr/lib/python2.6/site-packages/neutron/api/v2/resource.py", line 84, in resource
2013-12-16 11:16:53.439 1898 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2013-12-16 11:16:53.439 1898 TRACE neutron.api.v2.resource   File "/usr/lib/python2.6/site-packages/neutron/extensions/l3agentscheduler.py", line 79, in delete
2013-12-16 11:16:53.439 1898 TRACE neutron.api.v2.resource     request.context, kwargs['agent_id'], id)
2013-12-16 11:16:53.439 1898 TRACE neutron.api.v2.resource   File "/usr/lib/python2.6/site-packages/neutron/db/l3_agentschedulers_db.py", line 107, in remove_router_from_l3_agent
2013-12-16 11:16:53.439 1898 TRACE neutron.api.v2.resource     binding = query.one()
2013-12-16 11:16:53.439 1898 TRACE neutron.api.v2.resource   File "/usr/lib64/python2.6/site-packages/SQLAlchemy-0.7.8-py2.6-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2193, in one
2013-12-16 11:16:53.439 1898 TRACE neutron.api.v2.resource     "Multiple rows were found for one()")
2013-12-16 11:16:53.439 1898 TRACE neutron.api.v2.resource MultipleResultsFound: Multiple rows were found for one()
2013-12-16 11:16:53.439 1898 TRACE neutron.api.v2.resource 
2013-12-16 11:16:56.454 1898 ERROR neutron.api.v2.resource [-] delete failed
```

```
2013-12-16 11:13:46  rpcdaemon  INFO     Initializing...
2013-12-16 11:13:46  rpcdaemon  INFO     Loading plugins...
2013-12-16 11:13:46  l3agent    INFO     Populating agents...
2013-12-16 11:13:47  dhcpagent  INFO     Populating agents...
2013-12-16 11:13:47  rpcdaemon  INFO     Starting worker...
2013-12-16 11:13:47  rpcdaemon  INFO     Started.
2013-12-16 11:13:47  l3agent    INFO     Removing router 71e2adfa-4886-430b-a231-0b3a4bfe403e from qa-centos-pool879/L3 agent [48842d42-9acc-4523-aff1-c6b81eabb2a2]
2013-12-16 11:13:47  l3agent    WARNING  Retry 1: Request Failed: internal server error while processing your request.
2013-12-16 11:13:50  l3agent    WARNING  Retry 2: Request Failed: internal server error while processing your request.
2013-12-16 11:13:53  l3agent    WARNING  Retry 3: Request Failed: internal server error while processing your request.
2013-12-16 11:13:56  l3agent    WARNING  Retry 4: Request Failed: internal server error while processing your request.
2013-12-16 11:13:59  l3agent    WARNING  Retry 5: Request Failed: internal server error while processing your request.
2013-12-16 11:14:02  l3agent    WARNING  Retry 6: Request Failed: internal server error while processing your request.
2013-12-16 11:14:05  l3agent    WARNING  Retry 7: Request Failed: internal server error while processing your request.
2013-12-16 11:14:08  l3agent    WARNING  Retry 8: Request Failed: internal server error while processing your request.
2013-12-16 11:14:11  l3agent    WARNING  Retry 9: Request Failed: internal server error while processing your request.
2013-12-16 11:14:14  l3agent    WARNING  Retry 10: Request Failed: internal server error while processing your request.
2013-12-16 11:14:17  l3agent    ERROR    Retries exhausted.  Exiting
2013-12-16 11:14:17  rpcdaemon  INFO     Stopping worker...
2013-12-16 11:14:22  rpcdaemon  WARNING  Error stopping worker. Shutting down uncleanly.
2013-12-16 11:14:22  rpcdaemon  INFO     Stopped.
Traceback (most recent call last):
  File "/usr/bin/rpcdaemon", line 9, in <module>
    load_entry_point('RPCDaemon==1.0.0', 'console_scripts', 'rpcdaemon')()
  File "/usr/lib/python2.6/site-packages/rpcdaemon/__init__.py", line 166, in main
    monitor.check()
  File "/usr/lib/python2.6/site-packages/rpcdaemon/__init__.py", line 145, in check
    plugin.check()
  File "/usr/lib/python2.6/site-packages/rpcdaemon/lib/neutronagent.py", line 151, in check
    self.handle(agent, False)
  File "/usr/lib/python2.6/site-packages/rpcdaemon/plugins/l3agent.py", line 83, in handle
    lambda: self.client.remove_router_from_l3_agent(agent['id'],
  File "/usr/lib/python2.6/site-packages/rpcdaemon/lib/neutronagent.py", line 186, in retryable
    on_fail(exc_info)
  File "/usr/lib/python2.6/site-packages/rpcdaemon/lib/neutronagent.py", line 176, in retryable
    result = fn()
  File "/usr/lib/python2.6/site-packages/rpcdaemon/plugins/l3agent.py", line 84, in <lambda>
    router['id']))
  File "/usr/lib/python2.6/site-packages/neutronclient/v2_0/client.py", line 108, in with_params
    ret = self.function(instance, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/neutronclient/v2_0/client.py", line 966, in remove_router_from_l3_agent
    l3_agent, router_id))
  File "/usr/lib/python2.6/site-packages/neutronclient/v2_0/client.py", line 1179, in delete
    headers=headers, params=params)
  File "/usr/lib/python2.6/site-packages/neutronclient/v2_0/client.py", line 1168, in retry_request
    headers=headers, params=params)
  File "/usr/lib/python2.6/site-packages/neutronclient/v2_0/client.py", line 1111, in do_request
    self._handle_fault_response(status_code, replybody)
  File "/usr/lib/python2.6/site-packages/neutronclient/v2_0/client.py", line 1081, in _handle_fault_response
    exception_handler_v20(status_code, des_error_body)
  File "/usr/lib/python2.6/site-packages/neutronclient/v2_0/client.py", line 81, in exception_handler_v20
    message=error_dict)
neutronclient.common.exceptions.NeutronClientException: Request Failed: internal server error while processing your request.
```

```
[root@qa-centos-pool876 ~]# ip netns list
qdhcp-fff65b9c-78f8-445f-b27a-c7861a44e7cb
qdhcp-0551d2e2-9ffd-414e-9569-973f45be9983
vips
```

```
[root@qa-centos-pool876 ~]# cat /etc/neutron/neutron.conf 
[DEFAULT]
root_helper = sudo /usr/bin/neutron-rootwrap /etc/neutron/rootwrap.conf
debug = False
verbose = False
bind_host = 198.101.133.248
bind_port = 9696
core_plugin = neutron.plugins.openvswitch.ovs_neutron_plugin.OVSNeutronPluginV2
ovs_use_veth = True
allow_overlapping_ips = True
use_namespaces = True
api_paste_config = /etc/neutron/api-paste.ini
control_exchange = neutron
rabbit_host = 198.101.133.158
rabbit_ha_queues = true
rpc_backend = neutron.openstack.common.rpc.impl_kombu
notification_driver = neutron.openstack.common.notifier.rpc_notifier
notification_topics = notifications

service_plugins= neutron.services.loadbalancer.plugin.LoadBalancerPlugin

# keystone auth - this will cascade to all agents/services
auth_strategy = keystone
auth_url = http://198.101.133.159:35357/v2.0
auth_region = RegionOne
admin_tenant_name = service
admin_user = neutron
admin_password = 5sQFPncmZKwSueGnnkAj

# for now, these both need to be set to the same value
dhcp_lease_time = 1440
dhcp_lease_duration = 1440

# Seconds elapsed until an agent is considered down
agent_down_time = 30

[AGENT]
root_helper = sudo /usr/bin/neutron-rootwrap /etc/neutron/rootwrap.conf
polling_interval = 2

[QUOTAS]
# resource name(s) that are supported in quota features
quota_items = network,subnet,port
# default number of resource allowed per tenant, minus for unlimited
default_quota = -1
# number of networks allowed per tenant, and minus means unlimited
quota_network = 10
# number of subnets allowed per tenant, and minus means unlimited
quota_subnet = 10
# number of ports allowed per tenant, and minus means unlimited
quota_port = 50
# default driver to use for quota checks
quota_driver = neutron.db.quota_db.DbQuotaDriver

[SERVICE_PROVIDERS]
```

```
[root@qa-centos-pool876 ~]# cat /etc/rpcdaemon.conf
[Daemon]
# Space-separated list of plugins to load
# Available plugins: L3Agent, DHCPAgent, Dump
plugins = L3Agent DHCPAgent

# Rabbit server IP
rpchost = 198.101.133.158
pidfile = /var/run/rpcdaemon.pid
logfile = /var/log/rpcdaemon.log
loglevel = INFO

# How often to run plugin checks
check_interval = 1

[L3Agent]
conffile = /etc/neutron/neutron.conf
loglevel = INFO

# Max time for neutron API calls to complete -- also affects failover speed
timeout = 20
# Auto-terminate rabbit queues if no activity
queue_expire = 60

[DHCPAgent]
conffile = /etc/neutron/neutron.conf
loglevel = INFO

# Max time for neutron API calls to complete -- also affects failover speed
timeout = 20
# Auto-terminate rabbit queues if no activity
queue_expire = 60

[Dump]
# Only writes to DEBUG
loglevel = DEBUG
queue = neutron
```

```
[root@qa-centos-pool876 ~]# keystone endpoint-list
+----------------------------------+-----------+----------------------------------------------+----------------------------------------------+----------------------------------------------+----------------------------------+
|                id                |   region  |                  publicurl                   |                 internalurl                  |                   adminurl                   |            service_id            |
+----------------------------------+-----------+----------------------------------------------+----------------------------------------------+----------------------------------------------+----------------------------------+
| 17e54580050f42e58728dfe45277addd | RegionOne |         http://198.101.133.159:9292          |         http://198.101.133.159:9292          |         http://198.101.133.159:9292          | d154d55ea1ed4955bd35b10408c4a33a |
| 1eec5df1b169475c92f0d0ada0989df4 | RegionOne | http://198.101.133.208:8000/v1/$(tenant_id)s | http://198.101.133.208:8000/v1/$(tenant_id)s | http://198.101.133.208:8000/v1/$(tenant_id)s | 531d0c73c4524337ba459347afb5466d |
| 243227acbf80427b8cfa163baacac755 | RegionOne | http://198.101.133.159:8776/v1/%(tenant_id)s | http://198.101.133.159:8776/v1/%(tenant_id)s | http://198.101.133.159:8776/v1/%(tenant_id)s | d4d47f0a96c44bb68261e7e331a90944 |
| 43e46629f2c94147a930d666e1d12af5 | RegionOne |         http://198.101.133.159:9696          |         http://198.101.133.159:9696          |         http://198.101.133.159:9696          | 91edbab16929487caad8bcbfd3bc6dc2 |
| 5dd9ab4b13fc4ab5908fad6e6cdd5c21 | RegionOne |       http://198.101.133.159:5000/v2.0       |       http://198.101.133.159:5000/v2.0       |      http://198.101.133.159:35357/v2.0       | 1ce614caffc0449ab66b277333f5bb40 |
| b848a766b8f14be4ac159a65e1fd68b0 | RegionOne | http://198.101.133.159:8774/v2/%(tenant_id)s | http://198.101.133.159:8774/v2/%(tenant_id)s | http://198.101.133.159:8774/v2/%(tenant_id)s | e0c37480c2c844198d930217f512cd1a |
| c1496f17bb5f4ff7a3d33c2333d73611 | RegionOne |  http://198.101.133.159:8773/services/Cloud  |  http://198.101.133.159:8773/services/Admin  |  http://198.101.133.159:8773/services/Admin  | 9235bf7444fb4fc18f29d13607d2f398 |
| c24cef7f45cc46f5b905125b9be6700f | RegionOne |         http://198.101.133.159:8777          |         http://198.101.133.159:8777          |         http://198.101.133.159:8777          | 1ea463b660d54dfab623b5bebc917ae9 |
| ed82b92f616f41c3b1f5938a580ccd8a | RegionOne | http://198.101.133.208:8004/v1/$(tenant_id)s | http://198.101.133.208:8004/v1/$(tenant_id)s | http://198.101.133.208:8004/v1/$(tenant_id)s | a1a0fd4df8bd4446a32101df357bf24b |
+----------------------------------+-----------+----------------------------------------------+----------------------------------------------+----------------------------------------------+----------------------------------+
```

**Comment by jacobwagner** [comment]
seeing this on centos,w ill test soon on precise

**Comment by jacobwagner** [comment]
on the keystone-endpoint list, 198.101.133.208 is the IP of controller1, which is what i shutdown

159 is the ha-proxy vip

**Comment by jacobwagner** [comment]
Info on Precise

The router eventually got scheduled, leaving log for reference

```
2013-12-16 13:18:54  l3agent    WARNING  qa-precise-pool918/L3 agent [31a85013-1469-4f8a-8506-e4f5492e85c5]: is now down.
2013-12-16 13:18:54  l3agent    INFO     Removing router eee444bc-9145-4c74-bddd-68d7a21cec90 from qa-precise-pool918/L3 agent [31a85013-1469-4f8a-8506-e4f5492e85c5]
2013-12-16 13:19:14  l3agent    WARNING  Retry 1: 409-{u'NeutronError': {u'message': u'The router eee444bc-9145-4c74-bddd-68d7a21cec90 is not hosted by L3 agent 31a85013-1469-4f8a-8506-e4f5492e85c5.', u'type': u'RouterNotHostedByL3Agent', u'detail': u''}}
2013-12-16 13:19:17  l3agent    WARNING  Retry 2: 409-{u'NeutronError': {u'message': u'The router eee444bc-9145-4c74-bddd-68d7a21cec90 is not hosted by L3 agent 31a85013-1469-4f8a-8506-e4f5492e85c5.', u'type': u'RouterNotHostedByL3Agent', u'detail': u''}}
2013-12-16 13:19:20  l3agent    WARNING  Retry 3: 409-{u'NeutronError': {u'message': u'The router eee444bc-9145-4c74-bddd-68d7a21cec90 is not hosted by L3 agent 31a85013-1469-4f8a-8506-e4f5492e85c5.', u'type': u'RouterNotHostedByL3Agent', u'detail': u''}}
2013-12-16 13:19:23  l3agent    WARNING  Retry 4: 409-{u'NeutronError': {u'message': u'The router eee444bc-9145-4c74-bddd-68d7a21cec90 is not hosted by L3 agent 31a85013-1469-4f8a-8506-e4f5492e85c5.', u'type': u'RouterNotHostedByL3Agent', u'detail': u''}}
2013-12-16 13:19:26  l3agent    WARNING  Retry 5: 409-{u'NeutronError': {u'message': u'The router eee444bc-9145-4c74-bddd-68d7a21cec90 is not hosted by L3 agent 31a85013-1469-4f8a-8506-e4f5492e85c5.', u'type': u'RouterNotHostedByL3Agent', u'detail': u''}}
2013-12-16 13:19:29  l3agent    WARNING  Retry 6: 409-{u'NeutronError': {u'message': u'The router eee444bc-9145-4c74-bddd-68d7a21cec90 is not hosted by L3 agent 31a85013-1469-4f8a-8506-e4f5492e85c5.', u'type': u'RouterNotHostedByL3Agent', u'detail': u''}}
2013-12-16 13:19:32  l3agent    WARNING  Retry 7: 409-{u'NeutronError': {u'message': u'The router eee444bc-9145-4c74-bddd-68d7a21cec90 is not hosted by L3 agent 31a85013-1469-4f8a-8506-e4f5492e85c5.', u'type': u'RouterNotHostedByL3Agent', u'detail': u''}}
2013-12-16 13:19:35  l3agent    WARNING  Retry 8: 409-{u'NeutronError': {u'message': u'The router eee444bc-9145-4c74-bddd-68d7a21cec90 is not hosted by L3 agent 31a85013-1469-4f8a-8506-e4f5492e85c5.', u'type': u'RouterNotHostedByL3Agent', u'detail': u''}}
2013-12-16 13:19:38  l3agent    WARNING  Retry 9: 409-{u'NeutronError': {u'message': u'The router eee444bc-9145-4c74-bddd-68d7a21cec90 is not hosted by L3 agent 31a85013-1469-4f8a-8506-e4f5492e85c5.', u'type': u'RouterNotHostedByL3Agent', u'detail': u''}}
2013-12-16 13:19:41  l3agent    WARNING  Retry 10: 409-{u'NeutronError': {u'message': u'The router eee444bc-9145-4c74-bddd-68d7a21cec90 is not hosted by L3 agent 31a85013-1469-4f8a-8506-e4f5492e85c5.', u'type': u'RouterNotHostedByL3Agent', u'detail': u''}}
2013-12-16 13:19:44  l3agent    ERROR    Retries exhausted.  Exiting
2013-12-16 13:19:44  rpcdaemon  INFO     Stopping worker...
2013-12-16 13:19:49  rpcdaemon  WARNING  Error stopping worker. Shutting down uncleanly.
2013-12-16 13:19:49  rpcdaemon  INFO     Stopped.
Traceback (most recent call last):
  File "/usr/bin/rpcdaemon", line 9, in <module>
    load_entry_point('RPCDaemon==1.0.0', 'console_scripts', 'rpcdaemon')()
  File "/usr/lib/pymodules/python2.7/rpcdaemon/__init__.py", line 166, in main
    monitor.check()
  File "/usr/lib/pymodules/python2.7/rpcdaemon/__init__.py", line 145, in check
    plugin.check()
  File "/usr/lib/pymodules/python2.7/rpcdaemon/lib/neutronagent.py", line 151, in check
    self.handle(agent, False)
  File "/usr/lib/pymodules/python2.7/rpcdaemon/plugins/l3agent.py", line 83, in handle
    lambda: self.client.remove_router_from_l3_agent(agent['id'],
  File "/usr/lib/pymodules/python2.7/rpcdaemon/lib/neutronagent.py", line 186, in retryable
    on_fail(exc_info)
  File "/usr/lib/pymodules/python2.7/rpcdaemon/lib/neutronagent.py", line 176, in retryable
    result = fn()
  File "/usr/lib/pymodules/python2.7/rpcdaemon/plugins/l3agent.py", line 84, in <lambda>
    router['id']))
  File "/usr/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 108, in with_params
    ret = self.function(instance, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 966, in remove_router_from_l3_agent
    l3_agent, router_id))
  File "/usr/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 1179, in delete
    headers=headers, params=params)
  File "/usr/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 1168, in retry_request
    headers=headers, params=params)
  File "/usr/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 1111, in do_request
    self._handle_fault_response(status_code, replybody)
  File "/usr/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 1081, in _handle_fault_response
    exception_handler_v20(status_code, des_error_body)
  File "/usr/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 93, in exception_handler_v20
    message=msg)
neutronclient.common.exceptions.NeutronClientException: 409-{u'NeutronError': {u'message': u'The router eee444bc-9145-4c74-bddd-68d7a21cec90 is not hosted by L3 agent 31a85013-1469-4f8a-8506-e4f5492e85c5.', u'type': u'RouterNotHostedByL3Agent', u'detail': u''}}
2013-12-16 13:20:33  rpcdaemon  INFO     Initializing...
2013-12-16 13:20:33  rpcdaemon  INFO     Loading plugins...
2013-12-16 13:20:33  l3agent    INFO     Populating agents...
2013-12-16 13:20:33  dhcpagent  INFO     Populating agents...
2013-12-16 13:20:33  rpcdaemon  INFO     Starting worker...
2013-12-16 13:20:33  rpcdaemon  INFO     Started.
2013-12-16 13:20:33  l3agent    INFO     Scheduling router1 [eee444bc-9145-4c74-bddd-68d7a21cec90] -> qa-precise-pool935/L3 agent [f01c1ff0-6d65-493b-8179-97c8e50805fb].
2013-12-16 13:20:33  dhcpagent  INFO     Removing network 7a121430-98a7-423d-9e9f-d1f139f0732f from qa-precise-pool918/DHCP agent [f64a2761-4b4d-40fd-831b-b12a60f8142c]
```

```
root@qa-precise-pool935:~# tail -n 50 /var/log/neutron/server.log 
2013-12-16 13:19:29.817 17722 ERROR neutron.api.v2.resource [-] delete failed
2013-12-16 13:19:29.817 17722 TRACE neutron.api.v2.resource Traceback (most recent call last):
2013-12-16 13:19:29.817 17722 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/api/v2/resource.py", line 84, in resource
2013-12-16 13:19:29.817 17722 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2013-12-16 13:19:29.817 17722 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/extensions/l3agentscheduler.py", line 79, in delete
2013-12-16 13:19:29.817 17722 TRACE neutron.api.v2.resource     request.context, kwargs['agent_id'], id)
2013-12-16 13:19:29.817 17722 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/db/l3_agentschedulers_db.py", line 110, in remove_router_from_l3_agent
2013-12-16 13:19:29.817 17722 TRACE neutron.api.v2.resource     router_id=router_id, agent_id=agent_id)
2013-12-16 13:19:29.817 17722 TRACE neutron.api.v2.resource RouterNotHostedByL3Agent: The router eee444bc-9145-4c74-bddd-68d7a21cec90 is not hosted by L3 agent 31a85013-1469-4f8a-8506-e4f5492e85c5.
2013-12-16 13:19:29.817 17722 TRACE neutron.api.v2.resource 
2013-12-16 13:19:32.831 17722 ERROR neutron.api.v2.resource [-] delete failed
2013-12-16 13:19:32.831 17722 TRACE neutron.api.v2.resource Traceback (most recent call last):
2013-12-16 13:19:32.831 17722 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/api/v2/resource.py", line 84, in resource
2013-12-16 13:19:32.831 17722 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2013-12-16 13:19:32.831 17722 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/extensions/l3agentscheduler.py", line 79, in delete
2013-12-16 13:19:32.831 17722 TRACE neutron.api.v2.resource     request.context, kwargs['agent_id'], id)
2013-12-16 13:19:32.831 17722 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/db/l3_agentschedulers_db.py", line 110, in remove_router_from_l3_agent
2013-12-16 13:19:32.831 17722 TRACE neutron.api.v2.resource     router_id=router_id, agent_id=agent_id)
2013-12-16 13:19:32.831 17722 TRACE neutron.api.v2.resource RouterNotHostedByL3Agent: The router eee444bc-9145-4c74-bddd-68d7a21cec90 is not hosted by L3 agent 31a85013-1469-4f8a-8506-e4f5492e85c5.
2013-12-16 13:19:32.831 17722 TRACE neutron.api.v2.resource 
2013-12-16 13:19:35.846 17722 ERROR neutron.api.v2.resource [-] delete failed
2013-12-16 13:19:35.846 17722 TRACE neutron.api.v2.resource Traceback (most recent call last):
2013-12-16 13:19:35.846 17722 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/api/v2/resource.py", line 84, in resource
2013-12-16 13:19:35.846 17722 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2013-12-16 13:19:35.846 17722 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/extensions/l3agentscheduler.py", line 79, in delete
2013-12-16 13:19:35.846 17722 TRACE neutron.api.v2.resource     request.context, kwargs['agent_id'], id)
2013-12-16 13:19:35.846 17722 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/db/l3_agentschedulers_db.py", line 110, in remove_router_from_l3_agent
2013-12-16 13:19:35.846 17722 TRACE neutron.api.v2.resource     router_id=router_id, agent_id=agent_id)
2013-12-16 13:19:35.846 17722 TRACE neutron.api.v2.resource RouterNotHostedByL3Agent: The router eee444bc-9145-4c74-bddd-68d7a21cec90 is not hosted by L3 agent 31a85013-1469-4f8a-8506-e4f5492e85c5.
2013-12-16 13:19:35.846 17722 TRACE neutron.api.v2.resource 
2013-12-16 13:19:38.860 17722 ERROR neutron.api.v2.resource [-] delete failed
2013-12-16 13:19:38.860 17722 TRACE neutron.api.v2.resource Traceback (most recent call last):
2013-12-16 13:19:38.860 17722 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/api/v2/resource.py", line 84, in resource
2013-12-16 13:19:38.860 17722 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2013-12-16 13:19:38.860 17722 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/extensions/l3agentscheduler.py", line 79, in delete
2013-12-16 13:19:38.860 17722 TRACE neutron.api.v2.resource     request.context, kwargs['agent_id'], id)
2013-12-16 13:19:38.860 17722 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/db/l3_agentschedulers_db.py", line 110, in remove_router_from_l3_agent
2013-12-16 13:19:38.860 17722 TRACE neutron.api.v2.resource     router_id=router_id, agent_id=agent_id)
2013-12-16 13:19:38.860 17722 TRACE neutron.api.v2.resource RouterNotHostedByL3Agent: The router eee444bc-9145-4c74-bddd-68d7a21cec90 is not hosted by L3 agent 31a85013-1469-4f8a-8506-e4f5492e85c5.
2013-12-16 13:19:38.860 17722 TRACE neutron.api.v2.resource 
2013-12-16 13:19:41.874 17722 ERROR neutron.api.v2.resource [-] delete failed
2013-12-16 13:19:41.874 17722 TRACE neutron.api.v2.resource Traceback (most recent call last):
2013-12-16 13:19:41.874 17722 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/api/v2/resource.py", line 84, in resource
2013-12-16 13:19:41.874 17722 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2013-12-16 13:19:41.874 17722 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/extensions/l3agentscheduler.py", line 79, in delete
2013-12-16 13:19:41.874 17722 TRACE neutron.api.v2.resource     request.context, kwargs['agent_id'], id)
2013-12-16 13:19:41.874 17722 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/db/l3_agentschedulers_db.py", line 110, in remove_router_from_l3_agent
2013-12-16 13:19:41.874 17722 TRACE neutron.api.v2.resource     router_id=router_id, agent_id=agent_id)
2013-12-16 13:19:41.874 17722 TRACE neutron.api.v2.resource RouterNotHostedByL3Agent: The router eee444bc-9145-4c74-bddd-68d7a21cec90 is not hosted by L3 agent 31a85013-1469-4f8a-8506-e4f5492e85c5.
2013-12-16 13:19:41.874 17722 TRACE neutron.api.v2.resource 
```

```
root@qa-precise-pool935:~# ip netns list
qrouter-eee444bc-9145-4c74-bddd-68d7a21cec90
qdhcp-7a121430-98a7-423d-9e9f-d1f139f0732f
qdhcp-8d349188-39dd-42e5-9712-84df8674fa26
vips
```

```
root@qa-precise-pool935:~# cat /etc/rpcdaemon.conf
[Daemon]
# Space-separated list of plugins to load
# Available plugins: L3Agent, DHCPAgent, Dump
plugins = L3Agent DHCPAgent

# Rabbit server IP
rpchost = 198.101.133.155
pidfile = /var/run/rpcdaemon.pid
logfile = /var/log/rpcdaemon.log
loglevel = INFO

# How often to run plugin checks
check_interval = 1

[L3Agent]
conffile = /etc/neutron/neutron.conf
loglevel = INFO

# Max time for neutron API calls to complete -- also affects failover speed
timeout = 20
# Auto-terminate rabbit queues if no activity
queue_expire = 60

[DHCPAgent]
conffile = /etc/neutron/neutron.conf
loglevel = INFO

# Max time for neutron API calls to complete -- also affects failover speed
timeout = 20
# Auto-terminate rabbit queues if no activity
queue_expire = 60

[Dump]
# Only writes to DEBUG
loglevel = DEBUG
queue = neutron
```

```
root@qa-precise-pool935:~# cat /etc/neutron/neutron.conf 
[DEFAULT]
root_helper = sudo /usr/bin/neutron-rootwrap /etc/neutron/rootwrap.conf
debug = False
verbose = False
bind_host = 198.101.133.240
bind_port = 9696
core_plugin = neutron.plugins.openvswitch.ovs_neutron_plugin.OVSNeutronPluginV2
ovs_use_veth = False
allow_overlapping_ips = True
use_namespaces = True
api_paste_config = /etc/neutron/api-paste.ini
control_exchange = neutron
rabbit_host = 198.101.133.155
rabbit_ha_queues = true
rpc_backend = neutron.openstack.common.rpc.impl_kombu
notification_driver = neutron.openstack.common.notifier.rpc_notifier
notification_topics = notifications

service_plugins= neutron.services.loadbalancer.plugin.LoadBalancerPlugin

# keystone auth - this will cascade to all agents/services
auth_strategy = keystone
auth_url = http://198.101.133.156:35357/v2.0
auth_region = RegionOne
admin_tenant_name = service
admin_user = neutron
admin_password = hfON3nDgk9NuIsDZI_BM

# for now, these both need to be set to the same value
dhcp_lease_time = 1440
dhcp_lease_duration = 1440

# Seconds elapsed until an agent is considered down
agent_down_time = 30

[AGENT]
root_helper = sudo /usr/bin/neutron-rootwrap /etc/neutron/rootwrap.conf
polling_interval = 2

[QUOTAS]
# resource name(s) that are supported in quota features
quota_items = network,subnet,port
# default number of resource allowed per tenant, minus for unlimited
default_quota = -1
# number of networks allowed per tenant, and minus means unlimited
quota_network = 10
# number of subnets allowed per tenant, and minus means unlimited
quota_subnet = 10
# number of ports allowed per tenant, and minus means unlimited
quota_port = 50
# default driver to use for quota checks
quota_driver = neutron.db.quota_db.DbQuotaDriver

[SERVICE_PROVIDERS]
service_provider = LOADBALANCER:Haproxy:neutron.services.loadbalancer.drivers.haproxy.plugin_driver.HaproxyOnHostPluginDriver:default
```

**Comment by breu** [comment]
I cannot reproduce this on a clean install.

**Comment by jacobwagner** [comment]
This seems to have been a mysql split brain edge case issue. I am not able to reproduce either.
