### ISSUE TITLE
RPCDaemon after upgrade

### ISSUE THREAD

**Issue by cjoelrun** [rcbops/chef-cookbooks#732]
After an upgrade using cloudnull's db save/restore rpcdaemon has
already died:

`service rpcdaemon restart` gets things going

```
root@qa-precise-pool941:~# monit summary
The Monit daemon 5.3.2 uptime: 20m

Process 'rpcdaemon'                 Not monitored
Process 'rabbitmq-server'           Running
Process 'nova-scheduler'            Running
Process 'nova-novncproxy'           Data access error
Process 'nova-consoleauth'          Running
Process 'nova-conductor'            Running
Process 'nova-cert'                 Running
Process 'nova-api-os-compute'       Running
Process 'nova-api-ec2'              Running
Process 'neutron-server'            Running
Process 'neutron-metadata-agent'    Running
Process 'neutron-l3-agent'          Running
Process 'neutron-dhcp-agent'        Running
Process 'mysqld'                    Running
Process 'keystone'                  Running
Process 'glance-registry'           Running
Process 'glance-api'                Running
Process 'cinder-scheduler'          Running
Process 'cinder-api'                Running

2013-12-16 17:46:44  rpcdaemon  INFO     Initializing...
2013-12-16 17:46:44  rpcdaemon  INFO     Loading plugins...
2013-12-16 17:46:44  l3agent    INFO     Populating agents...
2013-12-16 17:46:44  dhcpagent  INFO     Populating agents...
2013-12-16 17:46:44  rpcdaemon  INFO     Starting worker...
2013-12-16 17:46:44  rpcdaemon  INFO     Started.
2013-12-16 17:46:44  l3agent    WARNING  Retry 1: Request Failed: internal server error while processing your request.
2013-12-16 17:46:47  l3agent    WARNING  Retry 2: Request Failed: internal server error while processing your request.
2013-12-16 17:46:50  l3agent    WARNING  Retry 3: Request Failed: internal server error while processing your request.
2013-12-16 17:46:53  l3agent    WARNING  Retry 4: Request Failed: internal server error while processing your request.
2013-12-16 17:46:56  l3agent    WARNING  Retry 5: Request Failed: internal server error while processing your request.
2013-12-16 17:46:59  l3agent    WARNING  Retry 6: Request Failed: internal server error while processing your request.
2013-12-16 17:47:02  l3agent    WARNING  Retry 7: Request Failed: internal server error while processing your request.
2013-12-16 17:47:05  l3agent    WARNING  Retry 8: Request Failed: internal server error while processing your request.
2013-12-16 17:47:08  l3agent    WARNING  Retry 9: Request Failed: internal server error while processing your request.
2013-12-16 17:47:11  l3agent    WARNING  Retry 10: Request Failed: internal server error while processing your request.
2013-12-16 17:47:14  l3agent    ERROR    Retries exhausted.  Exiting
2013-12-16 17:47:14  rpcdaemon  INFO     Stopping worker...
2013-12-16 17:47:19  rpcdaemon  WARNING  Error stopping worker. Shutting down uncleanly.
2013-12-16 17:47:19  rpcdaemon  INFO     Stopped.
Traceback (most recent call last):
  File "/usr/bin/rpcdaemon", line 9, in <module>
    load_entry_point('RPCDaemon==1.0.0', 'console_scripts', 'rpcdaemon')()
  File "/usr/lib/pymodules/python2.7/rpcdaemon/__init__.py", line 166, in main
    monitor.check()
  File "/usr/lib/pymodules/python2.7/rpcdaemon/__init__.py", line 145, in check
    plugin.check()
  File "/usr/lib/pymodules/python2.7/rpcdaemon/lib/neutronagent.py", line 165, in check
    self.handle(agent, True)
  File "/usr/lib/pymodules/python2.7/rpcdaemon/plugins/l3agent.py", line 90, in handle
    lambda: self.client.list_routers())['routers']
  File "/usr/lib/pymodules/python2.7/rpcdaemon/lib/neutronagent.py", line 186, in retryable
    on_fail(exc_info)
  File "/usr/lib/pymodules/python2.7/rpcdaemon/lib/neutronagent.py", line 176, in retryable
    result = fn()
  File "/usr/lib/pymodules/python2.7/rpcdaemon/plugins/l3agent.py", line 90, in <lambda>
    lambda: self.client.list_routers())['routers']
  File "/usr/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 108, in with_params
    ret = self.function(instance, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 378, in list_routers
    **_params)
  File "/usr/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 1197, in list
    for r in self._pagination(collection, path, **params):
  File "/usr/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 1210, in _pagination
    res = self.get(path, params=params)
  File "/usr/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 1183, in get
    headers=headers, params=params)
  File "/usr/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 1168, in retry_request
    headers=headers, params=params)
  File "/usr/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 1111, in do_request
    self._handle_fault_response(status_code, replybody)
  File "/usr/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 1081, in _handle_fault_response
    exception_handler_v20(status_code, des_error_body)
  File "/usr/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 81, in exception_handler_v20
    message=error_dict)
neutronclient.common.exceptions.NeutronClientException: Request Failed: internal server error while processing your request.
```

**Comment by breu** [comment]
@cjoelrun can you paste the stack trace from the neutron server.log?

**Comment by cjoelrun** [comment]
https://gist.github.com/7998109

**Comment by kaushikb** [comment]
@cjoelrun: Just remembered the conversation, have we updated the docs to indicate that RPC daemon has to be manually restarted post upgrade ?
