### ISSUE TITLE
[neutron] DHCP issues after Havana upgrade (from 4.1.2)

### ISSUE THREAD

**Issue by busterswt** [rcbops/chef-cookbooks#761]
Not sure if this happens every time, but David Wittman and I discovered that the quantum-ns-metadata-proxy processes can remain running in memory after an upgrade to Havana (4.2.1). This causes issues when Neutron also tries to bind to these interfaces, as indicated in the logs at /var/log/neutron/dhcp-agent.log:

2014-01-09 16:50:11.051 16885 ERROR neutron.agent.dhcp_agent [-] Unable to enable dhcp.
2014-01-09 16:50:11.051 16885 TRACE neutron.agent.dhcp_agent Traceback (most recent call last):
2014-01-09 16:50:11.051 16885 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/dist-packages/neutron/agent/dhcp_agent.py", line 126, in call_driver
2014-01-09 16:50:11.051 16885 TRACE neutron.agent.dhcp_agent     getattr(driver, action)(**action_kwargs)
2014-01-09 16:50:11.051 16885 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/dist-packages/neutron/agent/linux/dhcp.py", line 172, in enable
2014-01-09 16:50:11.051 16885 TRACE neutron.agent.dhcp_agent     self.spawn_process()
2014-01-09 16:50:11.051 16885 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/dist-packages/neutron/agent/linux/dhcp.py", line 362, in spawn_process
2014-01-09 16:50:11.051 16885 TRACE neutron.agent.dhcp_agent     ip_wrapper.netns.execute(cmd, addl_env=env)
2014-01-09 16:50:11.051 16885 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/dist-packages/neutron/agent/linux/ip_lib.py", line 458, in execute
2014-01-09 16:50:11.051 16885 TRACE neutron.agent.dhcp_agent     check_exit_code=check_exit_code)
2014-01-09 16:50:11.051 16885 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/dist-packages/neutron/agent/linux/utils.py", line 62, in execute
2014-01-09 16:50:11.051 16885 TRACE neutron.agent.dhcp_agent     raise RuntimeError(m)
2014-01-09 16:50:11.051 16885 TRACE neutron.agent.dhcp_agent RuntimeError:
2014-01-09 16:50:11.051 16885 TRACE neutron.agent.dhcp_agent Command: ['sudo', '/usr/bin/neutron-rootwrap', '/etc/neutron/rootwrap.conf', 'ip', 'netns', 'exec', 'qdhcp-e72fde6e-f35e-4d60-8bef-311d1f418871', 'env', 'NEUTRON_NETWORK_ID=e72fde6e-f35e-4d60-8bef-311d1f418871', 'dnsmasq', '--no-hosts', '--no-resolv', '--strict-order', '--bind-interfaces', '--interface=tapc8125b74-78', '--except-interface=lo', '--pid-file=/var/lib/neutron/dhcp/e72fde6e-f35e-4d60-8bef-311d1f418871/pid', '--dhcp-hostsfile=/var/lib/neutron/dhcp/e72fde6e-f35e-4d60-8bef-311d1f418871/host', '--dhcp-optsfile=/var/lib/neutron/dhcp/e72fde6e-f35e-4d60-8bef-311d1f418871/opts', '--leasefile-ro', '--dhcp-range=set:tag0,10.79.0.0,static,1440s', '--dhcp-lease-max=256', '--conf-file=', '--domain=openstacklocal']
2014-01-09 16:50:11.051 16885 TRACE neutron.agent.dhcp_agent Exit code: 2
2014-01-09 16:50:11.051 16885 TRACE neutron.agent.dhcp_agent Stdout: ''
2014-01-09 16:50:11.051 16885 TRACE neutron.agent.dhcp_agent Stderr: 'WARNING:root:Skipping unknown filter class (DnsmasqNetnsFilter) specified in filter definitions\nWARNING:root:Skipping unknown filter class (DnsmasqFilter) specified in filter definitions\nWARNING:root:Skipping unknown filter class (DnsmasqFilter) specified in filter definitions\n\ndnsmasq: failed to create listening socket for 169.254.169.254: Address already in use\n'

We were able to quickly resolve it by killing the old quantum processes off.

**Comment by DavidWittman** [comment]
Had the same issue on another 4.1.2 -> 4.2.1 upgrade today. Ubuntu 12.04.3.

```
# ps auxwww | grep quantu[m]
nobody     729  0.0  0.0  28824  1148 ?        S     2013   0:47 dnsmasq --no-hosts --no-resolv --strict-order --bind-interfaces --interface=tapf8d84175-a7 --except-interface=lo --pid-file=/var/lib/quantum/dhcp/5c40710e-52a3-43cc-99e4-c1ae1af01144/pid --dhcp-hostsfile=/var/lib/quantum/dhcp/5c40710e-52a3-43cc-99e4-c1ae1af01144/host --dhcp-optsfile=/var/lib/quantum/dhcp/5c40710e-52a3-43cc-99e4-c1ae1af01144/opts --dhcp-script=/usr/bin/quantum-dhcp-agent-dnsmasq-lease-update --leasefile-ro --dhcp-range=set:tag0,10.146.146.0,static,1440s --conf-file= --domain=openstacklocal
root       730  0.0  0.0  28796   464 ?        S     2013   0:28 dnsmasq --no-hosts --no-resolv --strict-order --bind-interfaces --interface=tapf8d84175-a7 --except-interface=lo --pid-file=/var/lib/quantum/dhcp/5c40710e-52a3-43cc-99e4-c1ae1af01144/pid --dhcp-hostsfile=/var/lib/quantum/dhcp/5c40710e-52a3-43cc-99e4-c1ae1af01144/host --dhcp-optsfile=/var/lib/quantum/dhcp/5c40710e-52a3-43cc-99e4-c1ae1af01144/opts --dhcp-script=/usr/bin/quantum-dhcp-agent-dnsmasq-lease-update --leasefile-ro --dhcp-range=set:tag0,10.146.146.0,static,1440s --conf-file= --domain=openstacklocal
nobody    1448  0.0  0.0  28824  1128 ?        S     2013   0:10 dnsmasq --no-hosts --no-resolv --strict-order --bind-interfaces --interface=tap2a7ab0e8-a9 --except-interface=lo --pid-file=/var/lib/quantum/dhcp/ae3f5987-1fa6-47ff-97ff-1732d07e8e91/pid --dhcp-hostsfile=/var/lib/quantum/dhcp/ae3f5987-1fa6-47ff-97ff-1732d07e8e91/host --dhcp-optsfile=/var/lib/quantum/dhcp/ae3f5987-1fa6-47ff-97ff-1732d07e8e91/opts --dhcp-script=/usr/bin/quantum-dhcp-agent-dnsmasq-lease-update --leasefile-ro --dhcp-range=set:tag0,10.240.112.0,static,1440s --conf-file= --domain=openstacklocal
root      1451  0.0  0.0  28796   468 ?        S     2013   0:09 dnsmasq --no-hosts --no-resolv --strict-order --bind-interfaces --interface=tap2a7ab0e8-a9 --except-interface=lo --pid-file=/var/lib/quantum/dhcp/ae3f5987-1fa6-47ff-97ff-1732d07e8e91/pid --dhcp-hostsfile=/var/lib/quantum/dhcp/ae3f5987-1fa6-47ff-97ff-1732d07e8e91/host --dhcp-optsfile=/var/lib/quantum/dhcp/ae3f5987-1fa6-47ff-97ff-1732d07e8e91/opts --dhcp-script=/usr/bin/quantum-dhcp-agent-dnsmasq-lease-update --leasefile-ro --dhcp-range=set:tag0,10.240.112.0,static,1440s --conf-file= --domain=openstacklocal
root      8607  0.0  0.0  94324 23744 ?        S     2013   0:03 python /usr/bin/quantum-ns-metadata-proxy --pid_file=/var/lib/quantum/external/pids/70a88e39-1172-4228-96ed-9d6b9b7ca8a7.pid --network_id=70a88e39-1172-4228-96ed-9d6b9b7ca8a7 --state_path=/var/lib/quantum --metadata_port=80 --log-file=quantum-ns-metadata-proxy70a88e39-1172-4228-96ed-9d6b9b7ca8a7.log --log-dir=/var/log/quantum
root      9512  0.0  0.0  94320 23760 ?        S     2013   0:03 python /usr/bin/quantum-ns-metadata-proxy --pid_file=/var/lib/quantum/external/pids/5c40710e-52a3-43cc-99e4-c1ae1af01144.pid --network_id=5c40710e-52a3-43cc-99e4-c1ae1af01144 --state_path=/var/lib/quantum --metadata_port=80 --log-file=quantum-ns-metadata-proxy5c40710e-52a3-43cc-99e4-c1ae1af01144.log --log-dir=/var/log/quantum
root     11239  0.0  0.0  94316 23744 ?        S     2013   0:03 python /usr/bin/quantum-ns-metadata-proxy --pid_file=/var/lib/quantum/external/pids/ae3f5987-1fa6-47ff-97ff-1732d07e8e91.pid --network_id=ae3f5987-1fa6-47ff-97ff-1732d07e8e91 --state_path=/var/lib/quantum --metadata_port=80 --log-file=quantum-ns-metadata-proxyae3f5987-1fa6-47ff-97ff-1732d07e8e91.log --log-dir=/var/log/quantum
nobody   31888  0.0  0.0  28824  1144 ?        S     2013   0:21 dnsmasq --no-hosts --no-resolv --strict-order --bind-interfaces --interface=tapdc437a46-c7 --except-interface=lo --pid-file=/var/lib/quantum/dhcp/70a88e39-1172-4228-96ed-9d6b9b7ca8a7/pid --dhcp-hostsfile=/var/lib/quantum/dhcp/70a88e39-1172-4228-96ed-9d6b9b7ca8a7/host --dhcp-optsfile=/var/lib/quantum/dhcp/70a88e39-1172-4228-96ed-9d6b9b7ca8a7/opts --dhcp-script=/usr/bin/quantum-dhcp-agent-dnsmasq-lease-update --leasefile-ro --dhcp-range=set:tag0,10.100.100.0,static,1440s --conf-file= --domain=openstacklocal
root     31889  0.0  0.0  28796   464 ?        S     2013   0:17 dnsmasq --no-hosts --no-resolv --strict-order --bind-interfaces --interface=tapdc437a46-c7 --except-interface=lo --pid-file=/var/lib/quantum/dhcp/70a88e39-1172-4228-96ed-9d6b9b7ca8a7/pid --dhcp-hostsfile=/var/lib/quantum/dhcp/70a88e39-1172-4228-96ed-9d6b9b7ca8a7/host --dhcp-optsfile=/var/lib/quantum/dhcp/70a88e39-1172-4228-96ed-9d6b9b7ca8a7/opts --dhcp-script=/usr/bin/quantum-dhcp-agent-dnsmasq-lease-update --leasefile-ro --dhcp-range=set:tag0,10.100.100.0,static,1440s --conf-file= --domain=openstacklocal
```

**Comment by breu** [comment]
we need to kill the quantum-ns-metadata-proxy process during upgrade.  need to determine if this is an upstream problem or something that we need to doc in the upgrade docs.

**Comment by breu** [comment]
@jrcloud let's fix this in the nova-network cookbook

**Comment by zfeldstein** [comment]
Fixed in here: 

https://github.com/rcbops-cookbooks/nova-network/commit/31a53c4683c4a058d108ca7e9eed18838fca799f

**Comment by claco** [comment]
Re-open for QE confirmation.
