### ISSUE TITLE
[rpcdaemon] failover issues w/ OVS and L3 Agent

### ISSUE THREAD

**Issue by busterswt** [rcbops/chef-cookbooks#790]
In two separate environments (new builds), we are experiencing odd issues after failing over the VIPs. A single failover from one controller to another may work as expected, but subsequent failovers do not. The symptoms appear to be:

loss of DHCP taps in 'ovs-vsctl show' output
loss of corresponding flows
router may not get scheduled to either agent
router taps (qg/qr) may exist with no tags or flows
stale taps in 'ovs-vsctl show' that MAY exist in the DHCP namespace with valid taps

Note: the vips namespace and failover of vip IPs works consistently ALWAYS.

Also note, both were deployed with the network "retrofit". However, one environment does have split mgmt and data NICs, while the other environment is on a single NIC.

---

Here are some tests I performed on both environments over the last two days. Results were similar. 

!!!!!TEST:
root@558516-controller02:~# ip netns exec qdhcp-bae934cc-8a2d-4662-ae56-e70b29ca8d08 ping 10.239.0.1
root@558513-controller01:~# ip netns exec qdhcp-bae934cc-8a2d-4662-ae56-e70b29ca8d08 ping 10.239.0.1
root@558513-controller01:~# ip netns exec qrouter-86ec1122-477d-465e-81e0-b14d044ed53d ping 10.239.0.1

Test notes:
At this point, both sides seem stable. controller01 has the vips and the router. both controllers can ping the external gateway from their dhcp namespaces. ping from router
namespace is good. Agent-list looks healthy. Looking at agents, the router is bound to controller01:

(neutron)  agent-show 3eefc9fb-b984-4d79-a240-29eadc158453 (controller01)
|                     |      "routers": 1,  
(neutron) agent-show f60442f7-cb39-41b8-b5f7-f9675b73f22a  (controller02)  
|                     |      "routers": 0,   

!!!!!TEST: failover from controller01 -> 02
service keepalived restart 

Notes:
Vips failed over properly. taps were created and have flows. ICMP test looks good from each controller in the DHCP and router namespace (controller02).

!!!!!TEST: Fail back over from controller02 -> 01
service keepalived restart 

Notes:

Controller01 is missing the router taps. DHCP tap exists and appears to work properly.

*\* rpcdaemon on controller01 says:
2014-02-07 14:37:19  l3agent    INFO     Scheduling RTR-PUBLIC [86ec1122-477d-465e-81e0-b14d044ed53d] -> 558516-controller02/L3 agent [f60442f7-cb39-41b8-b5f7-f9675b73f22a].

*\* rpcdaemon on controller02 says:
==> /var/log/rpcdaemon.log <==
2014-02-07 14:37:19  l3agent    INFO     Removing router 86ec1122-477d-465e-81e0-b14d044ed53d from 558516-controller02/L3 agent [f60442f7-cb39-41b8-b5f7-f9675b73f22a]
2014-02-07 14:37:20  l3agent    WARNING  No agents found to schedule routers to.
2014-02-07 14:37:20  l3agent    WARNING  No agents found to schedule routers to.
2014-02-07 14:37:21  l3agent    WARNING  558516-controller02/L3 agent [f60442f7-cb39-41b8-b5f7-f9675b73f22a]: is now up.
2014-02-07 14:37:21  l3agent    WARNING  558513-controller01/L3 agent [3eefc9fb-b984-4d79-a240-29eadc158453]: is now up.
2014-02-07 14:37:23  dhcpagent  WARNING  558513-controller01/DHCP agent [9f34d83d-947f-433a-9f09-e49033c6b6c3]: is now up.
2014-02-07 14:37:23  dhcpagent  WARNING  558516-controller02/DHCP agent [098cf17c-016b-438c-8221-25c8a8bc75f3]: is now up.

*\* server.log on controller01 says:
==> /var/log/neutron/server.log <==
2014-02-07 14:37:19.851 2017 WARNING neutron.scheduler.l3_agent_scheduler [-] L3 agent f60442f7-cb39-41b8-b5f7-f9675b73f22a is not active
2014-02-07 14:37:19.871 2017 ERROR neutron.openstack.common.rpc.common [-] Failed to publish message to topic 'l3_agent.558516-controller02': Socket closed
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common Traceback (most recent call last):
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/neutron/openstack/common/rpc/impl_kombu.py", line 561, in ensure
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common     return method(_args, *_kwargs)
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/neutron/openstack/common/rpc/impl_kombu.py", line 672, in _publish
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common     publisher = cls(self.conf, self.channel, topic, **kwargs)
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/neutron/openstack/common/rpc/impl_kombu.py", line 348, in __init__
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common     **options)
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/neutron/openstack/common/rpc/impl_kombu.py", line 295, in **init**
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common     self.reconnect(channel)
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/neutron/openstack/common/rpc/impl_kombu.py", line 303, in reconnect
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common     routing_key=self.routing_key)
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/kombu/messaging.py", line 83, in **init**
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common     self.revive(self._channel)
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/kombu/messaging.py", line 214, in revive
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common     self.declare()
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/kombu/messaging.py", line 100, in declare
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common     self.exchange.declare()
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/kombu/entity.py", line 162, in declare
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common     nowait=nowait, passive=passive,
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/amqp/channel.py", line 603, in exchange_declare
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common     (40, 11),  # Channel.exchange_declare_ok
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/amqp/abstract_channel.py", line 69, in wait
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common     self.channel_id, allowed_methods)
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/amqp/connection.py", line 204, in _wait_method
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common     self.method_reader.read_method()
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/amqp/method_framing.py", line 187, in read_method
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common     raise m
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common IOError: Socket closed
2014-02-07 14:37:19.871 2017 TRACE neutron.openstack.common.rpc.common

*\* server.log on controller02 says:
==> /var/log/neutron/server.log <==
2014-02-07 14:37:19.867 2151 ERROR neutron.openstack.common.rpc.common [-] Failed to publish message to topic 'l3_agent.558516-controller02': [Errno 104] Connection reset by peer
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common Traceback (most recent call last):
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/neutron/openstack/common/rpc/impl_kombu.py", line 561, in ensure
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common     return method(_args, *_kwargs)
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/neutron/openstack/common/rpc/impl_kombu.py", line 672, in _publish
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common     publisher = cls(self.conf, self.channel, topic, **kwargs)
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/neutron/openstack/common/rpc/impl_kombu.py", line 348, in __init__
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common     **options)
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/neutron/openstack/common/rpc/impl_kombu.py", line 295, in **init**
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common     self.reconnect(channel)
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/neutron/openstack/common/rpc/impl_kombu.py", line 303, in reconnect
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common     routing_key=self.routing_key)
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/kombu/messaging.py", line 83, in **init**
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common     self.revive(self._channel)
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/kombu/messaging.py", line 214, in revive
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common     self.declare()
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/kombu/messaging.py", line 100, in declare
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common     self.exchange.declare()
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/kombu/entity.py", line 162, in declare
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common     nowait=nowait, passive=passive,
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/amqp/channel.py", line 595, in exchange_declare
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common     self._send_method((40, 10), args)
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/amqp/abstract_channel.py", line 58, in _send_method
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common     self.channel_id, method_sig, args, content,
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/amqp/method_framing.py", line 219, in write_method
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common     write_frame(1, channel, payload)
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/amqp/transport.py", line 159, in write_frame
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common     pack('>BHI%dsB' % size, frame_type, channel, size, payload, 0xce),
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/eventlet/greenio.py", line 307, in sendall
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common     tail = self.send(data, flags)
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common   File "/usr/lib/python2.7/dist-packages/eventlet/greenio.py", line 293, in send
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common     total_sent += fd.send(data[total_sent:], flags)
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common error: [Errno 104] Connection reset by peer
2014-02-07 14:37:19.867 2151 TRACE neutron.openstack.common.rpc.common

Looking at the agents, neither one owns the router:

root@558516-controller02:~# neutron agent-show f60442f7-cb39-41b8-b5f7-f9675b73f22a
| admin_state_up      | True                                                                          |
|                     |      "routers": 0,                                                            |

root@558516-controller02:~# neutron agent-show 3eefc9fb-b984-4d79-a240-29eadc158453
| admin_state_up      | True                                                                          |
|                     |      "routers": 0,                                                            |

!!!!!TEST: Stop rpc daemon and get everything back in working order.
monit stop rpcdaemon
pkill dnsmasq; pkill -f ns-metadata-proxy; restart neutron-plugin-openvswitch-agent; restart neutron-dhcp-agent; restart neutron-metadata-agent; restart neutron-l3-agent;

Notes:
Controller02 - taps w/ tags. dhcp and router namespace pings 10.239.0.1
Controller01 - i see taps and tags, but unable to ping.
Restarted all neutron agents, openvswitch and neutron-server. this was the error in openvswitch-agent.log upon restart:

2014-02-07 20:34:57.451 4945 ERROR neutron.openstack.common.rpc.amqp [-] Exception during message handling
2014-02-07 20:34:57.451 4945 TRACE neutron.openstack.common.rpc.amqp Traceback (most recent call last):
2014-02-07 20:34:57.451 4945 TRACE neutron.openstack.common.rpc.amqp   File "/usr/lib/python2.7/dist-packages/neutron/openstack/common/rpc/amqp.py", line 438, in _process_data
2014-02-07 20:34:57.451 4945 TRACE neutron.openstack.common.rpc.amqp     *_args)
2014-02-07 20:34:57.451 4945 TRACE neutron.openstack.common.rpc.amqp   File "/usr/lib/python2.7/dist-packages/neutron/openstack/common/rpc/dispatcher.py", line 172, in dispatch
2014-02-07 20:34:57.451 4945 TRACE neutron.openstack.common.rpc.amqp     result = getattr(proxyobj, method)(ctxt, *_kwargs)
2014-02-07 20:34:57.451 4945 TRACE neutron.openstack.common.rpc.amqp   File "/usr/lib/python2.7/dist-packages/neutron/plugins/openvswitch/agent/ovs_neutron_agent.py", line 290, in port_update
2014-02-07 20:34:57.451 4945 TRACE neutron.openstack.common.rpc.amqp     self.sg_agent.refresh_firewall()
2014-02-07 20:34:57.451 4945 TRACE neutron.openstack.common.rpc.amqp AttributeError: 'NoneType' object has no attribute 'refresh_firewall'
2014-02-07 20:34:57.451 4945 TRACE neutron.openstack.common.rpc.amqp

In addition, the DHCP namespace has a stale tap (tap14409c5b-0a):

root@558513-controller01:/etc/init.d# ip netns exec qdhcp-bae934cc-8a2d-4662-ae56-e70b29ca8d08 ip a
18: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
41: tap14409c5b-0a: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN
    link/ether fa:16:3e:24:92:85 brd ff:ff:ff:ff:ff:ff
    inet 10.239.0.13/22 brd 10.239.3.255 scope global tap14409c5b-0a
    inet 169.254.169.254/16 brd 169.254.255.255 scope global tap14409c5b-0a
    inet6 fe80::f816:3eff:fe24:9285/64 scope link
       valid_lft forever preferred_lft forever
42: tape4c5c041-6f: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN
    link/ether fa:16:3e:07:d5:90 brd ff:ff:ff:ff:ff:ff
    inet 10.239.0.13/22 brd 10.239.3.255 scope global tape4c5c041-6f
    inet 169.254.169.254/16 brd 169.254.255.255 scope global tape4c5c041-6f
    inet6 fe80::f816:3eff:fe07:d590/64 scope link
       valid_lft forever preferred_lft forever

Bridge br-int
        Port "tap5b7e5839-ef"
            tag: 1
            Interface "tap5b7e5839-ef"
                type: internal
        Port br-int
            Interface br-int
                type: internal
        Port "int-br-bond0"
            Interface "int-br-bond0"
        Port patch-tun
            Interface patch-tun
                type: patch
                options: {peer=patch-int}
        Port "tap14409c5b-0a"
            tag: 4095
            Interface "tap14409c5b-0a"
                type: internal
        Port "tape4c5c041-6f"
            tag: 2
            Interface "tape4c5c041-6f"
                type: internal

So, I deleted the tap from the bridge:
root@558513-controller01:/etc/init.d# ovs-vsctl del-port br-int tap14409c5b-0a

And now ping works:
root@558513-controller01:/etc/init.d# ip netns exec qdhcp-bae934cc-8a2d-4662-ae56-e70b29ca8d08 ping 10.239.0.1
PING 10.239.0.1 (10.239.0.1) 56(84) bytes of data.
64 bytes from 10.239.0.1: icmp_req=1 ttl=255 time=0.944 ms
64 bytes from 10.239.0.1: icmp_req=2 ttl=255 time=0.279 ms

!!!!! TEST: failover again after disabling rpcdaemon
service keepalived restart (on controller01 - active)

Notes:
Controller01 - dhcp taps w/ tags. can ping the GW 10.239.0.1
Controller02 (now active) - dhcp taps w/ tags. can ping the GW 10.239.0.1. Router NS can also ping the GW.

!!!!! TEST: failover again
service keepalived restart (on controler02 - active)

Controller01 (now active)- dhcp taps w/ tags. can ping the GW 10.239.0.1
Controller02 - dhcp taps w/ tags. can ping the GW 10.239.0.1. ROUTER STILL EXISTS ON CONTROLLER02 - and it can ping GW

!!!!! TEST: failover again
service keepalived restart (on controler01 - active)

Notes:
Controller01 - dhcp taps w/ tags. can ping the GW 10.239.0.1
Controller02 (now active) - dhcp taps w/ tags. can ping the GW 10.239.0.1. Router NS can also ping the GW.

---

It would appear disabling rpcdaemon resolves the issues related to OVS/L3 agent during a failover event as the router and dhcp aren't being rescheduled. Please let me know if you need more info.

James Denton
Network Engineer
Rackspace Private Cloud

**Comment by IRTermite** [comment]
https://github.com/rsoprivatecloud/rpc-support/pull/64#issuecomment-34895290

**Comment by claco** [comment]
Fixed in https://github.com/rcbops-cookbooks/nova-network/commit/10318fbc86f9af966923747e4e3da994fd3ed0a4 and also ported to v4.2.2rc in https://github.com/rcbops-cookbooks/nova-network/commit/f8c3684e2d3a570ad7f430893f0ff2282546c2de

**Comment by JCallicoat** [comment]
Backport to v4.1.4 pl0x!

**Comment by claco** [comment]
@JCallicoat It's already backported into 4.1.5rc, which will drop in about 30 days. 4.1.4 was tagged, and never released, but this fix was after that anyhow.
