### ISSUE TITLE
[ceilometer/horizon] Resource Usage in Horizon Dashboard Not Working

### ISSUE THREAD

**Issue by jameswthorne** [rcbops/chef-cookbooks#799]
When going to the **Resource Usage** link under the **Admin** tab in the Horizon Dashboard it displays the **Something went wrong!** message.

**/var/log/ceilometer/ceilometer-api.log** on the controller node logs the following error when the **Resource Usage** link is accessed:

```
2014-02-19 13:36:55.235 8753 ERROR wsme.api [-] Server-side error: "metaquery not implemented". Detail:
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/wsmeext/pecan.py", line 72, in callfunction
    result = f(self, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/ceilometer/api/controllers/v2.py", line 965, in get_all
    for r in pecan.request.storage_conn.get_resources(**kwargs)]

  File "/usr/lib/python2.7/dist-packages/ceilometer/storage/impl_sqlalchemy.py", line 310, in get_resources
    raise NotImplementedError(_('metaquery not implemented'))

NotImplementedError: metaquery not implemented
```

This issue was brought to my attention at the following RPC Community Forum thread and appears to affect RPC v4.2.1 which also affects the RPC Sandbox:

https://community.rackspace.com/products/f/45/p/3260/8411#8411

This looks to be related to this bug:

https://bugs.launchpad.net/ceilometer/+bug/1093625

Which appears to have been fixed here:

https://review.openstack.org/#/c/49456/

However, running either of the following commands shows the commit fixing the issue does not exist in any of our branches or tags:

```
git branch -a --contains 1570462507eae1478123de25dbadc64b09c82af3

git tag --contains 1570462507eae1478123de25dbadc64b09c82af3
```

**Comment by cloudnull** [comment]
We are carrying a patch for this issue in the cookbooks "https://github.com/rcbops-cookbooks/ceilometer/commit/383c509cbc7b246c5b034e647cacc03d3198f1df" which supports both redhat and ubuntu. Recently the cloud archive repo was updated with a few new packages so this is likely related to new packages. I will look into this and figure out where the break down is.

**Comment by jacobwagner** [comment]
```
root@node98:~# uname -a
Linux node98.sat6.lab 3.8.0-37-generic #53~precise1-Ubuntu SMP Wed Feb 19 21:37:54 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
root@node98:~# dpkg -l | grep ceil
ii  ceilometer-agent-central             2013.2.2-0ubuntu1~cloud0                            ceilometer central agent
ii  ceilometer-api                       2013.2.2-0ubuntu1~cloud0                            ceilometer api service
ii  ceilometer-collector                 2013.2.2-0ubuntu1~cloud0                            ceilometer collector service
ii  ceilometer-common                    2013.2.2-0ubuntu1~cloud0                            ceilometer common files
ii  python-ceilometer                    2013.2.2-0ubuntu1~cloud0                            ceilometer python libraries
ii  python-ceilometerclient              1.0.5-0ubuntu1~cloud0                               Client library for Openstack ceilometer server.

root@node98:~# ceilometer resource-list

==> /var/log/ceilometer/ceilometer-api.log <==
2014-03-12 20:33:05.472 1905 ERROR wsme.api [-] Server-side error: "'module' object has no attribute 'ResourceMeter'". Detail: 
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/wsmeext/pecan.py", line 72, in callfunction
    result = f(self, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/ceilometer/api/controllers/v2.py", line 968, in get_all
    for r in pecan.request.storage_conn.get_resources(**kwargs)]

  File "/usr/lib/python2.7/dist-packages/ceilometer/storage/impl_sqlalchemy.py", line 439, in get_resources
    for m in meter.resource.meters

AttributeError: 'module' object has no attribute 'ResourceMeter'

No handlers could be found for logger "ceilometerclient.common.http"
HTTPInternalServerError (HTTP 500)
```

**Comment by claco** [comment]
This seems related to this maybe, not sure yet. @cloudnull 

https://github.com/openstack/ceilometer/commit/7c4c0e8fc098fbadec2e30ea2bdf1068b5b4288a
https://bugs.launchpad.net/ceilometer/+bug/1267162

So we need to update our patch maybe, or maybe not needed at all.

@rackerjoe @cloudnull Why did we add two versions in https://github.com/rcbops-cookbooks/ceilometer/commit/5313fecc4dada0603a654e4b4ddd6ec1783c799b

Was that pre 2013.2.2? @jacobwagner What just dropped for the dbsync fix?

**Comment by breu** [comment]
@claco 2013.2.1-0ubuntu2~cloud0 was already there.  I added 2013.2.2-0ubuntu1~cloud0 and a , behind 2013.2.1-0ubuntu2~cloud0.

**Comment by xeregin** [comment]
![shot-2014-03-13_13-39-57](https://f.cloud.github.com/assets/2779091/2413507/193da65c-aadf-11e3-910b-94ecd5d895f2.png)

This is now working. I will close this issue.

**Comment by git-harry** [comment]
This doesn't appear to be fixed. I still see get:

2014-03-21 10:35:03.376 709 ERROR wsme.api [-] Server-side error: "'module' object has no attribute 'ResourceMeter'". Detail:
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/wsmeext/pecan.py", line 72, in callfunction
    result = f(self, _args, *_kwargs)

  File "/usr/lib/python2.7/dist-packages/ceilometer/api/controllers/v2.py", line 968, in get_all
    for r in pecan.request.storage_conn.get_resources(**kwargs)]

  File "/usr/lib/python2.7/dist-packages/ceilometer/storage/impl_sqlalchemy.py", line 439, in get_resources
    for m in meter.resource.meters

AttributeError: 'module' object has no attribute 'ResourceMeter'

By the looks of it the following lines of code need to be removed.
https://github.com/rcbops-cookbooks/ceilometer/blob/master/templates/default/patches/impl_sqlalchemy.py.erb#L433-L440

**Comment by claco** [comment]
Even without the error, we're short 2 tabs, included here for visual reference:

![image](https://f.cloud.github.com/assets/20319/2484480/fc27b438-b10d-11e3-8653-4f06442fb33e.png)
![image](https://f.cloud.github.com/assets/20319/2484482/054597c4-b10e-11e3-8e75-6a2d3c83f987.png)
![image](https://f.cloud.github.com/assets/20319/2484485/0dd1aea0-b10e-11e3-8615-c85a21e0cc93.png)

**Comment by claco** [comment]
After @cloudnull digging, I t appears that these tabs went all removed in havana 2.1 upstream. Updating the patch to stop the exception for now that ResourceMeter class is gone.

Remove here-ish? https://bugs.launchpad.net/horizon/+bug/1249279

**Comment by breu** [comment]
Nice catch

**Comment by jameswthorne** [comment]
Quick update, I spun up a CentOS 6.5 RPC v.4.2.2rc environment today and the Horizon Resource Usage pane loads and the ceilometer commands run without error, but no data is returned from either because ceilometer cannot connect to the rabbitmq-server service even though all the other OpenStack services can:

```
==> /var/log/ceilometer/central.log <==
2014-03-27 11:34:56.737 20979 ERROR ceilometer.openstack.common.rpc.impl_qpid [-] Unable to connect to AMQP server: [Errno 111] ECONNREFUSED. Sleeping 60 seconds

==> /var/log/ceilometer/collector.log <==
2014-03-27 11:34:57.265 20994 ERROR ceilometer.openstack.common.rpc.impl_qpid [-] Unable to connect to AMQP server: [Errno 111] ECONNREFUSED. Sleeping 60 seconds
```

**Comment by jacobwagner** [comment]
I am building a 6.4 build right now i will see if i see it as well

**Comment by jameswthorne** [comment]
I'm in the process of spinning up a Ubuntu Server 12.04.3 LTS RPC v4.2.2rc environment to test on. Will report back soon.

**Comment by jacobwagner** [comment]
6.4 is seeing this as well

**Comment by jacobwagner** [comment]
This is a configuration error

we are missing the following 2 variables in ceilometer.conf

```
##### RABBITMQ #####
rpc_backend=ceilometer.openstack.common.rpc.impl_kombu
control_exchange=ceilometer
```

**Comment by jacobwagner** [comment]
```
[root@node112-sat6-lab ~]# cat /usr/share/ceilometer/ceilometer-dist.conf 
[DEFAULT]
log_dir = /var/log/ceilometer
rpc_backend = ceilometer.openstack.common.rpc.impl_qpid

[database]
connection = mongodb://localhost:27017/ceilometer
```

This is in relation to redhat doing there own confs

Kevin said we ran into this issue with neutron so we just wiped the above file out and put it in our conf

**Comment by jameswthorne** [comment]
This doesn't appear to be a problem in Ubuntu Server 12.04.3 LTS.

The ceilometer commands return output and there are no "Unable to connect" messages in the ceilometer logs.

I am still getting **No data available** in the Horizon Resource Usage pane, but that may be because I haven't let the environment run long enough.

**Comment by jameswthorne** [comment]
Another update, in Ubuntu Server 12.04.3 LTS the Horizon Resource Usage pane is now showing graph data after letting the environment run for a while with an instance running.

**Comment by cloudnull** [comment]
Closing the issue as this is now fixed. But feel free to reopen or create a new one if something else decides to break with ceilometer.

**Comment by claco** [comment]
You no close when I close. :-) Reopening pending backport/submodule confirmation.

**Comment by jacobwagner** [comment]
Verified Fixed

```
##### RABBITMQ #####
rpc_backend=ceilometer.openstack.common.rpc.impl_kombu
control_exchange=ceilometer

rabbit_password=guest
rabbit_hosts=10.127.101.69:5672
rabbit_ha_queues=True

notification_driver = ceilometer.openstack.common.notifier.no_op_notifier
notification_topics = notifications
```

```
2014-03-28 08:38:42.777 5698 ERROR ceilometer.openstack.common.rpc.impl_qpid [-] Unable to connect to AMQP server: [Errno 111] ECONNREFUSED. Sleeping 60 seconds
2014-03-28 08:39:19.917 5698 INFO ceilometer.openstack.common.service [-] Caught SIGTERM, exiting
2014-03-28 08:39:20.557 5174 INFO ceilometer.openstack.common.rpc.common [-] Connected to AMQP server on 10.127.101.69:5672
2014-03-28 08:39:20.583 5174 INFO ceilometer.pipeline [-] Pipeline config: [{'meters': ['*'], 'interval': 600, 'transformers': None, 'name': 'meter_pipeline', 'publishers': ['rpc://']}, {'meters': ['cpu'], 'interval': 600, 'transformers': [{'name': 'rate_of_change', 'parameters': {'target': {'scale': '100.0 / (10**9 * (resource_metadata.cpu_number or 1))', 'type': 'gauge', 'name': 'cpu_util', 'unit': '%'}}}], 'name': 'cpu_pipeline', 'publishers': ['rpc://']}]
2014-03-28 08:39:20.584 5174 WARNING ceilometer.publisher.rpc [-] Publishing policy is unknown (wait) force to default
2014-03-28 08:39:20.584 5174 WARNING ceilometer.publisher.rpc [-] Publishing policy is unknown (wait) force to default
2014-03-28 08:39:20.584 5174 INFO ceilometer.pipeline [-] Pipeline cpu_pipeline: Setup transformer instance rate_of_change with parameter {'target': {'scale': '100.0 / (10**9 * (resource_metadata.cpu_number or 1))', 'type': 'gauge', 'name': 'cpu_util', 'unit': '%'}}
```
