### ISSUE TITLE
libvirt issue on Havanna using QEMU on public cloud

### ISSUE THREAD

**Issue by xeregin** [rcbops/chef-cookbooks#809]
Controller: > nova boot --image cirros-image --flavor 4 iantester

```
ERROR: The requested availability zone is not available (HTTP 400) (Request-ID: req-ce3191f1-ae84-42af-97f0-c35d2e1c6a63)
```

Controller: > nova service-list

```
+------------------+-----------------+----------+---------+-------+----------------------------+-----------------+
| Binary           | Host            | Zone     | Status  | State | Updated_at                 | Disabled Reason |
+------------------+-----------------+----------+---------+-------+----------------------------+-----------------+
| nova-scheduler   | ian-controller  | internal | enabled | up    | 2014-02-27T02:50:02.000000 | None            |
| nova-conductor   | ian-controller  | internal | enabled | up    | 2014-02-27T02:50:02.000000 | None            |
| nova-cert        | ian-controller  | internal | enabled | up    | 2014-02-27T02:50:05.000000 | None            |
| nova-consoleauth | ian-controller  | internal | enabled | up    | 2014-02-27T02:50:07.000000 | None            |
| nova-scheduler   | ian-controller2 | internal | enabled | up    | 2014-02-27T02:50:08.000000 | None            |
| nova-conductor   | ian-controller2 | internal | enabled | up    | 2014-02-27T02:50:08.000000 | None            |
| nova-cert        | ian-controller2 | internal | enabled | up    | 2014-02-27T02:50:02.000000 | None            |
| nova-consoleauth | ian-controller2 | internal | enabled | up    | 2014-02-27T02:50:04.000000 | None            |
+------------------+-----------------+----------+---------+-------+----------------------------+-----------------+
```

Compute: /var/log/nova/nova-compute.log

```
2014-02-27 02:16:42.505 7854 TRACE nova.virt.libvirt.driver Traceback (most recent call last):
2014-02-27 02:16:42.505 7854 TRACE nova.virt.libvirt.driver   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 677, in _connect
2014-02-27 02:16:42.505 7854 TRACE nova.virt.libvirt.driver     return libvirt.openAuth(uri, auth, flags)
2014-02-27 02:16:42.505 7854 TRACE nova.virt.libvirt.driver   File "/usr/lib/python2.7/dist-packages/libvirt.py", line 102, in openAuth
2014-02-27 02:16:42.505 7854 TRACE nova.virt.libvirt.driver     if ret is None:raise libvirtError('virConnectOpenAuth() failed')
2014-02-27 02:16:42.505 7854 TRACE nova.virt.libvirt.driver libvirtError: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
2014-02-27 02:16:42.505 7854 TRACE nova.virt.libvirt.driver
2014-02-27 02:16:42.518 7854 ERROR nova.openstack.common.threadgroup [-] 'NoneType' object has no attribute 'numOfDomains'
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup Traceback (most recent call last):
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup   File "/usr/lib/python2.7/dist-packages/nova/openstack/common/threadgroup.py", line 117, in wait
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup     x.wait()
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup   File "/usr/lib/python2.7/dist-packages/nova/openstack/common/threadgroup.py", line 49, in wait
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup     return self.thread.wait()
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup   File "/usr/lib/python2.7/dist-packages/eventlet/greenthread.py", line 168, in wait
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup     return self._exit_event.wait()
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup   File "/usr/lib/python2.7/dist-packages/eventlet/event.py", line 116, in wait
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup     return hubs.get_hub().switch()
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup   File "/usr/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 187, in switch
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup     return self.greenlet.switch()
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup   File "/usr/lib/python2.7/dist-packages/eventlet/greenthread.py", line 194, in main
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup     result = function(*args, **kwargs)
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup   File "/usr/lib/python2.7/dist-packages/nova/openstack/common/service.py", line 65, in run_service
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup     service.start()
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup   File "/usr/lib/python2.7/dist-packages/nova/service.py", line 154, in start
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup     self.manager.init_host()
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 784, in init_host
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup     self._destroy_evacuated_instances(context)
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 541, in _destroy_evacuated_instances
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup     local_instances = self._get_instances_on_driver(context, filters)
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 509, in _get_instances_on_driver
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup     driver_uuids = self.driver.list_instance_uuids()
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 725, in list_instance_uuids
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup     for domain_id in self.list_instance_ids():
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 701, in list_instance_ids
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup     if self._conn.numOfDomains() == 0:
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup AttributeError: 'NoneType' object has no attribute 'numOfDomains'
2014-02-27 02:16:42.518 7854 TRACE nova.openstack.common.threadgroup 
```

Compute: dpkg -l | grep virt

```
ii  libvirt-bin                      1.1.1-0ubuntu8.5~cloud0                    programs for the libvirt library
ii  libvirt0                         1.1.1-0ubuntu8.5~cloud0                    library for interfacing with different virtualization systems
ii  linux-headers-3.2.0-55-virtual   3.2.0-55.85                                Linux kernel headers for version 3.2.0 on 64 bit x86 Virtual Guests
ii  linux-headers-virtual            3.2.0.55.65                                Linux kernel headers for virtual machines
ii  linux-image-3.2.0-55-virtual     3.2.0-55.85                                Linux kernel image for version 3.2.0 on 64 bit x86 Virtual Guests
ii  linux-image-virtual              3.2.0.55.65                                Linux kernel image for virtual machines
ii  neutron-common                   1:2013.2.1-0ubuntu1~cloud0                 Neutron is a virtual network service for Openstack - common
ii  neutron-plugin-openvswitch       1:2013.2.1-0ubuntu1~cloud0                 Neutron is a virtual network service for Openstack - Open vSwitch plugin
ii  neutron-plugin-openvswitch-agent 1:2013.2.1-0ubuntu1~cloud0                 Neutron is a virtual network service for Openstack - Open vSwitch plugin agent
ii  python-libvirt                   1.1.1-0ubuntu8.5~cloud0                    libvirt Python bindings
ii  python-neutronclient             1:2.3.0-0ubuntu1~cloud0                    client - Neutron is a virtual network service for Openstack
ii  qemu-kvm                         1.5.0+dfsg-3ubuntu5.3~cloud0               QEMU Full virtualization on x86 hardware (transitional package)
```

Compute: /var/log/libvirt/libvirtd.log

```
2014-02-27 02:11:16.994+0000: 29845: info : libvirt version: 1.1.1
2014-02-27 02:11:16.994+0000: 29845: error : udevGetDMIData:1558 : Failed to get udev device for syspath '/sys/devices/virtual/dmi/id' or '/sys/class/dmi/id'
2014-02-27 02:11:17.079+0000: 29845: error : virExec:418 : Cannot find 'usr/lib/xen-common/bin/xen-toolstack' in path: No such file or directory
2014-02-27 02:11:17.086+0000: 29845: error : libxlMakeCapabilities:786 : internal error: Failed to get node physical info from libxenlight
2014-02-27 02:11:17.086+0000: 29845: error : libxlStateInitialize:1320 : cannot create capabilities for libxenlight
2014-02-27 02:11:17.087+0000: 29845: error : virStateInitialize:838 : Initialization of LIBXL state driver failed: internal error: Failed to get node physical info from libxenlight
```

**Comment by cloudnull** [comment]
This is a know issue in the upstream packaging. The issue has been reported and is being worked on. 

Relevant: 
https://bugs.launchpad.net/nova/+bug/1228977
https://bugs.launchpad.net/cloud-archive/+bug/1248025

**Comment by claco** [comment]
Because next time I won't want to read:

```
I know this is dirty, but...

removing /usr/lib/libvirt/connection-driver/libvirt_driver_libxl.so and /usr/lib/libvirt/connection-driver/libvirt_driver_xen.so makes libvirt-bin launch on the Rackspace public cloud.
```
