### ISSUE TITLE
[ceilometer] Cannot access horizon dashboard tab for ceilometer

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#812]
OS: Precise 12.04.3
Build: Fresh Build

When trying to access the resource usage tab, server error occurs

```
==> ceilometer-api.log <==
2014-02-27 10:46:56.833 31893 ERROR wsme.api [-] Server-side error: "metaquery not implemented". Detail: 
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/wsmeext/pecan.py", line 72, in callfunction
    result = f(self, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/ceilometer/api/controllers/v2.py", line 965, in get_all
    for r in pecan.request.storage_conn.get_resources(**kwargs)]

  File "/usr/lib/python2.7/dist-packages/ceilometer/storage/impl_sqlalchemy.py", line 310, in get_resources
    raise NotImplementedError(_('metaquery not implemented'))

NotImplementedError: metaquery not implemented
```

**Comment by cloudnull** [comment]
fixed in master, pending gating on 4.2.2rc 
https://github.com/rcbops-cookbooks/ceilometer/pull/33

**Comment by cloudnull** [comment]
Fixed https://github.com/rcbops-cookbooks/ceilometer/commit/83e1752cddf99a9784d677cce59a72aa78b7d4e1

**Comment by xeregin** [comment]
To track current ceilometer issue: https://github.com/rcbops/chef-cookbooks/issues/799
