### ISSUE TITLE
CentOS python-six >= 1.4 required by python-novaclient but not installed

### ISSUE THREAD

**Issue by breu** [rcbops/chef-cookbooks#815]
```
[root@mini-ha-neutron-3-2125-api ~]# nova list
Traceback (most recent call last):
  File "/usr/bin/nova", line 6, in <module>
    from novaclient.shell import main
  File "/usr/lib/python2.6/site-packages/novaclient/shell.py", line 47, in <module>
    import novaclient.extension
  File "/usr/lib/python2.6/site-packages/novaclient/extension.py", line 16, in <module>
    from novaclient import base
  File "/usr/lib/python2.6/site-packages/novaclient/base.py", line 32, in <module>
    from novaclient.openstack.common.apiclient import base
  File "/usr/lib/python2.6/site-packages/novaclient/openstack/common/apiclient/base.py", line 204, in <module>
    @six.add_metaclass(abc.ABCMeta)
AttributeError: 'module' object has no attribute 'add_metaclass'
```

```
Installed Packages
Name        : python-six
Arch        : noarch
Version     : 1.1.0
Release     : 2.el6
Size        : 43 k
Repo        : installed
From repo   : epel
Summary     : Python 2 and 3 compatibility utilities
URL         : http://pypi.python.org/pypi/six/
License     : MIT
Description : python-six provides simple utilities for wrapping over differences between
            : Python 2 and Python 3.
            :
            : This is the Python 2 build of the module.

Available Packages
Name        : python-six
Arch        : noarch
Version     : 1.4.1
Release     : 1.el6
Size        : 22 k
Repo        : epel
Summary     : Python 2 and 3 compatibility utilities
URL         : http://pypi.python.org/pypi/six/
License     : MIT
Description : python-six provides simple utilities for wrapping over differences between
            : Python 2 and Python 3.
            :
            : This is the Python 2 build of the module.
```

After upgrade of python-six

```
[root@mini-ha-neutron-3-2125-api ~]# nova list

```

**Comment by xeregin** [comment]
I verified that nova is working as expected on v4.2.2rc, and also verified that the version of six has been updated to 1.4.1:
[root@ian-compute ~]# nova list

[root@ian-compute ~]# pip freeze | grep six
six==1.4.1
