### ISSUE TITLE
[ceilometer] Ceilometer-common calling ceilometer dbsync on compute node

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#854]
OS: Ubuntu
Role: single-compute

Steps: Upgrading yesterdays 4.2.2 ubuntu-openstack packages to new packages released today

Setting up ceilometer-common (2013.2.2-0ubuntu1~cloud0) ...

```
Configuration file `/etc/ceilometer/ceilometer.conf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** ceilometer.conf (Y/I/N/O/D/Z) [default=N] ? 
2014-03-07 19:43:22.736 32062 CRITICAL ceilometer [-] <VerNum(20)>
2014-03-07 19:43:22.736 32062 TRACE ceilometer Traceback (most recent call last):
2014-03-07 19:43:22.736 32062 TRACE ceilometer   File "/usr/bin/ceilometer-dbsync", line 10, in <module>
2014-03-07 19:43:22.736 32062 TRACE ceilometer     sys.exit(dbsync())
2014-03-07 19:43:22.736 32062 TRACE ceilometer   File "/usr/lib/python2.7/dist-packages/ceilometer/storage/__init__.py", line 139, in dbsync
2014-03-07 19:43:22.736 32062 TRACE ceilometer     get_connection(cfg.CONF).upgrade()
2014-03-07 19:43:22.736 32062 TRACE ceilometer   File "/usr/lib/python2.7/dist-packages/ceilometer/storage/impl_sqlalchemy.py", line 153, in upgrade
2014-03-07 19:43:22.736 32062 TRACE ceilometer     migration.db_sync(session.get_bind())
2014-03-07 19:43:22.736 32062 TRACE ceilometer   File "/usr/lib/python2.7/dist-packages/ceilometer/storage/sqlalchemy/migration.py", line 68, in db_sync
2014-03-07 19:43:22.736 32062 TRACE ceilometer     versioning_api.upgrade(engine, repository)
2014-03-07 19:43:22.736 32062 TRACE ceilometer   File "/usr/lib/python2.7/dist-packages/migrate/versioning/api.py", line 186, in upgrade
2014-03-07 19:43:22.736 32062 TRACE ceilometer     return _migrate(url, repository, version, upgrade=True, err=err, **opts)
2014-03-07 19:43:22.736 32062 TRACE ceilometer   File "<string>", line 2, in _migrate
2014-03-07 19:43:22.736 32062 TRACE ceilometer   File "/usr/lib/python2.7/dist-packages/ceilometer/storage/sqlalchemy/migration.py", line 42, in patched_with_engine
2014-03-07 19:43:22.736 32062 TRACE ceilometer     return f(*a, **kw)
2014-03-07 19:43:22.736 32062 TRACE ceilometer   File "/usr/lib/python2.7/dist-packages/migrate/versioning/api.py", line 345, in _migrate
2014-03-07 19:43:22.736 32062 TRACE ceilometer     changeset = schema.changeset(version)
2014-03-07 19:43:22.736 32062 TRACE ceilometer   File "/usr/lib/python2.7/dist-packages/migrate/versioning/schema.py", line 80, in changeset
2014-03-07 19:43:22.736 32062 TRACE ceilometer     changeset = self.repository.changeset(database, start_ver, version)
2014-03-07 19:43:22.736 32062 TRACE ceilometer   File "/usr/lib/python2.7/dist-packages/migrate/versioning/repository.py", line 225, in changeset
2014-03-07 19:43:22.736 32062 TRACE ceilometer     changes = [self.version(v).script(database, op) for v in versions]
2014-03-07 19:43:22.736 32062 TRACE ceilometer   File "/usr/lib/python2.7/dist-packages/migrate/versioning/repository.py", line 189, in version
2014-03-07 19:43:22.736 32062 TRACE ceilometer     return self.versions.version(*p, **k)
2014-03-07 19:43:22.736 32062 TRACE ceilometer   File "/usr/lib/python2.7/dist-packages/migrate/versioning/version.py", line 140, in version
2014-03-07 19:43:22.736 32062 TRACE ceilometer     return self.versions[VerNum(vernum)]
2014-03-07 19:43:22.736 32062 TRACE ceilometer KeyError: <VerNum(20)>
2014-03-07 19:43:22.736 32062 TRACE ceilometer 
dpkg: error processing ceilometer-common (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of ceilometer-agent-compute:
 ceilometer-agent-compute depends on ceilometer-common (= 2013.2.2-0ubuntu1~cloud0); however:
  Package ceilometer-common is not configured yet.
dpkg: error processing ceilometer-agent-compute (--configure):
 dependency problems - leaving unconfigured
Setting up linux-generic-lts-raring (3.8.0.37.37) ...
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          Setting up linux-libc-dev (3.2.0-60.91) ...
Setting up python-neutron (1:2013.2.2-0ubuntu1~cloud0) ...
Setting up neutron-common (1:2013.2.2-0ubuntu1~cloud0) ...
Setting up neutron-plugin-openvswitch (1:2013.2.2-0ubuntu1~cloud0) ...
Setting up neutron-plugin-openvswitch-agent (1:2013.2.2-0ubuntu1~cloud0) ...
neutron-plugin-openvswitch-agent start/running, process 32119
Setting up python-nova (1:2013.2.2-0ubuntu1~cloud0) ...
Setting up nova-common (1:2013.2.2-0ubuntu1~cloud0) ...
Setting up python-keystone (1:2013.2.2-0ubuntu1~cloud0) ...
Setting up nova-compute-kvm (1:2013.2.2-0ubuntu1~cloud0) ...
Setting up nova-compute (1:2013.2.2-0ubuntu1~cloud0) ...
nova-compute start/running, process 32571
Errors were encountered while processing:
 ceilometer-common
 ceilometer-agent-compute
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@node83:~# dpkg -l | grep ceilometer
iU  ceilometer-agent-compute         2013.2.2-0ubuntu1~cloud0                   ceilometer compute agent
iF  ceilometer-common                2013.2.2-0ubuntu1~cloud0                   ceilometer common files
ii  python-ceilometer                2013.2.2-0ubuntu1~cloud0                   ceilometer python libraries
ii  python-ceilometerclient          1.0.5-0ubuntu1~cloud0                      Client library for Openstack ceilometer server.
```

**Comment by jacobwagner** [comment]
verified fixed by running chef-client on compute and seeing new package installed and not failing dbsync

```
2014-03-12T20:18:04+00:00] DEBUG: package[ceilometer-agent-compute] checking package status for ceilometer-agent-compute
[2014-03-12T20:18:04+00:00] DEBUG: package[ceilometer-agent-compute] current version is 2013.2.2-0ubuntu1~cloud0
[2014-03-12T20:18:04+00:00] DEBUG: package[ceilometer-agent-compute] candidate version is 2013.2.2-0ubuntu1~cloud0
[2014-03-12T20:18:04+00:00] DEBUG: package[ceilometer-agent-compute] is already installed - nothing to do
[2014-03-12T20:18:04+00:00] INFO: Processing package[ceilometer-common] action install (ceilometer::ceilometer-common line 37)
[2014-03-12T20:18:04+00:00] DEBUG: Platform ubuntu version 12.04 found
[2014-03-12T20:18:04+00:00] DEBUG: package[ceilometer-common] checking package status for ceilometer-common
[2014-03-12T20:18:04+00:00] DEBUG: package[ceilometer-common] current version is 2013.2.2-0ubuntu1~cloud0
[2014-03-12T20:18:04+00:00] DEBUG: package[ceilometer-common] candidate version is 2013.2.2-0ubuntu1~cloud0
[2014-03-12T20:18:04+00:00] DEBUG: package[ceilometer-common] is already installed - nothing to do
```

**Comment by hachemchrayti** [comment]
Error communicating with http://controller:8777 [Errno 111] Connection refused

How can i fix this error pleeeeeeeeeease????
-- the "ceilometer-api.log" file shows:
CRITICAL ceilometer [-] command SON([('authenticate', 1), ('user', u'ceilometer'), ('nonce', u'd87b198a63e5a3fa'), ('key', u'83f20aa83cba8ab7c982a472738f00ba')]) failed: auth fails

**Comment by breu** [comment]
@HachDev - please open a new issue.  This one is closed
