### ISSUE TITLE
[keystone] Active Directory / LDAP missing required attribute key

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#926]
OS: Ubuntu

When compiling the keystone cookbooks using AD/LDAP the recipe for keystone is missing the admin auth token variable

```
2014-04-03 14:14:35,317 RPC-QE INFO node: Running: chef-client -l debug -L "/opt/chef/2014-04-03_19:14:33-client-run.log" on node92-sat6-lab
2014-04-03 14:15:50,541 RPC-QE INFO server_helper: Building native extensions.  This could take a while...
2014-04-03 14:15:54,585 RPC-QE INFO server_helper: 
2014-04-03 14:15:54,586 RPC-QE INFO server_helper: ================================================================================
2014-04-03 14:15:54,587 RPC-QE INFO server_helper: Recipe Compile Error in /var/chef/cache/cookbooks/keystone/recipes/keystone-api.rb
2014-04-03 14:15:54,587 RPC-QE INFO server_helper: ================================================================================
2014-04-03 14:15:54,587 RPC-QE INFO server_helper: 
2014-04-03 14:15:54,588 RPC-QE INFO server_helper: 
2014-04-03 14:15:54,588 RPC-QE INFO server_helper: Chef::Exceptions::ValidationFailed
2014-04-03 14:15:54,589 RPC-QE INFO server_helper: ----------------------------------
2014-04-03 14:15:54,589 RPC-QE INFO server_helper: Required argument auth_token is missing!
2014-04-03 14:15:54,589 RPC-QE INFO server_helper: 
2014-04-03 14:15:54,590 RPC-QE INFO server_helper: 
2014-04-03 14:15:54,590 RPC-QE INFO server_helper: Cookbook Trace:
2014-04-03 14:15:54,590 RPC-QE INFO server_helper: ---------------
2014-04-03 14:15:54,590 RPC-QE INFO server_helper: /var/chef/cache/cookbooks/keystone/recipes/keystone-api.rb:81:in `block in from_file'
2014-04-03 14:15:54,590 RPC-QE INFO server_helper: /var/chef/cache/cookbooks/keystone/recipes/keystone-api.rb:76:in `from_file'
2014-04-03 14:15:54,591 RPC-QE INFO server_helper: 
2014-04-03 14:15:54,591 RPC-QE INFO server_helper: 
2014-04-03 14:15:54,591 RPC-QE INFO server_helper: Relevant File Content:
2014-04-03 14:15:54,591 RPC-QE INFO server_helper: ----------------------
2014-04-03 14:15:54,591 RPC-QE INFO server_helper: /var/chef/cache/cookbooks/keystone/recipes/keystone-api.rb:
2014-04-03 14:15:54,592 RPC-QE INFO server_helper: 
2014-04-03 14:15:54,592 RPC-QE INFO server_helper: 74:
2014-04-03 14:15:54,592 RPC-QE INFO server_helper: 75:  ## Add Services ##
2014-04-03 14:15:54,592 RPC-QE INFO server_helper: 76:  keystone_service "Create Identity Service" do
2014-04-03 14:15:54,593 RPC-QE INFO server_helper: 77:    auth_host ks_admin_endpoint["host"]
2014-04-03 14:15:54,593 RPC-QE INFO server_helper: 78:    auth_port ks_admin_endpoint["port"]
2014-04-03 14:15:54,593 RPC-QE INFO server_helper: 79:    auth_protocol ks_admin_endpoint["scheme"]
2014-04-03 14:15:54,593 RPC-QE INFO server_helper: 80:    api_ver ks_admin_endpoint["path"]
2014-04-03 14:15:54,593 RPC-QE INFO server_helper: 81>>   auth_token keystone["admin_token"]
2014-04-03 14:15:54,593 RPC-QE INFO server_helper: 82:    service_name "keystone"
2014-04-03 14:15:54,594 RPC-QE INFO server_helper: 83:    service_type "identity"
2014-04-03 14:15:54,594 RPC-QE INFO server_helper: 84:    service_description "Keystone Identity Service"
2014-04-03 14:15:54,594 RPC-QE INFO server_helper: 85:    action :create
2014-04-03 14:15:54,594 RPC-QE INFO server_helper: 86:  end
2014-04-03 14:15:54,594 RPC-QE INFO server_helper: 87:
2014-04-03 14:15:54,594 RPC-QE INFO server_helper: 88:  ## Add Endpoints ##
2014-04-03 14:15:54,595 RPC-QE INFO server_helper: 89:  node.set["keystone"]["adminURL"] = ks_admin_endpoint["uri"]
2014-04-03 14:15:54,595 RPC-QE INFO server_helper: 90:  node.set["keystone"]["internalURL"] = ks_internal_endpoint["uri"]
2014-04-03 14:15:54,595 RPC-QE INFO server_helper: 
2014-04-03 14:15:54,595 RPC-QE INFO server_helper: 
2014-04-03 14:15:54,596 RPC-QE INFO server_helper: 
2014-04-03 14:16:07,591 RPC-QE INFO server_helper: 
2014-04-03 14:16:07,591 RPC-QE INFO server_helper: ================================================================================
2014-04-03 14:16:07,591 RPC-QE INFO server_helper: Recipe Compile Error in /var/chef/cache/cookbooks/keystone/recipes/keystone-api.rb
2014-04-03 14:16:07,592 RPC-QE INFO server_helper: ================================================================================
2014-04-03 14:16:07,592 RPC-QE INFO server_helper: 
2014-04-03 14:16:07,592 RPC-QE INFO server_helper: 
2014-04-03 14:16:07,592 RPC-QE INFO server_helper: Chef::Exceptions::ValidationFailed
2014-04-03 14:16:07,592 RPC-QE INFO server_helper: ----------------------------------
2014-04-03 14:16:07,593 RPC-QE INFO server_helper: Required argument auth_token is missing!
2014-04-03 14:16:07,593 RPC-QE INFO server_helper: 
2014-04-03 14:16:07,593 RPC-QE INFO server_helper: 
2014-04-03 14:16:07,594 RPC-QE INFO server_helper: Cookbook Trace:
2014-04-03 14:16:07,594 RPC-QE INFO server_helper: ---------------
2014-04-03 14:16:07,595 RPC-QE INFO server_helper: /var/chef/cache/cookbooks/keystone/recipes/keystone-api.rb:81:in `block in from_file'
2014-04-03 14:16:07,595 RPC-QE INFO server_helper: /var/chef/cache/cookbooks/keystone/recipes/keystone-api.rb:76:in `from_file'
2014-04-03 14:16:07,595 RPC-QE INFO server_helper: 
2014-04-03 14:16:07,595 RPC-QE INFO server_helper: 
2014-04-03 14:16:07,595 RPC-QE INFO server_helper: Relevant File Content:
2014-04-03 14:16:07,596 RPC-QE INFO server_helper: ----------------------
2014-04-03 14:16:07,596 RPC-QE INFO server_helper: /var/chef/cache/cookbooks/keystone/recipes/keystone-api.rb:
2014-04-03 14:16:07,596 RPC-QE INFO server_helper: 
2014-04-03 14:16:07,596 RPC-QE INFO server_helper: 74:
2014-04-03 14:16:07,596 RPC-QE INFO server_helper: 75:  ## Add Services ##
2014-04-03 14:16:07,597 RPC-QE INFO server_helper: 76:  keystone_service "Create Identity Service" do
2014-04-03 14:16:07,597 RPC-QE INFO server_helper: 77:    auth_host ks_admin_endpoint["host"]
2014-04-03 14:16:07,597 RPC-QE INFO server_helper: 78:    auth_port ks_admin_endpoint["port"]
2014-04-03 14:16:07,597 RPC-QE INFO server_helper: 79:    auth_protocol ks_admin_endpoint["scheme"]
2014-04-03 14:16:07,597 RPC-QE INFO server_helper: 80:    api_ver ks_admin_endpoint["path"]
2014-04-03 14:16:07,597 RPC-QE INFO server_helper: 81>>   auth_token keystone["admin_token"]
2014-04-03 14:16:07,598 RPC-QE INFO server_helper: 82:    service_name "keystone"
2014-04-03 14:16:07,598 RPC-QE INFO server_helper: 83:    service_type "identity"
2014-04-03 14:16:07,598 RPC-QE INFO server_helper: 84:    service_description "Keystone Identity Service"
2014-04-03 14:16:07,598 RPC-QE INFO server_helper: 85:    action :create
2014-04-03 14:16:07,598 RPC-QE INFO server_helper: 86:  end
2014-04-03 14:16:07,599 RPC-QE INFO server_helper: 87:
2014-04-03 14:16:07,599 RPC-QE INFO server_helper: 88:  ## Add Endpoints ##
2014-04-03 14:16:07,599 RPC-QE INFO server_helper: 89:  node.set["keystone"]["adminURL"] = ks_admin_endpoint["uri"]
2014-04-03 14:16:07,599 RPC-QE INFO server_helper: 90:  node.set["keystone"]["internalURL"] = ks_internal_endpoint["uri"]
2014-04-03 14:16:07,599 RPC-QE INFO server_helper: 
2014-04-03 14:16:07,599 RPC-QE INFO server_helper: 
2014-04-03 14:16:07,600 RPC-QE INFO server_helper: 
```

**Comment by claco** [comment]
I assume this wasn't a problem on Havana/4.2.2. Wonder if I missed a backport somewhere.

**Comment by jcannava** [comment]
The value that won't compile should be set automatically when "developer_mode" is true (string provided in recipe) or false (secure_password string). This hasn't changed between versions and at least looks correct. Can we try to reproduce again?

**Comment by claco** [comment]
@jacobwagner Any status on this.. still a problem.. or config issue.. or both?

**Comment by jacobwagner** [comment]
I am going to rebuild this now

**Comment by jacobwagner** [comment]
I am still seeing this. I am going to leave the build up and investigate. Might need another set of eyes
