### ISSUE TITLE
controller always includes nova-network-controller

### ISSUE THREAD

**Issue by eliasdc** [rcbops/chef-cookbooks#966]
My setup: 
Controller node attached to management/nova and public network
Network node attached to management/nova, public and data network
Compute nodes attached to management/nova and data network

In this setup the installation of the controller fails because the server is not connected to the datanetwork. It fails because ha1-controller or single-controller try to install the nova-network-controller role which should be on the network node.

Is this setup so uncommon?

my environment file: 

```
{
  "name": "private-cloud",
  "description": "Rackspace Private Cloud OpenStack Environment for IBCN",
  "cookbook_versions": {
  },
  "json_class": "Chef::Environment",
  "chef_type": "environment",
  "default_attributes": {
  },
  "override_attributes": {
    "developer_mode": false,
    "enable_testing_repos": false,
    "monitoring" : {
      "metric_provider" : "collectd",
      "procmon_provider" : "monit"
    },
    "glance": {
      "api": {
        "default_store": "file"
      },
      "image_upload": true,
      "image": {
        "raring": "http://cloud-images.ubuntu.com/raring/current/raring-server-cloudimg-amd64-disk1.img",
        "trusty": "http://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img"
      },
      "images": ["cirros", "precise","raring","trusty" ]
    },
    "nova": {
        "config": {
              "ram_allocation_ratio": 1.0,
              "disk_allocation_ratio": 1.0,
              "cpu_allocation_ratio": 2.0,
              "resume_guests_state_on_host_boot": true
            },
      "ratelimit" : {
        "api" : { "enabled" : false },
        "volume" : { "enabled" : false }
      },
      "libvirt": { 
        "virt_type": "kvm",
        "vncserver_listen": "0.0.0.0"
      },
      "network": {
        "provider": "neutron"
      }
    },
    "keystone": {
        "pki": {
          "enabled": false
        },
        "admin_user": "admin",
        "tenants": [
          "service",
          "admin",
          "demo",
          "playground",
          "aiolos"
        ],
        "users": {
          "admin": {
            "password": "admin_pass",
            "roles": {
              "admin": [
                "admin"
              ]
            }
          },
          "demo": {
            "password": "demo_pass",
            "default_tenant": "demo",
            "roles": {
              "Member": [
                "demo", "playground"
              ]
            }
          },
          "playground": {
            "password": "playground_pass",
            "default_tenant": "playground",
            "roles": {
              "Member": [
                "playground"
              ]
            }
          },
          "aiolos": {
            "password": "aiolos_pass",
            "default_tenant": "aiolos",
            "roles": {
              "Member": [
                "aiolos"
              ]
            }
          }
        }
      },
    "neutron": {
      "ovs": {
        "network_type": "gre",
        "network": "data"
      }
    },
    "mysql": {
      "allow_remote_root": true,
      "root_network_acl": "%"
    },
    "osops_networks": {
      "nova": "10.0.0.0/24",
      "public": "10.10.0.0/17",
      "management": "10.0.0.0/24",
      "data": "10.0.1.0/24"
    }
  }
}
```

**Comment by claco** [comment]
What chef roles do you have assigned to all of the nodes?

**Comment by eliasdc** [comment]
just started with the controller with role['ha-controller1']

This is the error I get with chef-client:

```
openstack1.test Recipe Compile Error in /var/chef/cache/cookbooks/nova-network/recipes/nova-controller.rb
openstack1.test ================================================================================
openstack1.test
openstack1.test
openstack1.test RuntimeError
openstack1.test ------------
openstack1.test Can't find address on network data for node
openstack1.test
openstack1.test
openstack1.test Cookbook Trace:
openstack1.test ---------------
openstack1.test   /var/chef/cache/cookbooks/osops-utils/libraries/ip_location.rb:52:in `rcb_exit_error'
openstack1.test   /var/chef/cache/cookbooks/osops-utils/libraries/ip_location.rb:113:in `get_if_ip_for_net'
openstack1.test   /var/chef/cache/cookbooks/osops-utils/libraries/ip_location.rb:75:in `get_ip_for_net'
openstack1.test   /var/chef/cache/cookbooks/nova-network/recipes/neutron-common.rb:54:in `from_file'
openstack1.test   /var/chef/cache/cookbooks/nova-network/recipes/neutron-server.rb:56:in `from_file'
openstack1.test   /var/chef/cache/cookbooks/nova-network/recipes/nova-controller.rb:22:in `from_file'
```

**Comment by claco** [comment]
I'm making some assumptions here. First, the error indicates that your data network interface has no ip, which is expected. You can simply remove:

```
      "data": "10.0.1.0/24"
```

from your `osops_networks`, and remove:

```
        "network": "data"
```

from your `neutron: ovs` configuration, and then point your neutron config to the physical interface or bridge for your data network, tailored to your specific setup: https://github.com/rsoprivatecloud/openstack-chef-deploy/blob/master/environments/havana-neutron-vips.json#L112-L123
