### ISSUE TITLE
Ceilometer-common calling ceilometer dbsync on compute node

### ISSUE THREAD

**Issue by jklint** [rcbops/chef-cookbooks#975]
OS: Ubuntu 12.04
Role: single-compute
Steps: apt-get update; apt-get upgrade -y
(Seems identical to https://github.com/rcbops/chef-cookbooks/issues/854)

Setting up ceilometer-common (2013.2.3-0ubuntu1~cloud0) ...
2014-11-03 23:39:22.627 12724 CRITICAL ceilometer [-] <VerNum(20)>
2014-11-03 23:39:22.627 12724 TRACE ceilometer Traceback (most recent call last):
2014-11-03 23:39:22.627 12724 TRACE ceilometer   File "/usr/bin/ceilometer-dbsync", line 10, in <module>
2014-11-03 23:39:22.627 12724 TRACE ceilometer     sys.exit(dbsync())
2014-11-03 23:39:22.627 12724 TRACE ceilometer   File "/usr/lib/python2.7/dist-packages/ceilometer/storage/**init**.py", line 139, in dbsync
2014-11-03 23:39:22.627 12724 TRACE ceilometer     get_connection(cfg.CONF).upgrade()
2014-11-03 23:39:22.627 12724 TRACE ceilometer   File "/usr/lib/python2.7/dist-packages/ceilometer/storage/impl_sqlalchemy.py", line 153, in upgrade
2014-11-03 23:39:22.627 12724 TRACE ceilometer     migration.db_sync(session.get_bind())
2014-11-03 23:39:22.627 12724 TRACE ceilometer   File "/usr/lib/python2.7/dist-packages/ceilometer/storage/sqlalchemy/migration.py", line 68, in db_sync
2014-11-03 23:39:22.627 12724 TRACE ceilometer     versioning_api.upgrade(engine, repository)
2014-11-03 23:39:22.627 12724 TRACE ceilometer   File "/usr/lib/python2.7/dist-packages/migrate/versioning/api.py", line 186, in upgrade
2014-11-03 23:39:22.627 12724 TRACE ceilometer     return _migrate(url, repository, version, upgrade=True, err=err, *_opts)
2014-11-03 23:39:22.627 12724 TRACE ceilometer   File "<string>", line 2, in _migrate
2014-11-03 23:39:22.627 12724 TRACE ceilometer   File "/usr/lib/python2.7/dist-packages/ceilometer/storage/sqlalchemy/migration.py", line 42, in patched_with_engine
2014-11-03 23:39:22.627 12724 TRACE ceilometer     return f(_a, *_kw)
2014-11-03 23:39:22.627 12724 TRACE ceilometer   File "/usr/lib/python2.7/dist-packages/migrate/versioning/api.py", line 345, in _migrate
2014-11-03 23:39:22.627 12724 TRACE ceilometer     changeset = schema.changeset(version)
2014-11-03 23:39:22.627 12724 TRACE ceilometer   File "/usr/lib/python2.7/dist-packages/migrate/versioning/schema.py", line 80, in changeset
2014-11-03 23:39:22.627 12724 TRACE ceilometer     changeset = self.repository.changeset(database, start_ver, version)
2014-11-03 23:39:22.627 12724 TRACE ceilometer   File "/usr/lib/python2.7/dist-packages/migrate/versioning/repository.py", line 225, in changeset
2014-11-03 23:39:22.627 12724 TRACE ceilometer     changes = [self.version(v).script(database, op) for v in versions]
2014-11-03 23:39:22.627 12724 TRACE ceilometer   File "/usr/lib/python2.7/dist-packages/migrate/versioning/repository.py", line 189, in version
2014-11-03 23:39:22.627 12724 TRACE ceilometer     return self.versions.version(_p, **k)
2014-11-03 23:39:22.627 12724 TRACE ceilometer   File "/usr/lib/python2.7/dist-packages/migrate/versioning/version.py", line 140, in version
2014-11-03 23:39:22.627 12724 TRACE ceilometer     return self.versions[VerNum(vernum)]
2014-11-03 23:39:22.627 12724 TRACE ceilometer KeyError: <VerNum(20)>
2014-11-03 23:39:22.627 12724 TRACE ceilometer 
dpkg: error processing ceilometer-common (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of ceilometer-agent-compute:
 ceilometer-agent-compute depends on ceilometer-common (= 2013.2.3-0ubuntu1~cloud0); however:
  Package ceilometer-common is not configured yet.
dpkg: error processing ceilometer-agent-compute (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          Errors were encountered while processing:
 ceilometer-common
 ceilometer-agent-compute
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@552321-compute02:~# dpkg -l | grep ceilometer
iU  ceilometer-agent-compute             2013.2.3-0ubuntu1~cloud0                   ceilometer compute agent
iF  ceilometer-common                    2013.2.3-0ubuntu1~cloud0                   ceilometer common files
ii  python-ceilometer                    2013.2.3-0ubuntu1~cloud0                   ceilometer python libraries
ii  python-ceilometerclient              1.0.5-0ubuntu1~cloud0                      Client library for Openstack ceilometer server.

**Comment by claco** [comment]
This is fixed in master, and in 4.2.3rc  with this commit: https://github.com/rcbops-cookbooks/ceilometer/commit/65944d8def87fa94fab5e48333575b77dd189b39
